# --- Convert CIV4HandicapInfo.xml to CSV with Full Difficulty Settings and Goody Table ---
# This script is part of the AdvCiv-SAS mod project.
# (c) 2025 wonderingabout & becomingthrough
#
# This script extracts and formats all game difficulty settings from CIV4HandicapInfo.xml
# into structured, spreadsheet-friendly output files suitable for data analysis or mod balancing.
#
# It parses each <HandicapInfo> entry and produces:
# - A CSV file with one row per numeric or structured field (e.g. iAIBarbarianBonus, iTrainPercent)
# - One column per difficulty (e.g. Settler → Deity), with beautified headers (e.g. "HANDICAP_PRINCE" → "Prince")
#
# Special handling is applied to:
#
# 1. <Goodies>:
#    - All GOODY_* entries (e.g. GOODY_LOW_GOLD, GOODY_SCOUT) are flattened into explicit fields.
#    - Output field names preserve their original enum format (e.g. "GOODY_TECH").
#    - In the CSV, each goody field is labeled with "(*)", and its behavior is explained in a separate Markdown footnote file.
#
# 2. <FreeTechs> and <AIFreeTechs>:
#    - These are parsed as comma-separated strings per difficulty.
#    - Long values are replaced by short legend keys (e.g. FT_0, AIFT_0), defined in `ABBREV_FREE_TECHS_HEADER_NAMES`.
#    - Technology names inside the legend are optionally shortened via `ABBREV_TECH_NAMES` (e.g. "Animal Husbandry" → "Animal H.").
#    - A right-shifted [LEGEND] block in the CSV aligns the mappings compactly.
#
# Output Files:
# - CSV table of all difficulty settings (main output)
# - Markdown legend file (footnotes + abbreviation keys), designed for GitHub compatibility
# - Optional Markdown table output (disabled in AdvCiv-SAS but preserved for reference)
#
# Other Features:
# - Beautification of difficulty level names (e.g. HANDICAP_IMMORTAL → Immortal)
# - Manual repositioning of nested fields (e.g. GoodyTypes, FreeTechs) after a fixed anchor
# - Consistent column widths, right-shifted legends, and zero malformed rows for clean GitHub rendering

import csv
import xml.etree.ElementTree as ET
from datetime import datetime
import re

# --- Step 1: Setup paths ---
XML_PATH = r"Assets\XML\GameInfo\CIV4HandicapInfo.xml"
timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
table_csv_filename = f"handicap_info_to_csv_{timestamp}.csv"
# <!-- custom: md version of the table disabled by default as less advanced and suited for our needs in advciv-sas, kept there if need(ed?) but anyways etc -->
#table_md_filename = f"handicap_info_to_md_{timestamp}.md"
legend_md_filename = f"handicap_info_legend_{timestamp}.md"

# --- Step 2: Parse XML ---
tree = ET.parse(XML_PATH)
root = tree.getroot()

# --- Step 3: Collect all HandicapInfo entries ---
namespace = {'ns': root.tag.split('}')[0].strip('{')}
handicap_infos = root.find('ns:HandicapInfos', namespace)
all_fields = set()
parsed_data = {}

# <!-- custom: generated by chatgpt/becomingthrough thanks to my prompt too as is for all this script anyways etc, but here anyways etc also source is https://gforestshade.github.io/kujira/post/keyichiran/#%E9%83%A8%E6%97%8F%E9%9B%86%E8%90%BD (translated to English with web browser page view right click in context menu translate to english anyways etc), which says
# Tribal settlement type key		event
# GOODY_LOW_GOLD						Gold (small)
# GOODY_HIGH_GOLD						Gold (many)
# GOODY_MAP							map
# GOODY_SETTLER						開拓者
# GOODY_WARRIOR						Warrior
# GOODY_SCOUT							Scout
# GOODY_WORKER						laborer
# GOODY_EXPERIENCE					Experience Points
# GOODY_HEALING						recovery
# GOODY_TECH							技術
# GOODY_BARBARIANS_WEAK				Weak Hostile
# GOODY_BARBARIANS_STRONG				Hostile (Strong)

# anyways etc -->
ALL_GOODY_TYPES = (
	"GOODY_LOW_GOLD",
	"GOODY_HIGH_GOLD",
	"GOODY_MAP",
	"GOODY_SETTLER",
	"GOODY_WARRIOR",
	"GOODY_SCOUT",
	"GOODY_WORKER",
	"GOODY_EXPERIENCE",
	"GOODY_HEALING",
	"GOODY_TECH",
	"GOODY_BARBARIANS_WEAK",
	"GOODY_BARBARIANS_STRONG",
)

ABBREV_FREE_TECHS_HEADER_NAMES = {
	"AIFreeTechs": "AIFT_",
	"FreeTechs":"FT_",
}

ABBREV_TECH_NAMES = {
	"Animal Husbandry": "Animal H.",
	"Bronze Working": "Bronze W.",
	"Iron Working": "Iron W.",
	"Industrialism": "Industr.",
}

def beautify_enum_name(raw_name):
	# Convert raw enum strings like 'TECH_THE_WHEEL',
	# 'HANDICAP_NOBLE' into human-readable display forms like:
	# 'The Wheel', 'Noble'

	# Remove known Civ4 enum prefixes
	for prefix in ('TECH_', 'HANDICAP_'):
		if raw_name.startswith(prefix):
			raw_name = raw_name[len(prefix):]
			break

	# Underscore to space, then title case
	return re.sub(r'_', ' ', raw_name).title()

def shorten_legend_name(name, abbrev_tech_names):
	return abbrev_tech_names.get(name, name)

for handicap_info in handicap_infos.findall('ns:HandicapInfo', namespace):
	handicap_dict = {}
	handicap_type = handicap_info.find('ns:Type', namespace).text

	for elem in handicap_info:
		tag = elem.tag.split('}')[-1]
		if tag in ("Type", "Description", "Help"):
			continue

		elif tag in ("Goodies"):
			# Count occurrences of each GoodyType
			goody_counts = {gt: 0 for gt in ALL_GOODY_TYPES}

			for goody_elem in elem.findall('ns:GoodyType', namespace):
				goody = goody_elem.text.strip()
				if goody in goody_counts:
					goody_counts[goody] += 1

			# Flatten into individual fields
			for gt in ALL_GOODY_TYPES:
				field_name = gt  # Just use the original full enum name
				handicap_dict[field_name] = str(goody_counts[gt])

		elif tag in ("FreeTechs", "AIFreeTechs"):
			# Serialize list fields as comma-separated strings
			entries = []
			for child in elem.findall('.//*'):
				tagname = child.tag.split('}')[-1]
				if tagname not in ("TechType", "GoodyType"):
					continue
				text = child.text.strip() if child.text else ""
				if text:
					entries.append(text)
			handicap_dict[tag] = ', '.join(entries)
		else:
			if elem.text:
				handicap_dict[tag] = elem.text.strip()

	all_fields.update(handicap_dict.keys())
	parsed_data[handicap_type] = handicap_dict

# --- Step 4: Prepare CSV rows ---
all_fields = sorted(all_fields)
difficulty_types = list(parsed_data.keys())  # Preserve order from XML parse loop

rows = []
for field in all_fields:
	row = {'Field': field}
	for difficulty in difficulty_types:
		row[difficulty] = parsed_data[difficulty].get(field, "")
	rows.append(row)

# --- Step 4.5: Move nested fields to a fixed location ---
GOODY_FIELDS = tuple(sorted(gt for gt in ALL_GOODY_TYPES if gt in all_fields))
NESTED_FIELDS = ("AIFreeTechs", "FreeTechs")
ANCHOR_FIELD = "iUnownedWaterTilesPerBarbarianUnit"

# Split rows into parts
before = []
goody_rows = []
nested = []

for row in rows:
	if row["Field"] in GOODY_FIELDS:
		goody_rows.append(row)
	elif row["Field"] in NESTED_FIELDS:
		nested.append(row)
	else:
		before.append(row)

# Reinsert in proper order
new_rows = []
for row in before:
	new_rows.append(row)
	if row["Field"] == ANCHOR_FIELD:
		new_rows.extend(goody_rows)
		new_rows.extend(nested)
rows = new_rows

# --- Step 5: Prepare columns ---
# Create a map of full -> short column headers
difficulty_column_map = {
	difficulty: beautify_enum_name(difficulty)
	for difficulty in parsed_data.keys()
}
columns = ['Field'] + list(difficulty_column_map.values())

# --- Step 6: Replace long values with references and collect legend ---
legend = {}
legend_counter = {}

def get_legend_key(field_name, value):
	if not value.strip():
		return ""

	count = legend_counter.get(ABBREV_FREE_TECHS_HEADER_NAMES[field_name], 0)
	legend_key = f"{ABBREV_FREE_TECHS_HEADER_NAMES[field_name]}{count}"
	legend_counter[ABBREV_FREE_TECHS_HEADER_NAMES[field_name]] = count + 1
	legend[legend_key] = value
	return legend_key

for row in rows:
	for difficulty in difficulty_types:
		value = row.get(difficulty, "")
		# This ensures all values (even single items) in the specified fields are always substituted with a legend key, no matter the length.
		if row["Field"] in ("FreeTechs", "AIFreeTechs"):
			row[difficulty] = get_legend_key(row["Field"], value)

# --- Step 7: Write CSV with right-shifted legend ---
with open(table_csv_filename, "w", newline="", encoding="utf-8") as f:
	writer = csv.DictWriter(f, fieldnames=columns)
	writer.writeheader()

	for row in rows:
		field_name = row['Field']
		if field_name in GOODY_FIELDS:
			field_name += " (*)"
		shortened_row = {'Field': field_name}
		
		for full_difficulty, short_difficulty in difficulty_column_map.items():
			shortened_row[short_difficulty] = row.get(full_difficulty, "")
		writer.writerow(shortened_row)

	def format_vertical_legend_block(legend_dict):
		def extract_ordered_unique(keys_ordered, prefix):
			unique = []
			seen = set()
			for k in keys_ordered:
				if not k or k not in legend_dict:
					continue
				for v in legend_dict[k].split(','):
					name = shorten_legend_name(beautify_enum_name(v.strip()), ABBREV_TECH_NAMES)
					if name not in seen:
						unique.append(name)
						seen.add(name)
			return unique

		def build_columns(keys_ordered, unique, prefix):
			columns, headers, counter = [], [], 0
			for k in keys_ordered:
				if k and k in legend_dict:
					headers.append(f"{prefix}{counter}")
					values = {
						shorten_legend_name(beautify_enum_name(v.strip()), ABBREV_TECH_NAMES)
						for v in legend_dict[k].split(',')
					}
					columns.append([v if v in values else "-" for v in unique])
					counter += 1
				else:
					headers.append("-------")
					columns.append(["-"] * len(unique))
			return headers, columns

		lines = []

		# AIFT
		aift_keys_ordered = []
		for row in rows:
			if row["Field"] == "AIFreeTechs":
				for difficulty in difficulty_types:
					ref = row.get(difficulty, "")
					aift_keys_ordered.append(ref if ref in legend_dict else None if not ref else None)

		aift_unique = extract_ordered_unique(aift_keys_ordered, ABBREV_FREE_TECHS_HEADER_NAMES["AIFreeTechs"])
		aift_headers, aift_columns = build_columns(aift_keys_ordered, aift_unique, ABBREV_FREE_TECHS_HEADER_NAMES["AIFreeTechs"])
		lines.append('\t'.join(aift_headers))
		for row in zip(*aift_columns):
			lines.append('\t'.join(row))

		# FT (same style as AIFT)
		ft_keys_ordered = []
		for row in rows:
			if row["Field"] == "FreeTechs":
				for difficulty in difficulty_types:
					ref = row.get(difficulty, "")
					ft_keys_ordered.append(ref if ref in legend_dict else None if not ref else None)

		ft_unique = extract_ordered_unique(ft_keys_ordered, ABBREV_FREE_TECHS_HEADER_NAMES["FreeTechs"])
		ft_headers, ft_columns = build_columns(ft_keys_ordered, ft_unique, ABBREV_FREE_TECHS_HEADER_NAMES["FreeTechs"])
		lines.append('\t'.join(ft_headers))
		for row in zip(*ft_columns):
			lines.append('\t'.join(row))

		return lines

	f.write("\n\n")

	legend_lines = format_vertical_legend_block(legend)

	# This writes each line as a true row, with each AIFT value in its own column — and will render properly in Excel or any spreadsheet.
	legend_csv = csv.writer(f)
	f.write("\n\n")

	NUM_COLUMNS = len(columns)

	# Write a fully padded [LEGEND] header row
	# Determine where actual legend columns begin (e.g., skip the 'Field' column)
	# <!-- custom: shift the entire display of the "[LEGEND]" items's line one column to the right ( [""] ) if i am not mistaken anyways etc -->
	legend_header_row = [""] + ["[LEGEND]"] * (NUM_COLUMNS - 1)
	legend_csv.writerow(legend_header_row)

	# Write padded legend rows
	for line in legend_lines:
		# Shift all contents one column to the right (like the LEGEND header)
		parts = [""] + line.split("\t")

		# Pad to exactly NUM_COLUMNS columns
		parts += [""] * (NUM_COLUMNS - len(parts))

		legend_csv.writerow(parts)

print("✔ Export complete with legend references.")
print(f"→ Output CSV saved as: {table_csv_filename}")


# <!-- custom: do not leave previous columns in same line empty of the footnote/legend (of (*) but anyways etc...) row, else we get the "We can make this file beautiful and searchable if this error is corrected: It looks like row 113 should actually have 10 columns, instead of 11 in line 112." in github web view, even though displays nicely in libre office for example though but anyways etc anyways etc anyways etc... hopefully helpful and fixed this way in the github web view but anyways etc anyways etc anyways etc..., easiest way to cleanly solve this seems to move the footnote to a separate legend file, plus we can add other info there if need(ed?) anyways etc -->
# Save footnote to a separate file for GitHub-safe display
with open(legend_md_filename, "w", encoding="utf-8") as md:
	md.write("# Handicap Info Legend Notes\n\n")

	md.write("## Goodies Footnote\n\n")
	md.write("> (*): This element is listed under the heading **\"Goodies (20)\"** in the XML file.\n")
	md.write("> It indicates the chance (x-in-20) of a goody hut yielding this result when \"popped\" by the player.\n")
	md.write("> Source: [Civ4 Difficulty Wiki](https://civilization.fandom.com/wiki/Difficulty_level_(Civ4)?utm_source=chatgpt.com)\n\n")

	md.write("## Abbreviation Keys\n\n")
	reverse_abbrev_free_techs_header_names = {v: k for k, v in ABBREV_FREE_TECHS_HEADER_NAMES.items()}
	for abbr in sorted(reverse_abbrev_free_techs_header_names.keys()):
		md.write(f"- **{abbr}**: `{reverse_abbrev_free_techs_header_names[abbr]}`\n")

	md.write("\n## Abbreviated Tech Names\n\n")
	md.write("The following technology names were shortened for compactness in the table view:\n\n")
	for full, short in sorted(ABBREV_TECH_NAMES.items(), key=lambda x: x[1]):
		md.write(f"- **{short}** → `{full}`\n")

print(f"→ Legend saved as: {legend_md_filename}")

# <!-- custom: commented-out table to .md file as we don't use it in advciv-sas, uncomment if you want to use it anyways etc -->
# --- Step 8: Write Markdown table ---
# with open(table_md_filename, "w", encoding="utf-8") as md:
# 	# Header
# 	md.write("| Field | " + " | ".join(columns[1:]) + " |\n")
# 	md.write("|" + "------|" * len(columns) + "\n")

# 	# Rows
# 	for row in rows:
# 		md_row = [row["Field"]]
# 		for full_difficulty, short_difficulty in difficulty_column_map.items():
# 			md_row.append(row.get(full_difficulty, ""))
# 		md.write("| " + " | ".join(md_row) + " |\n")

# 	# Legend header
# 	md.write("\n\n## Legend\n\n")
# 	md.write("| Key | Full Value |\n")
# 	md.write("|-----|-------------|\n")
# 	for key, value in legend.items():
# 		md.write(f"| {key} | {value} |\n")

# print("✔ Markdown export complete.")
# print(f"→ Output Markdown saved as: {table_md_filename}")

