# <!-- custom: --- Test data module of expected parsed leaders_data py output to test against the real parsed leaders data py file during its creation --> --- 
# (c) 2025 wonderingabout & becomingthrough

def get_expected_output_PARSED_XML_LEADERS_DATA_SAMPLE():
	return {
		"LEADER_BARBARIAN": {
			"Type": "LEADER_BARBARIAN",
			"Description": "TXT_KEY_LEADER_BARBARIAN",
			"Civilopedia": "TXT_KEY_LEADER_BARBARIAN_PEDIA",
			"ArtDefineTag": "ART_DEF_LEADER_BARBARIAN",
			"getWonderConstructRand": "0",
			"getBaseAttitude": "0",
			"getBasePeaceWeight": "0",
			"getPeaceWeightRand": "0",
			"getWarmongerRespect": "0",
			"getEspionageWeight": "0",
			"getRefuseToTalkWarThreshold": "0",
			"getNoTechTradeThreshold": "0",
			"getTechTradeKnownPercent": "0",
			"getMaxGoldTradePercent": "0",
			"getMaxGoldPerTurnTradePercent": "0",
			"getCultureVictoryWeight": "0",
			"getSpaceVictoryWeight": "0",
			"getConquestVictoryWeight": "120",
			"getDominationVictoryWeight": "30",
			"getDiplomacyVictoryWeight": "0",
			"getMaxWarRand": "0",
			"getMaxWarNearbyPowerRatio": "0",
			"getMaxWarDistantPowerRatio": "0",
			"getMaxWarMinAdjacentLandPercent": "0",
			"getLimitedWarRand": "0",
			"getLimitedWarPowerRatio": "0",
			"getDogpileWarRand": "0",
			"getMakePeaceRand": "0",
			"getDeclareWarTradeRand": "0",
			"getDemandRebukedSneakProb": "0",
			"getDemandRebukedWarProb": "0",
			"getRazeCityProb": "60",
			"getBuildUnitProb": "70",
			"getBaseAttackOddsChange": "1",
			"getAttackOddsChangeRand": "16",
			"getWorseRankDifferenceAttitudeChange": "-2",
			"getBetterRankDifferenceAttitudeChange": "0",
			"getCloseBordersAttitudeChange": "-2",
			"getLostWarAttitudeChange": "0",
			"getAtWarAttitudeDivisor": "0",
			"getAtWarAttitudeChangeLimit": "0",
			"getAtPeaceAttitudeDivisor": "0",
			"getAtPeaceAttitudeChangeLimit": "0",
			"getSameReligionAttitudeChange": "0",
			"getSameReligionAttitudeDivisor": "0",
			"getSameReligionAttitudeChangeLimit": "0",
			"getDifferentReligionAttitudeChange": "0",
			"getDifferentReligionAttitudeDivisor": "0",
			"getDifferentReligionAttitudeChangeLimit": "0",
			"getBonusTradeAttitudeDivisor": "0",
			"getBonusTradeAttitudeChangeLimit": "0",
			"getOpenBordersAttitudeDivisor": "0",
			"getOpenBordersAttitudeChangeLimit": "0",
			"getDefensivePactAttitudeDivisor": "0",
			"getDefensivePactAttitudeChangeLimit": "0",
			"getShareWarAttitudeChange": "0",
			"getShareWarAttitudeDivisor": "0",
			"getShareWarAttitudeChangeLimit": "0",
			"getFavoriteCivicAttitudeChange": "0",
			"getFavoriteCivicAttitudeDivisor": "0",
			"getFavoriteCivicAttitudeChangeLimit": "0",
			"getDemandTributeAttitudeThreshold": -1,
			"getNoGiveHelpAttitudeThreshold": -1,
			"getTechRefuseAttitudeThreshold": -1,
			"getCityRefuseAttitudeThreshold": -1,
			"getNativeCityRefuseAttitudeThreshold": -1,
			"getStrategicBonusRefuseAttitudeThreshold": -1,
			"getHappinessBonusRefuseAttitudeThreshold": -1,
			"getHealthBonusRefuseAttitudeThreshold": -1,
			"getMapRefuseAttitudeThreshold": -1,
			"getDeclareWarRefuseAttitudeThreshold": -1,
			"getDeclareWarThemRefuseAttitudeThreshold": -1,
			"getStopTradingRefuseAttitudeThreshold": -1,
			"getStopTradingThemRefuseAttitudeThreshold": -1,
			"getAdoptCivicRefuseAttitudeThreshold": -1,
			"getConvertReligionRefuseAttitudeThreshold": -1,
			"getOpenBordersRefuseAttitudeThreshold": -1,
			"getDefensivePactRefuseAttitudeThreshold": -1,
			"getPermanentAllianceRefuseAttitudeThreshold": -1,
			"getVassalRefuseAttitudeThreshold": -1,
			"getVassalPowerModifier": "0",
			"getFreedomAppreciation": "0",
			"FavoriteCivic": "NONE",
			"FavoriteReligion": "NONE",
			"Traits": "",
			"iFlavorMilitary": 0,
			"UnitAIWeightModifiers": [
				{
					"UnitAIType": "UNITAI_RESERVE",
					"iWeightModifier": "75"
				},
				{
					"UnitAIType": "UNITAI_ATTACK_CITY",
					"iWeightModifier": "75"
				},
				{
					"UnitAIType": "UNITAI_WORKER",
					"iWeightModifier": "75"
				}
			],
			"ImprovementWeightModifiers": "",
			"DiplomacyIntroMusicPeace": "",
			"DiplomacyMusicPeace": [
				{
					"EraType": "ERA_ANCIENT",
					"DiploScriptId": "AS2D_DIPLO_RAGNAR_EARLY"
				},
				{
					"EraType": "ERA_CLASSICAL",
					"DiploScriptId": "AS2D_DIPLO_RAGNAR_EARLY"
				},
				{
					"EraType": "ERA_MEDIEVAL",
					"DiploScriptId": "AS2D_DIPLO_RAGNAR_MIDDLE"
				},
				{
					"EraType": "ERA_RENAISSANCE",
					"DiploScriptId": "AS2D_DIPLO_RAGNAR_MIDDLE"
				},
				{
					"EraType": "ERA_INDUSTRIAL",
					"DiploScriptId": "AS2D_DIPLO_RAGNAR_LATE"
				},
				{
					"EraType": "ERA_MODERN",
					"DiploScriptId": "AS2D_DIPLO_RAGNAR_LATE"
				},
				{
					"EraType": "ERA_FUTURE",
					"DiploScriptId": "AS2D_DIPLO_RAGNAR_LATE"
				}
			],
			"DiplomacyIntroMusicWar": "",
			"DiplomacyMusicWar": [
				{
					"EraType": "ERA_ANCIENT",
					"DiploScriptId": "AS2D_DIPLO_WARDRUMS_EARLY"
				},
				{
					"EraType": "ERA_CLASSICAL",
					"DiploScriptId": "AS2D_DIPLO_WARDRUMS_EARLY"
				},
				{
					"EraType": "ERA_MEDIEVAL",
					"DiploScriptId": "AS2D_DIPLO_WARDRUMS_MIDDLE"
				},
				{
					"EraType": "ERA_RENAISSANCE",
					"DiploScriptId": "AS2D_DIPLO_WARDRUMS_MIDDLE"
				},
				{
					"EraType": "ERA_INDUSTRIAL",
					"DiploScriptId": "AS2D_DIPLO_WARDRUMS_LATE"
				},
				{
					"EraType": "ERA_MODERN",
					"DiploScriptId": "AS2D_DIPLO_WARDRUMS_LATE"
				},
				{
					"EraType": "ERA_FUTURE",
					"DiploScriptId": "AS2D_DIPLO_WARDRUMS_LATE"
				}
			],
			"iNoWarAttitudeProbFurious": 0,
			"iNoWarAttitudeProbAnnoyed": 0,
			"iNoWarAttitudeProbCautious": 0,
			"iNoWarAttitudeProbPleased": 0,
			"iNoWarAttitudeProbFriendly": 100,
			"iLoveOfPeace": 0,
			"iFlavorReligion": 0,
			"iFlavorProduction": 0,
			"iFlavorGold": 0,
			"iFlavorScience": 0,
			"iFlavorCulture": 0,
			"iFlavorGrowth": 0,
			"iFlavorEspionage": 0,
			"iContactRandReligionPressure": -1,
			"iContactDelayReligionPressure": 50,
			"iContactRandCivicPressure": -1,
			"iContactDelayCivicPressure": 50,
			"iContactRandJoinWar": -1,
			"iContactDelayJoinWar": 20,
			"iContactRandStopTrading": -1,
			"iContactDelayStopTrading": 20,
			"iContactRandGiveHelp": -1,
			"iContactDelayGiveHelp": 50,
			"iContactRandAskForHelp": -1,
			"iContactDelayAskForHelp": 50,
			"iContactRandDemandTribute": -1,
			"iContactDelayDemandTribute": 50,
			"iContactRandTradeTech": -1,
			"iContactDelayTradeTech": 30,
			"iContactRandTradeBonus": -1,
			"iContactDelayTradeBonus": 20,
			"iContactRandPeaceTreaty": -1,
			"iContactDelayPeaceTreaty": -1,
			"iContactRandOpenBorders": 10,
			"iContactDelayOpenBorders": 40,
			"iContactRandDefensivePact": 80,
			"iContactDelayDefensivePact": 20,
			"iContactRandPermanentAlliance": 80,
			"iContactDelayPermanentAlliance": 20,
			"iContactRandTradeMap": 20,
			"iContactDelayTradeMap": 50,
			"iAggregatedContactProbReligionPressure": -999,
			"iAggregatedContactProbCivicPressure": -999,
			"iAggregatedContactProbJoinWar": -999,
			"iAggregatedContactProbStopTrading": -999,
			"iAggregatedContactProbGiveHelp": -999,
			"iAggregatedContactProbAskForHelp": -999,
			"iAggregatedContactProbDemandTribute": -999,
			"iAggregatedContactProbTradeTech": -999,
			"iAggregatedContactProbTradeBonus": -999,
			"iAggregatedContactProbPeaceTreaty": -999,
			"iAggregatedContactProbOpenBorders": -999,
			"iAggregatedContactProbDefensivePact": -999,
			"iAggregatedContactProbPermanentAlliance": -999,
			"iAggregatedContactProbTradeMap": -999,
			"iMemoryAttitudePercentGiveHelp": 100,
			"iMemoryDecayGiveHelp": 150,
			"iMemoryAttitudePercentAcceptDemand": 100,
			"iMemoryDecayAcceptDemand": 30,
			"iMemoryAttitudePercentAcceptedReligion": 100,
			"iMemoryDecayAcceptedReligion": 100,
			"iMemoryAttitudePercentAcceptedCivic": 100,
			"iMemoryDecayAcceptedCivic": 100,
			"iMemoryAttitudePercentAcceptedJoinWar": 100,
			"iMemoryDecayAcceptedJoinWar": 100,
			"iMemoryAttitudePercentAcceptedStopTrading": 50,
			"iMemoryDecayAcceptedStopTrading": 50,
			"iMemoryAttitudePercentTradedTechToUs": -1,
			"iMemoryDecayTradedTechToUs": 25,
			"iMemoryAttitudePercentVotedForUs": 200,
			"iMemoryDecayVotedForUs": 10,
			"iMemoryAttitudePercentEventGoodToUs": 100,
			"iMemoryDecayEventGoodToUs": 50,
			"iMemoryAttitudePercentLiberatedCities": 150,
			"iMemoryDecayLiberatedCities": 150,
			"iMemoryAttitudePercentIndependence": 100,
			"iMemoryDecayIndependence": 30,
			"iAggregatedPositiveMemoryGiveHelpAffection": -999,
			"iAggregatedPositiveMemoryAcceptDemandAffection": -999,
			"iAggregatedPositiveMemoryAcceptedReligionAffection": -999,
			"iAggregatedPositiveMemoryAcceptedCivicAffection": -999,
			"iAggregatedPositiveMemoryAcceptedJoinWarAffection": -999,
			"iAggregatedPositiveMemoryAcceptedStopTradingAffection": -999,
			"iAggregatedPositiveMemoryTradedTechToUsAffection": -999,
			"iAggregatedPositiveMemoryVotedForUsAffection": -999,
			"iAggregatedPositiveMemoryEventGoodToUsAffection": -999,
			"iAggregatedPositiveMemoryLiberatedCitiesAffection": -999,
			"iAggregatedPositiveMemoryIndependenceAffection": -999,
			"iAggregatedPositiveMemoryGiveHelpResentment": -999,
			"iAggregatedPositiveMemoryAcceptDemandResentment": -999,
			"iAggregatedPositiveMemoryAcceptedReligionResentment": -999,
			"iAggregatedPositiveMemoryAcceptedCivicResentment": -999,
			"iAggregatedPositiveMemoryAcceptedJoinWarResentment": -999,
			"iAggregatedPositiveMemoryAcceptedStopTradingResentment": -999,
			"iAggregatedPositiveMemoryTradedTechToUsResentment": -999,
			"iAggregatedPositiveMemoryVotedForUsResentment": -999,
			"iAggregatedPositiveMemoryEventGoodToUsResentment": -999,
			"iAggregatedPositiveMemoryLiberatedCitiesResentment": -999,
			"iAggregatedPositiveMemoryIndependenceResentment": -999,
			"iMemoryAttitudePercentDeclaredWar": -300,
			"iMemoryDecayDeclaredWar": 150,
			"iMemoryAttitudePercentDeclaredWarOnFriend": -100,
			"iMemoryDecayDeclaredWarOnFriend": 120,
			"iMemoryAttitudePercentHiredWarAlly": -200,
			"iMemoryDecayHiredWarAlly": 75,
			"iMemoryAttitudePercentNukedUs": -200,
			"iMemoryDecayNukedUs": 120,
			"iMemoryAttitudePercentNukedFriend": -100,
			"iMemoryDecayNukedFriend": 80,
			"iMemoryAttitudePercentRazedCity": -250,
			"iMemoryDecayRazedCity": 75,
			"iMemoryAttitudePercentRazedHolyCity": -200,
			"iMemoryDecayRazedHolyCity": 150,
			"iMemoryAttitudePercentSpyCaught": -100,
			"iMemoryDecaySpyCaught": 40,
			"iMemoryAttitudePercentRefusedHelp": -100,
			"iMemoryDecayRefusedHelp": 100,
			"iMemoryAttitudePercentRejectedDemand": -100,
			"iMemoryDecayRejectedDemand": 90,
			"iMemoryAttitudePercentDeniedReligion": -100,
			"iMemoryDecayDeniedReligion": 50,
			"iMemoryAttitudePercentDeniedCivic": -100,
			"iMemoryDecayDeniedCivic": 50,
			"iMemoryAttitudePercentDeniedJoinWar": -100,
			"iMemoryDecayDeniedJoinWar": 100,
			"iMemoryAttitudePercentDeniedStopTrading": -100,
			"iMemoryDecayDeniedStopTrading": 50,
			"iMemoryAttitudePercentStoppedTrading": -100,
			"iMemoryDecayStoppedTrading": 60,
			"iMemoryAttitudePercentStoppedTradingRecent": 0,
			"iMemoryDecayStoppedTradingRecent": 18,
			"iMemoryAttitudePercentHiredTradeEmbargo": -100,
			"iMemoryDecayHiredTradeEmbargo": 60,
			"iMemoryAttitudePercentMadeDemand": -100,
			"iMemoryDecayMadeDemand": 30,
			"iMemoryAttitudePercentCancelledVassalAgreement": 0,
			"iMemoryDecayCancelledVassalAgreement": 10,
			"iMemoryAttitudePercentMadeDemandRecent": 0,
			"iMemoryDecayMadeDemandRecent": 20,
			"iMemoryAttitudePercentCancelledOpenBorders": 0,
			"iMemoryDecayCancelledOpenBorders": 10,
			"iMemoryAttitudePercentCancelledDefensivePact": 0,
			"iMemoryDecayCancelledDefensivePact": 10,
			"iMemoryAttitudePercentReceivedTechFromAny": 0,
			"iMemoryDecayReceivedTechFromAny": 20,
			"iMemoryAttitudePercentVotedAgainstUs": -200,
			"iMemoryDecayVotedAgainstUs": 10,
			"iMemoryAttitudePercentEventBadToUs": -100,
			"iMemoryDecayEventBadToUs": 50,
			"iMemoryAttitudePercentDeclaredWarRecent": 0,
			"iMemoryDecayDeclaredWarRecent": 11,
			"iAggregatedNegativeMemoryDeclaredWarAffection": -999,
			"iAggregatedNegativeMemoryDeclaredWarOnFriendAffection": -999,
			"iAggregatedNegativeMemoryHiredWarAllyAffection": -999,
			"iAggregatedNegativeMemoryNukedUsAffection": -999,
			"iAggregatedNegativeMemoryNukedFriendAffection": -999,
			"iAggregatedNegativeMemoryRazedCityAffection": -999,
			"iAggregatedNegativeMemoryRazedHolyCityAffection": -999,
			"iAggregatedNegativeMemorySpyCaughtAffection": -999,
			"iAggregatedNegativeMemoryRefusedHelpAffection": -999,
			"iAggregatedNegativeMemoryRejectedDemandAffection": -999,
			"iAggregatedNegativeMemoryDeniedReligionAffection": -999,
			"iAggregatedNegativeMemoryDeniedCivicAffection": -999,
			"iAggregatedNegativeMemoryDeniedJoinWarAffection": -999,
			"iAggregatedNegativeMemoryDeniedStopTradingAffection": -999,
			"iAggregatedNegativeMemoryStoppedTradingAffection": -999,
			"iAggregatedNegativeMemoryStoppedTradingRecentAffection": -999,
			"iAggregatedNegativeMemoryHiredTradeEmbargoAffection": -999,
			"iAggregatedNegativeMemoryMadeDemandAffection": -999,
			"iAggregatedNegativeMemoryCancelledVassalAgreementAffection": -999,
			"iAggregatedNegativeMemoryMadeDemandRecentAffection": -999,
			"iAggregatedNegativeMemoryCancelledOpenBordersAffection": -999,
			"iAggregatedNegativeMemoryCancelledDefensivePactAffection": -999,
			"iAggregatedNegativeMemoryReceivedTechFromAnyAffection": -999,
			"iAggregatedNegativeMemoryVotedAgainstUsAffection": -999,
			"iAggregatedNegativeMemoryEventBadToUsAffection": -999,
			"iAggregatedNegativeMemoryDeclaredWarRecentAffection": -999,
			"iAggregatedNegativeMemoryDeclaredWarResentment": -999,
			"iAggregatedNegativeMemoryDeclaredWarOnFriendResentment": -999,
			"iAggregatedNegativeMemoryHiredWarAllyResentment": -999,
			"iAggregatedNegativeMemoryNukedUsResentment": -999,
			"iAggregatedNegativeMemoryNukedFriendResentment": -999,
			"iAggregatedNegativeMemoryRazedCityResentment": -999,
			"iAggregatedNegativeMemoryRazedHolyCityResentment": -999,
			"iAggregatedNegativeMemorySpyCaughtResentment": -999,
			"iAggregatedNegativeMemoryRefusedHelpResentment": -999,
			"iAggregatedNegativeMemoryRejectedDemandResentment": -999,
			"iAggregatedNegativeMemoryDeniedReligionResentment": -999,
			"iAggregatedNegativeMemoryDeniedCivicResentment": -999,
			"iAggregatedNegativeMemoryDeniedJoinWarResentment": -999,
			"iAggregatedNegativeMemoryDeniedStopTradingResentment": -999,
			"iAggregatedNegativeMemoryStoppedTradingResentment": -999,
			"iAggregatedNegativeMemoryStoppedTradingRecentResentment": -999,
			"iAggregatedNegativeMemoryHiredTradeEmbargoResentment": -999,
			"iAggregatedNegativeMemoryMadeDemandResentment": -999,
			"iAggregatedNegativeMemoryCancelledVassalAgreementResentment": -999,
			"iAggregatedNegativeMemoryMadeDemandRecentResentment": -999,
			"iAggregatedNegativeMemoryCancelledOpenBordersResentment": -999,
			"iAggregatedNegativeMemoryCancelledDefensivePactResentment": -999,
			"iAggregatedNegativeMemoryReceivedTechFromAnyResentment": -999,
			"iAggregatedNegativeMemoryVotedAgainstUsResentment": -999,
			"iAggregatedNegativeMemoryEventBadToUsResentment": -999,
			"iAggregatedNegativeMemoryDeclaredWarRecentResentment": -999
		},
		"LEADER_DEFAULTS": {
			"Type": "LEADER_DEFAULTS",
			"Description": "",
			"Civilopedia": "",
			"ArtDefineTag": "",
			"getWonderConstructRand": "0",
			"getBaseAttitude": "0",
			"getBasePeaceWeight": "0",
			"getPeaceWeightRand": "3",
			"getWarmongerRespect": "0",
			"getEspionageWeight": "0",
			"getRefuseToTalkWarThreshold": "0",
			"getNoTechTradeThreshold": "0",
			"getTechTradeKnownPercent": "0",
			"getMaxGoldTradePercent": "0",
			"getMaxGoldPerTurnTradePercent": "10",
			"getCultureVictoryWeight": "30",
			"getSpaceVictoryWeight": "30",
			"getConquestVictoryWeight": "30",
			"getDominationVictoryWeight": "30",
			"getDiplomacyVictoryWeight": "30",
			"getMaxWarRand": "0",
			"getMaxWarNearbyPowerRatio": "0",
			"getMaxWarDistantPowerRatio": "0",
			"getMaxWarMinAdjacentLandPercent": "0",
			"getLimitedWarRand": "0",
			"getLimitedWarPowerRatio": "0",
			"getDogpileWarRand": "0",
			"getMakePeaceRand": "0",
			"getDeclareWarTradeRand": "40",
			"getDemandRebukedSneakProb": "0",
			"getDemandRebukedWarProb": "0",
			"getRazeCityProb": "0",
			"getBuildUnitProb": "10",
			"getBaseAttackOddsChange": "0",
			"getAttackOddsChangeRand": "8",
			"getWorseRankDifferenceAttitudeChange": "0",
			"getBetterRankDifferenceAttitudeChange": "0",
			"getCloseBordersAttitudeChange": "0",
			"getLostWarAttitudeChange": "-1",
			"getAtWarAttitudeDivisor": "-5",
			"getAtWarAttitudeChangeLimit": "5",
			"getAtPeaceAttitudeDivisor": "60",
			"getAtPeaceAttitudeChangeLimit": "1",
			"getSameReligionAttitudeChange": "1",
			"getSameReligionAttitudeDivisor": "10",
			"getSameReligionAttitudeChangeLimit": "0",
			"getDifferentReligionAttitudeChange": "-1",
			"getDifferentReligionAttitudeDivisor": "-15",
			"getDifferentReligionAttitudeChangeLimit": "0",
			"getBonusTradeAttitudeDivisor": "50",
			"getBonusTradeAttitudeChangeLimit": "2",
			"getOpenBordersAttitudeDivisor": "25",
			"getOpenBordersAttitudeChangeLimit": "2",
			"getDefensivePactAttitudeDivisor": "12",
			"getDefensivePactAttitudeChangeLimit": "2",
			"getShareWarAttitudeChange": "1",
			"getShareWarAttitudeDivisor": "8",
			"getShareWarAttitudeChangeLimit": "0",
			"getFavoriteCivicAttitudeChange": "1",
			"getFavoriteCivicAttitudeDivisor": "10",
			"getFavoriteCivicAttitudeChangeLimit": "0",
			"getDemandTributeAttitudeThreshold": 2,
			"getNoGiveHelpAttitudeThreshold": 2,
			"getTechRefuseAttitudeThreshold": -1,
			"getCityRefuseAttitudeThreshold": 2,
			"getNativeCityRefuseAttitudeThreshold": 3,
			"getStrategicBonusRefuseAttitudeThreshold": -1,
			"getHappinessBonusRefuseAttitudeThreshold": -1,
			"getHealthBonusRefuseAttitudeThreshold": -1,
			"getMapRefuseAttitudeThreshold": -1,
			"getDeclareWarRefuseAttitudeThreshold": -1,
			"getDeclareWarThemRefuseAttitudeThreshold": -1,
			"getStopTradingRefuseAttitudeThreshold": -1,
			"getStopTradingThemRefuseAttitudeThreshold": -1,
			"getAdoptCivicRefuseAttitudeThreshold": -1,
			"getConvertReligionRefuseAttitudeThreshold": -1,
			"getOpenBordersRefuseAttitudeThreshold": -1,
			"getDefensivePactRefuseAttitudeThreshold": 3,
			"getPermanentAllianceRefuseAttitudeThreshold": 3,
			"getVassalRefuseAttitudeThreshold": -1,
			"getVassalPowerModifier": "0",
			"getFreedomAppreciation": "10",
			"FavoriteCivic": "NONE",
			"FavoriteReligion": "NONE",
			"Traits": "",
			"iNoWarAttitudeProbFurious": 0,
			"iNoWarAttitudeProbAnnoyed": 0,
			"iNoWarAttitudeProbCautious": 0,
			"iNoWarAttitudeProbPleased": 0,
			"iNoWarAttitudeProbFriendly": 100,
			"iLoveOfPeace": 0,
			"UnitAIWeightModifiers": "",
			"ImprovementWeightModifiers": "",
			"DiplomacyIntroMusicPeace": [
				{
					"EraType": "ERA_ANCIENT"
				},
				{
					"EraType": "ERA_CLASSICAL"
				},
				{
					"EraType": "ERA_MEDIEVAL"
				},
				{
					"EraType": "ERA_RENAISSANCE"
				},
				{
					"EraType": "ERA_INDUSTRIAL"
				},
				{
					"EraType": "ERA_MODERN"
				},
				{
					"EraType": "ERA_FUTURE"
				}
			],
			"DiplomacyMusicPeace": [
				{
					"EraType": "ERA_ANCIENT"
				},
				{
					"EraType": "ERA_CLASSICAL"
				},
				{
					"EraType": "ERA_MEDIEVAL"
				},
				{
					"EraType": "ERA_RENAISSANCE"
				},
				{
					"EraType": "ERA_INDUSTRIAL"
				},
				{
					"EraType": "ERA_MODERN"
				},
				{
					"EraType": "ERA_FUTURE"
				}
			],
			"DiplomacyIntroMusicWar": [
				{
					"EraType": "ERA_ANCIENT"
				},
				{
					"EraType": "ERA_CLASSICAL"
				},
				{
					"EraType": "ERA_MEDIEVAL"
				},
				{
					"EraType": "ERA_RENAISSANCE"
				},
				{
					"EraType": "ERA_INDUSTRIAL"
				},
				{
					"EraType": "ERA_MODERN"
				},
				{
					"EraType": "ERA_FUTURE"
				}
			],
			"DiplomacyMusicWar": [
				{
					"EraType": "ERA_ANCIENT",
					"DiploScriptId": "AS2D_DIPLO_WARDRUMS_EARLY"
				},
				{
					"EraType": "ERA_CLASSICAL",
					"DiploScriptId": "AS2D_DIPLO_WARDRUMS_EARLY"
				},
				{
					"EraType": "ERA_MEDIEVAL",
					"DiploScriptId": "AS2D_DIPLO_WARDRUMS_MIDDLE"
				},
				{
					"EraType": "ERA_RENAISSANCE",
					"DiploScriptId": "AS2D_DIPLO_WARDRUMS_MIDDLE"
				},
				{
					"EraType": "ERA_INDUSTRIAL",
					"DiploScriptId": "AS2D_DIPLO_WARDRUMS_LATE"
				},
				{
					"EraType": "ERA_MODERN",
					"DiploScriptId": "AS2D_DIPLO_WARDRUMS_LATE"
				},
				{
					"EraType": "ERA_FUTURE",
					"DiploScriptId": "AS2D_DIPLO_WARDRUMS_LATE"
				}
			],
			"iFlavorMilitary": 0,
			"iFlavorReligion": 0,
			"iFlavorProduction": 0,
			"iFlavorGold": 0,
			"iFlavorScience": 0,
			"iFlavorCulture": 0,
			"iFlavorGrowth": 0,
			"iFlavorEspionage": 0,
			"iContactRandReligionPressure": -1,
			"iContactDelayReligionPressure": 50,
			"iContactRandCivicPressure": -1,
			"iContactDelayCivicPressure": 50,
			"iContactRandJoinWar": -1,
			"iContactDelayJoinWar": 20,
			"iContactRandStopTrading": -1,
			"iContactDelayStopTrading": 20,
			"iContactRandGiveHelp": -1,
			"iContactDelayGiveHelp": 50,
			"iContactRandAskForHelp": -1,
			"iContactDelayAskForHelp": 50,
			"iContactRandDemandTribute": -1,
			"iContactDelayDemandTribute": 50,
			"iContactRandTradeTech": -1,
			"iContactDelayTradeTech": 30,
			"iContactRandTradeBonus": -1,
			"iContactDelayTradeBonus": 20,
			"iContactRandPeaceTreaty": -1,
			"iContactDelayPeaceTreaty": -1,
			"iContactRandOpenBorders": 10,
			"iContactDelayOpenBorders": 40,
			"iContactRandDefensivePact": 80,
			"iContactDelayDefensivePact": 20,
			"iContactRandPermanentAlliance": 80,
			"iContactDelayPermanentAlliance": 20,
			"iContactRandTradeMap": 20,
			"iContactDelayTradeMap": 50,
			"iAggregatedContactProbReligionPressure": -999,
			"iAggregatedContactProbCivicPressure": -999,
			"iAggregatedContactProbJoinWar": -999,
			"iAggregatedContactProbStopTrading": -999,
			"iAggregatedContactProbGiveHelp": -999,
			"iAggregatedContactProbAskForHelp": -999,
			"iAggregatedContactProbDemandTribute": -999,
			"iAggregatedContactProbTradeTech": -999,
			"iAggregatedContactProbTradeBonus": -999,
			"iAggregatedContactProbPeaceTreaty": -999,
			"iAggregatedContactProbOpenBorders": -999,
			"iAggregatedContactProbDefensivePact": -999,
			"iAggregatedContactProbPermanentAlliance": -999,
			"iAggregatedContactProbTradeMap": -999,
			"iMemoryAttitudePercentGiveHelp": 100,
			"iMemoryDecayGiveHelp": 150,
			"iMemoryAttitudePercentAcceptDemand": 100,
			"iMemoryDecayAcceptDemand": 30,
			"iMemoryAttitudePercentAcceptedReligion": 100,
			"iMemoryDecayAcceptedReligion": 100,
			"iMemoryAttitudePercentAcceptedCivic": 100,
			"iMemoryDecayAcceptedCivic": 100,
			"iMemoryAttitudePercentAcceptedJoinWar": 100,
			"iMemoryDecayAcceptedJoinWar": 100,
			"iMemoryAttitudePercentAcceptedStopTrading": 50,
			"iMemoryDecayAcceptedStopTrading": 50,
			"iMemoryAttitudePercentTradedTechToUs": -1,
			"iMemoryDecayTradedTechToUs": 25,
			"iMemoryAttitudePercentVotedForUs": 200,
			"iMemoryDecayVotedForUs": 10,
			"iMemoryAttitudePercentEventGoodToUs": 100,
			"iMemoryDecayEventGoodToUs": 50,
			"iMemoryAttitudePercentLiberatedCities": 150,
			"iMemoryDecayLiberatedCities": 150,
			"iMemoryAttitudePercentIndependence": 100,
			"iMemoryDecayIndependence": 30,
			"iAggregatedPositiveMemoryGiveHelpAffection": -999,
			"iAggregatedPositiveMemoryAcceptDemandAffection": -999,
			"iAggregatedPositiveMemoryAcceptedReligionAffection": -999,
			"iAggregatedPositiveMemoryAcceptedCivicAffection": -999,
			"iAggregatedPositiveMemoryAcceptedJoinWarAffection": -999,
			"iAggregatedPositiveMemoryAcceptedStopTradingAffection": -999,
			"iAggregatedPositiveMemoryTradedTechToUsAffection": -999,
			"iAggregatedPositiveMemoryVotedForUsAffection": -999,
			"iAggregatedPositiveMemoryEventGoodToUsAffection": -999,
			"iAggregatedPositiveMemoryLiberatedCitiesAffection": -999,
			"iAggregatedPositiveMemoryIndependenceAffection": -999,
			"iAggregatedPositiveMemoryGiveHelpResentment": -999,
			"iAggregatedPositiveMemoryAcceptDemandResentment": -999,
			"iAggregatedPositiveMemoryAcceptedReligionResentment": -999,
			"iAggregatedPositiveMemoryAcceptedCivicResentment": -999,
			"iAggregatedPositiveMemoryAcceptedJoinWarResentment": -999,
			"iAggregatedPositiveMemoryAcceptedStopTradingResentment": -999,
			"iAggregatedPositiveMemoryTradedTechToUsResentment": -999,
			"iAggregatedPositiveMemoryVotedForUsResentment": -999,
			"iAggregatedPositiveMemoryEventGoodToUsResentment": -999,
			"iAggregatedPositiveMemoryLiberatedCitiesResentment": -999,
			"iAggregatedPositiveMemoryIndependenceResentment": -999,
			"iMemoryAttitudePercentDeclaredWar": -300,
			"iMemoryDecayDeclaredWar": 150,
			"iMemoryAttitudePercentDeclaredWarOnFriend": -100,
			"iMemoryDecayDeclaredWarOnFriend": 120,
			"iMemoryAttitudePercentHiredWarAlly": -200,
			"iMemoryDecayHiredWarAlly": 75,
			"iMemoryAttitudePercentNukedUs": -200,
			"iMemoryDecayNukedUs": 120,
			"iMemoryAttitudePercentNukedFriend": -100,
			"iMemoryDecayNukedFriend": 80,
			"iMemoryAttitudePercentRazedCity": -250,
			"iMemoryDecayRazedCity": 75,
			"iMemoryAttitudePercentRazedHolyCity": -200,
			"iMemoryDecayRazedHolyCity": 150,
			"iMemoryAttitudePercentSpyCaught": -100,
			"iMemoryDecaySpyCaught": 40,
			"iMemoryAttitudePercentRefusedHelp": -100,
			"iMemoryDecayRefusedHelp": 100,
			"iMemoryAttitudePercentRejectedDemand": -100,
			"iMemoryDecayRejectedDemand": 90,
			"iMemoryAttitudePercentDeniedReligion": -100,
			"iMemoryDecayDeniedReligion": 50,
			"iMemoryAttitudePercentDeniedCivic": -100,
			"iMemoryDecayDeniedCivic": 50,
			"iMemoryAttitudePercentDeniedJoinWar": -100,
			"iMemoryDecayDeniedJoinWar": 100,
			"iMemoryAttitudePercentDeniedStopTrading": -100,
			"iMemoryDecayDeniedStopTrading": 50,
			"iMemoryAttitudePercentStoppedTrading": -100,
			"iMemoryDecayStoppedTrading": 60,
			"iMemoryAttitudePercentStoppedTradingRecent": 0,
			"iMemoryDecayStoppedTradingRecent": 18,
			"iMemoryAttitudePercentHiredTradeEmbargo": -100,
			"iMemoryDecayHiredTradeEmbargo": 60,
			"iMemoryAttitudePercentMadeDemand": -100,
			"iMemoryDecayMadeDemand": 30,
			"iMemoryAttitudePercentCancelledVassalAgreement": 0,
			"iMemoryDecayCancelledVassalAgreement": 10,
			"iMemoryAttitudePercentMadeDemandRecent": 0,
			"iMemoryDecayMadeDemandRecent": 20,
			"iMemoryAttitudePercentCancelledOpenBorders": 0,
			"iMemoryDecayCancelledOpenBorders": 10,
			"iMemoryAttitudePercentCancelledDefensivePact": 0,
			"iMemoryDecayCancelledDefensivePact": 10,
			"iMemoryAttitudePercentReceivedTechFromAny": 0,
			"iMemoryDecayReceivedTechFromAny": 20,
			"iMemoryAttitudePercentVotedAgainstUs": -200,
			"iMemoryDecayVotedAgainstUs": 10,
			"iMemoryAttitudePercentEventBadToUs": -100,
			"iMemoryDecayEventBadToUs": 50,
			"iMemoryAttitudePercentDeclaredWarRecent": 0,
			"iMemoryDecayDeclaredWarRecent": 11,
			"iAggregatedNegativeMemoryDeclaredWarAffection": -999,
			"iAggregatedNegativeMemoryDeclaredWarOnFriendAffection": -999,
			"iAggregatedNegativeMemoryHiredWarAllyAffection": -999,
			"iAggregatedNegativeMemoryNukedUsAffection": -999,
			"iAggregatedNegativeMemoryNukedFriendAffection": -999,
			"iAggregatedNegativeMemoryRazedCityAffection": -999,
			"iAggregatedNegativeMemoryRazedHolyCityAffection": -999,
			"iAggregatedNegativeMemorySpyCaughtAffection": -999,
			"iAggregatedNegativeMemoryRefusedHelpAffection": -999,
			"iAggregatedNegativeMemoryRejectedDemandAffection": -999,
			"iAggregatedNegativeMemoryDeniedReligionAffection": -999,
			"iAggregatedNegativeMemoryDeniedCivicAffection": -999,
			"iAggregatedNegativeMemoryDeniedJoinWarAffection": -999,
			"iAggregatedNegativeMemoryDeniedStopTradingAffection": -999,
			"iAggregatedNegativeMemoryStoppedTradingAffection": -999,
			"iAggregatedNegativeMemoryStoppedTradingRecentAffection": -999,
			"iAggregatedNegativeMemoryHiredTradeEmbargoAffection": -999,
			"iAggregatedNegativeMemoryMadeDemandAffection": -999,
			"iAggregatedNegativeMemoryCancelledVassalAgreementAffection": -999,
			"iAggregatedNegativeMemoryMadeDemandRecentAffection": -999,
			"iAggregatedNegativeMemoryCancelledOpenBordersAffection": -999,
			"iAggregatedNegativeMemoryCancelledDefensivePactAffection": -999,
			"iAggregatedNegativeMemoryReceivedTechFromAnyAffection": -999,
			"iAggregatedNegativeMemoryVotedAgainstUsAffection": -999,
			"iAggregatedNegativeMemoryEventBadToUsAffection": -999,
			"iAggregatedNegativeMemoryDeclaredWarRecentAffection": -999,
			"iAggregatedNegativeMemoryDeclaredWarResentment": -999,
			"iAggregatedNegativeMemoryDeclaredWarOnFriendResentment": -999,
			"iAggregatedNegativeMemoryHiredWarAllyResentment": -999,
			"iAggregatedNegativeMemoryNukedUsResentment": -999,
			"iAggregatedNegativeMemoryNukedFriendResentment": -999,
			"iAggregatedNegativeMemoryRazedCityResentment": -999,
			"iAggregatedNegativeMemoryRazedHolyCityResentment": -999,
			"iAggregatedNegativeMemorySpyCaughtResentment": -999,
			"iAggregatedNegativeMemoryRefusedHelpResentment": -999,
			"iAggregatedNegativeMemoryRejectedDemandResentment": -999,
			"iAggregatedNegativeMemoryDeniedReligionResentment": -999,
			"iAggregatedNegativeMemoryDeniedCivicResentment": -999,
			"iAggregatedNegativeMemoryDeniedJoinWarResentment": -999,
			"iAggregatedNegativeMemoryDeniedStopTradingResentment": -999,
			"iAggregatedNegativeMemoryStoppedTradingResentment": -999,
			"iAggregatedNegativeMemoryStoppedTradingRecentResentment": -999,
			"iAggregatedNegativeMemoryHiredTradeEmbargoResentment": -999,
			"iAggregatedNegativeMemoryMadeDemandResentment": -999,
			"iAggregatedNegativeMemoryCancelledVassalAgreementResentment": -999,
			"iAggregatedNegativeMemoryMadeDemandRecentResentment": -999,
			"iAggregatedNegativeMemoryCancelledOpenBordersResentment": -999,
			"iAggregatedNegativeMemoryCancelledDefensivePactResentment": -999,
			"iAggregatedNegativeMemoryReceivedTechFromAnyResentment": -999,
			"iAggregatedNegativeMemoryVotedAgainstUsResentment": -999,
			"iAggregatedNegativeMemoryEventBadToUsResentment": -999,
			"iAggregatedNegativeMemoryDeclaredWarRecentResentment": -999
		},
		"LEADER_ALEXANDER": {
			"Type": "LEADER_ALEXANDER",
			"Description": "TXT_KEY_LEADER_ALEXANDER",
			"Civilopedia": "TXT_KEY_LEADER_ALEXANDER_PEDIA",
			"ArtDefineTag": "ART_DEF_LEADER_ALEXANDER",
			"getWonderConstructRand": "20",
			"getBaseAttitude": "0",
			"getBasePeaceWeight": "0",
			"getWarmongerRespect": "2",
			"getEspionageWeight": "100",
			"getRefuseToTalkWarThreshold": "8",
			"getNoTechTradeThreshold": "5",
			"getTechTradeKnownPercent": "30",
			"getMaxGoldTradePercent": "5",
			"getCultureVictoryWeight": "25",
			"getSpaceVictoryWeight": "25",
			"getConquestVictoryWeight": "35",
			"getDominationVictoryWeight": "65",
			"getDiplomacyVictoryWeight": "0",
			"getMaxWarRand": "50",
			"getMaxWarNearbyPowerRatio": "90",
			"getMaxWarDistantPowerRatio": "70",
			"getMaxWarMinAdjacentLandPercent": "0",
			"getLimitedWarRand": "40",
			"getLimitedWarPowerRatio": "130",
			"getDogpileWarRand": "50",
			"getMakePeaceRand": "40",
			"getDemandRebukedSneakProb": "40",
			"getDemandRebukedWarProb": "25",
			"getRazeCityProb": "0",
			"getBuildUnitProb": "50",
			"getBaseAttackOddsChange": "4",
			"getWorseRankDifferenceAttitudeChange": "-2",
			"getBetterRankDifferenceAttitudeChange": "0",
			"getCloseBordersAttitudeChange": "-4",
			"getSameReligionAttitudeChangeLimit": "4",
			"getDifferentReligionAttitudeChangeLimit": "-1",
			"getShareWarAttitudeChangeLimit": "4",
			"getFavoriteCivicAttitudeChangeLimit": "2",
			"getTechRefuseAttitudeThreshold": 1,
			"getCityRefuseAttitudeThreshold": 2,
			"getNativeCityRefuseAttitudeThreshold": 3,
			"getStrategicBonusRefuseAttitudeThreshold": 2,
			"getHappinessBonusRefuseAttitudeThreshold": 1,
			"getHealthBonusRefuseAttitudeThreshold": 1,
			"getMapRefuseAttitudeThreshold": 3,
			"getDeclareWarRefuseAttitudeThreshold": 1,
			"getDeclareWarThemRefuseAttitudeThreshold": 3,
			"getStopTradingRefuseAttitudeThreshold": 2,
			"getStopTradingThemRefuseAttitudeThreshold": 2,
			"getAdoptCivicRefuseAttitudeThreshold": 3,
			"getConvertReligionRefuseAttitudeThreshold": 2,
			"getOpenBordersRefuseAttitudeThreshold": 1,
			"getVassalRefuseAttitudeThreshold": 3,
			"getVassalPowerModifier": "20",
			"FavoriteCivic": "CIVIC_VASSALAGE",
			"FavoriteReligion": "RELIGION_PAGANISM",
			"Traits": [
				{
					"TraitType": "TRAIT_PHILOSOPHICAL",
					"bTrait": "1"
				},
				{
					"TraitType": "TRAIT_AGGRESSIVE",
					"bTrait": "1"
				}
			],
			"iFlavorMilitary": 5,
			"iFlavorGrowth": 2,
			"iNoWarAttitudeProbCautious": 20,
			"iNoWarAttitudeProbPleased": 80,
			"iNoWarAttitudeProbFriendly": 80,
			"UnitAIWeightModifiers": [
				{
					"UnitAIType": "UNITAI_SETTLE",
					"iWeightModifier": "25"
				},
				{
					"UnitAIType": "UNITAI_COLLATERAL",
					"iWeightModifier": "25"
				}
			],
			"ImprovementWeightModifiers": [
				{
					"ImprovementType": "IMPROVEMENT_MINE",
					"iWeightModifier": "30"
				}
			],
			"DiplomacyIntroMusicPeace": "",
			"DiplomacyMusicPeace": [
				{
					"EraType": "ERA_ANCIENT",
					"DiploScriptId": "AS2D_DIPLO_ALEXANDER_EARLY"
				},
				{
					"EraType": "ERA_CLASSICAL",
					"DiploScriptId": "AS2D_DIPLO_ALEXANDER_EARLY"
				},
				{
					"EraType": "ERA_MEDIEVAL",
					"DiploScriptId": "AS2D_DIPLO_ALEXANDER_EARLY"
				},
				{
					"EraType": "ERA_RENAISSANCE",
					"DiploScriptId": "AS2D_DIPLO_ALEXANDER_EARLY"
				},
				{
					"EraType": "ERA_INDUSTRIAL",
					"DiploScriptId": "AS2D_DIPLO_ALEXANDER_EARLY"
				},
				{
					"EraType": "ERA_MODERN",
					"DiploScriptId": "AS2D_DIPLO_ALEXANDER_EARLY"
				},
				{
					"EraType": "ERA_FUTURE",
					"DiploScriptId": "AS2D_DIPLO_ALEXANDER_EARLY"
				}
			],
			"DiplomacyIntroMusicWar": "",
			"DiplomacyMusicWar": "",
			"getPeaceWeightRand": "3",
			"getMaxGoldPerTurnTradePercent": "10",
			"getDeclareWarTradeRand": "40",
			"getAttackOddsChangeRand": "8",
			"getLostWarAttitudeChange": "-1",
			"getAtWarAttitudeDivisor": "-5",
			"getAtWarAttitudeChangeLimit": "5",
			"getAtPeaceAttitudeDivisor": "60",
			"getAtPeaceAttitudeChangeLimit": "1",
			"getSameReligionAttitudeChange": "1",
			"getSameReligionAttitudeDivisor": "10",
			"getDifferentReligionAttitudeChange": "-1",
			"getDifferentReligionAttitudeDivisor": "-15",
			"getBonusTradeAttitudeDivisor": "50",
			"getBonusTradeAttitudeChangeLimit": "2",
			"getOpenBordersAttitudeDivisor": "25",
			"getOpenBordersAttitudeChangeLimit": "2",
			"getDefensivePactAttitudeDivisor": "12",
			"getDefensivePactAttitudeChangeLimit": "2",
			"getShareWarAttitudeChange": "1",
			"getShareWarAttitudeDivisor": "8",
			"getFavoriteCivicAttitudeChange": "1",
			"getFavoriteCivicAttitudeDivisor": "10",
			"getDemandTributeAttitudeThreshold": 2,
			"getNoGiveHelpAttitudeThreshold": 2,
			"getDefensivePactRefuseAttitudeThreshold": 3,
			"getPermanentAllianceRefuseAttitudeThreshold": 3,
			"getFreedomAppreciation": "10",
			"iNoWarAttitudeProbFurious": 0,
			"iNoWarAttitudeProbAnnoyed": 0,
			"iLoveOfPeace": 0,
			"iFlavorReligion": 0,
			"iFlavorProduction": 0,
			"iFlavorGold": 0,
			"iFlavorScience": 0,
			"iFlavorCulture": 0,
			"iFlavorEspionage": 0,
			"iContactRandReligionPressure": 250,
			"iContactDelayReligionPressure": 50,
			"iContactRandCivicPressure": 1000,
			"iContactDelayCivicPressure": 50,
			"iContactRandJoinWar": 20,
			"iContactDelayJoinWar": 20,
			"iContactRandStopTrading": 50,
			"iContactDelayStopTrading": 20,
			"iContactRandGiveHelp": 500,
			"iContactDelayGiveHelp": 50,
			"iContactRandAskForHelp": 250,
			"iContactDelayAskForHelp": 50,
			"iContactRandDemandTribute": 250,
			"iContactDelayDemandTribute": 50,
			"iContactRandTradeTech": 5,
			"iContactDelayTradeTech": 30,
			"iContactRandTradeBonus": 5,
			"iContactDelayTradeBonus": 20,
			"iContactRandPeaceTreaty": 20,
			"iContactDelayPeaceTreaty": 15,
			"iContactRandOpenBorders": 10,
			"iContactDelayOpenBorders": 40,
			"iContactRandDefensivePact": 80,
			"iContactDelayDefensivePact": 20,
			"iContactRandPermanentAlliance": 80,
			"iContactDelayPermanentAlliance": 20,
			"iContactRandTradeMap": 20,
			"iContactDelayTradeMap": 50,
			"iAggregatedContactProbReligionPressure": 79,
			"iAggregatedContactProbCivicPressure": 12,
			"iAggregatedContactProbJoinWar": 0,
			"iAggregatedContactProbStopTrading": 50,
			"iAggregatedContactProbGiveHelp": 57,
			"iAggregatedContactProbAskForHelp": 78,
			"iAggregatedContactProbDemandTribute": 80,
			"iAggregatedContactProbTradeTech": 79,
			"iAggregatedContactProbTradeBonus": 72,
			"iAggregatedContactProbPeaceTreaty": 35,
			"iAggregatedContactProbOpenBorders": 50,
			"iAggregatedContactProbDefensivePact": 50,
			"iAggregatedContactProbPermanentAlliance": 50,
			"iAggregatedContactProbTradeMap": 50,
			"iMemoryAttitudePercentGiveHelp": 100,
			"iMemoryDecayGiveHelp": 150,
			"iMemoryAttitudePercentAcceptDemand": 100,
			"iMemoryDecayAcceptDemand": 30,
			"iMemoryAttitudePercentAcceptedReligion": 100,
			"iMemoryDecayAcceptedReligion": 100,
			"iMemoryAttitudePercentAcceptedCivic": 100,
			"iMemoryDecayAcceptedCivic": 100,
			"iMemoryAttitudePercentAcceptedJoinWar": 100,
			"iMemoryDecayAcceptedJoinWar": 100,
			"iMemoryAttitudePercentAcceptedStopTrading": 50,
			"iMemoryDecayAcceptedStopTrading": 50,
			"iMemoryAttitudePercentTradedTechToUs": 10,
			"iMemoryDecayTradedTechToUs": 25,
			"iMemoryAttitudePercentVotedForUs": 200,
			"iMemoryDecayVotedForUs": 10,
			"iMemoryAttitudePercentEventGoodToUs": 100,
			"iMemoryDecayEventGoodToUs": 50,
			"iMemoryAttitudePercentLiberatedCities": 150,
			"iMemoryDecayLiberatedCities": 150,
			"iMemoryAttitudePercentIndependence": 100,
			"iMemoryDecayIndependence": 30,
			"iAggregatedPositiveMemoryGiveHelpAffection": 50,
			"iAggregatedPositiveMemoryAcceptDemandAffection": 50,
			"iAggregatedPositiveMemoryAcceptedReligionAffection": 50,
			"iAggregatedPositiveMemoryAcceptedCivicAffection": 50,
			"iAggregatedPositiveMemoryAcceptedJoinWarAffection": 50,
			"iAggregatedPositiveMemoryAcceptedStopTradingAffection": 50,
			"iAggregatedPositiveMemoryTradedTechToUsAffection": 32,
			"iAggregatedPositiveMemoryVotedForUsAffection": 50,
			"iAggregatedPositiveMemoryEventGoodToUsAffection": 50,
			"iAggregatedPositiveMemoryLiberatedCitiesAffection": 50,
			"iAggregatedPositiveMemoryIndependenceAffection": 50,
			"iAggregatedPositiveMemoryGiveHelpResentment": 50,
			"iAggregatedPositiveMemoryAcceptDemandResentment": 50,
			"iAggregatedPositiveMemoryAcceptedReligionResentment": 50,
			"iAggregatedPositiveMemoryAcceptedCivicResentment": 50,
			"iAggregatedPositiveMemoryAcceptedJoinWarResentment": 50,
			"iAggregatedPositiveMemoryAcceptedStopTradingResentment": 50,
			"iAggregatedPositiveMemoryTradedTechToUsResentment": 50,
			"iAggregatedPositiveMemoryVotedForUsResentment": 50,
			"iAggregatedPositiveMemoryEventGoodToUsResentment": 50,
			"iAggregatedPositiveMemoryLiberatedCitiesResentment": 50,
			"iAggregatedPositiveMemoryIndependenceResentment": 50,
			"iMemoryAttitudePercentDeclaredWar": -300,
			"iMemoryDecayDeclaredWar": 150,
			"iMemoryAttitudePercentDeclaredWarOnFriend": -100,
			"iMemoryDecayDeclaredWarOnFriend": 120,
			"iMemoryAttitudePercentHiredWarAlly": -200,
			"iMemoryDecayHiredWarAlly": 75,
			"iMemoryAttitudePercentNukedUs": -200,
			"iMemoryDecayNukedUs": 120,
			"iMemoryAttitudePercentNukedFriend": -100,
			"iMemoryDecayNukedFriend": 80,
			"iMemoryAttitudePercentRazedCity": -250,
			"iMemoryDecayRazedCity": 75,
			"iMemoryAttitudePercentRazedHolyCity": -200,
			"iMemoryDecayRazedHolyCity": 150,
			"iMemoryAttitudePercentSpyCaught": -100,
			"iMemoryDecaySpyCaught": 40,
			"iMemoryAttitudePercentRefusedHelp": -100,
			"iMemoryDecayRefusedHelp": 100,
			"iMemoryAttitudePercentRejectedDemand": -100,
			"iMemoryDecayRejectedDemand": 90,
			"iMemoryAttitudePercentDeniedReligion": -100,
			"iMemoryDecayDeniedReligion": 50,
			"iMemoryAttitudePercentDeniedCivic": -100,
			"iMemoryDecayDeniedCivic": 50,
			"iMemoryAttitudePercentDeniedJoinWar": -100,
			"iMemoryDecayDeniedJoinWar": 100,
			"iMemoryAttitudePercentDeniedStopTrading": -100,
			"iMemoryDecayDeniedStopTrading": 50,
			"iMemoryAttitudePercentStoppedTrading": -100,
			"iMemoryDecayStoppedTrading": 60,
			"iMemoryAttitudePercentStoppedTradingRecent": 0,
			"iMemoryDecayStoppedTradingRecent": 18,
			"iMemoryAttitudePercentHiredTradeEmbargo": -100,
			"iMemoryDecayHiredTradeEmbargo": 60,
			"iMemoryAttitudePercentMadeDemand": -100,
			"iMemoryDecayMadeDemand": 30,
			"iMemoryAttitudePercentCancelledVassalAgreement": 0,
			"iMemoryDecayCancelledVassalAgreement": 10,
			"iMemoryAttitudePercentMadeDemandRecent": 0,
			"iMemoryDecayMadeDemandRecent": 20,
			"iMemoryAttitudePercentCancelledOpenBorders": 0,
			"iMemoryDecayCancelledOpenBorders": 10,
			"iMemoryAttitudePercentCancelledDefensivePact": 0,
			"iMemoryDecayCancelledDefensivePact": 10,
			"iMemoryAttitudePercentReceivedTechFromAny": 0,
			"iMemoryDecayReceivedTechFromAny": 20,
			"iMemoryAttitudePercentVotedAgainstUs": -200,
			"iMemoryDecayVotedAgainstUs": 10,
			"iMemoryAttitudePercentEventBadToUs": -100,
			"iMemoryDecayEventBadToUs": 50,
			"iMemoryAttitudePercentDeclaredWarRecent": 0,
			"iMemoryDecayDeclaredWarRecent": 11,
			"iAggregatedNegativeMemoryDeclaredWarAffection": 50,
			"iAggregatedNegativeMemoryDeclaredWarOnFriendAffection": 50,
			"iAggregatedNegativeMemoryHiredWarAllyAffection": 50,
			"iAggregatedNegativeMemoryNukedUsAffection": 50,
			"iAggregatedNegativeMemoryNukedFriendAffection": 50,
			"iAggregatedNegativeMemoryRazedCityAffection": 50,
			"iAggregatedNegativeMemoryRazedHolyCityAffection": 50,
			"iAggregatedNegativeMemorySpyCaughtAffection": 50,
			"iAggregatedNegativeMemoryRefusedHelpAffection": 50,
			"iAggregatedNegativeMemoryRejectedDemandAffection": 50,
			"iAggregatedNegativeMemoryDeniedReligionAffection": 50,
			"iAggregatedNegativeMemoryDeniedCivicAffection": 50,
			"iAggregatedNegativeMemoryDeniedJoinWarAffection": 50,
			"iAggregatedNegativeMemoryDeniedStopTradingAffection": 50,
			"iAggregatedNegativeMemoryStoppedTradingAffection": 50,
			"iAggregatedNegativeMemoryStoppedTradingRecentAffection": 50,
			"iAggregatedNegativeMemoryHiredTradeEmbargoAffection": 50,
			"iAggregatedNegativeMemoryMadeDemandAffection": 50,
			"iAggregatedNegativeMemoryCancelledVassalAgreementAffection": 50,
			"iAggregatedNegativeMemoryMadeDemandRecentAffection": 50,
			"iAggregatedNegativeMemoryCancelledOpenBordersAffection": 50,
			"iAggregatedNegativeMemoryCancelledDefensivePactAffection": 50,
			"iAggregatedNegativeMemoryReceivedTechFromAnyAffection": 50,
			"iAggregatedNegativeMemoryVotedAgainstUsAffection": 50,
			"iAggregatedNegativeMemoryEventBadToUsAffection": 50,
			"iAggregatedNegativeMemoryDeclaredWarRecentAffection": 50,
			"iAggregatedNegativeMemoryDeclaredWarResentment": 50,
			"iAggregatedNegativeMemoryDeclaredWarOnFriendResentment": 0,
			"iAggregatedNegativeMemoryHiredWarAllyResentment": 50,
			"iAggregatedNegativeMemoryNukedUsResentment": 50,
			"iAggregatedNegativeMemoryNukedFriendResentment": 0,
			"iAggregatedNegativeMemoryRazedCityResentment": 50,
			"iAggregatedNegativeMemoryRazedHolyCityResentment": 50,
			"iAggregatedNegativeMemorySpyCaughtResentment": 0,
			"iAggregatedNegativeMemoryRefusedHelpResentment": 50,
			"iAggregatedNegativeMemoryRejectedDemandResentment": 50,
			"iAggregatedNegativeMemoryDeniedReligionResentment": 50,
			"iAggregatedNegativeMemoryDeniedCivicResentment": 50,
			"iAggregatedNegativeMemoryDeniedJoinWarResentment": 50,
			"iAggregatedNegativeMemoryDeniedStopTradingResentment": 50,
			"iAggregatedNegativeMemoryStoppedTradingResentment": 100,
			"iAggregatedNegativeMemoryStoppedTradingRecentResentment": 50,
			"iAggregatedNegativeMemoryHiredTradeEmbargoResentment": 50,
			"iAggregatedNegativeMemoryMadeDemandResentment": 0,
			"iAggregatedNegativeMemoryCancelledVassalAgreementResentment": 50,
			"iAggregatedNegativeMemoryMadeDemandRecentResentment": 50,
			"iAggregatedNegativeMemoryCancelledOpenBordersResentment": 50,
			"iAggregatedNegativeMemoryCancelledDefensivePactResentment": 50,
			"iAggregatedNegativeMemoryReceivedTechFromAnyResentment": 50,
			"iAggregatedNegativeMemoryVotedAgainstUsResentment": 100,
			"iAggregatedNegativeMemoryEventBadToUsResentment": 50,
			"iAggregatedNegativeMemoryDeclaredWarRecentResentment": 50
		},
		"LEADER_CATHERINE": {
			"Type": "LEADER_CATHERINE",
			"Description": "TXT_KEY_LEADER_CATHERINE",
			"Civilopedia": "TXT_KEY_LEADER_CATHERINE_PEDIA",
			"ArtDefineTag": "ART_DEF_LEADER_CATHERINE",
			"getWonderConstructRand": "30",
			"getBaseAttitude": "1",
			"getBasePeaceWeight": "2",
			"getWarmongerRespect": "2",
			"getEspionageWeight": "130",
			"getRefuseToTalkWarThreshold": "6",
			"getNoTechTradeThreshold": "15",
			"getTechTradeKnownPercent": "20",
			"getMaxGoldTradePercent": "5",
			"getCultureVictoryWeight": "30",
			"getSpaceVictoryWeight": "45",
			"getConquestVictoryWeight": "25",
			"getDominationVictoryWeight": "40",
			"getDiplomacyVictoryWeight": "10",
			"getMaxWarRand": "100",
			"getMaxWarNearbyPowerRatio": "90",
			"getMaxWarDistantPowerRatio": "40",
			"getMaxWarMinAdjacentLandPercent": "1",
			"getLimitedWarRand": "80",
			"getLimitedWarPowerRatio": "110",
			"getDogpileWarRand": "25",
			"getMakePeaceRand": "10",
			"getDemandRebukedSneakProb": "80",
			"getDemandRebukedWarProb": "0",
			"getRazeCityProb": "0",
			"getBuildUnitProb": "40",
			"getBaseAttackOddsChange": "2",
			"getWorseRankDifferenceAttitudeChange": "-2",
			"getBetterRankDifferenceAttitudeChange": "0",
			"getCloseBordersAttitudeChange": "-4",
			"getSameReligionAttitudeChangeLimit": "4",
			"getDifferentReligionAttitudeChangeLimit": "-2",
			"getShareWarAttitudeChangeLimit": "2",
			"getFavoriteCivicAttitudeChangeLimit": "3",
			"getTechRefuseAttitudeThreshold": -1,
			"getCityRefuseAttitudeThreshold": 3,
			"getNativeCityRefuseAttitudeThreshold": 4,
			"getStrategicBonusRefuseAttitudeThreshold": 2,
			"getHappinessBonusRefuseAttitudeThreshold": 1,
			"getHealthBonusRefuseAttitudeThreshold": 0,
			"getMapRefuseAttitudeThreshold": 3,
			"getDeclareWarRefuseAttitudeThreshold": 3,
			"getDeclareWarThemRefuseAttitudeThreshold": 4,
			"getStopTradingRefuseAttitudeThreshold": 1,
			"getStopTradingThemRefuseAttitudeThreshold": 1,
			"getAdoptCivicRefuseAttitudeThreshold": 1,
			"getConvertReligionRefuseAttitudeThreshold": 2,
			"getOpenBordersRefuseAttitudeThreshold": 0,
			"getDefensivePactRefuseAttitudeThreshold": 2,
			"getVassalRefuseAttitudeThreshold": 1,
			"getVassalPowerModifier": "-20",
			"FavoriteCivic": "CIVIC_HEREDITARY_RULE",
			"FavoriteReligion": "RELIGION_CHRISTIANITY",
			"Traits": [
				{
					"TraitType": "TRAIT_PHILOSOPHICAL",
					"bTrait": "1"
				},
				{
					"TraitType": "TRAIT_IMPERIALIST",
					"bTrait": "1"
				}
			],
			"iFlavorCulture": 5,
			"iFlavorMilitary": 2,
			"iNoWarAttitudeProbCautious": 20,
			"iNoWarAttitudeProbPleased": 80,
			"iNoWarAttitudeProbFriendly": 80,
			"UnitAIWeightModifiers": [
				{
					"UnitAIType": "UNITAI_RESERVE",
					"iWeightModifier": "25"
				}
			],
			"ImprovementWeightModifiers": [
				{
					"ImprovementType": "IMPROVEMENT_FARM",
					"iWeightModifier": "20"
				},
				{
					"ImprovementType": "IMPROVEMENT_LUMBERMILL",
					"iWeightModifier": "20"
				}
			],
			"DiplomacyIntroMusicPeace": "",
			"DiplomacyMusicPeace": [
				{
					"EraType": "ERA_ANCIENT",
					"DiploScriptId": "AS2D_DIPLO_CATHERINE_EARLY"
				},
				{
					"EraType": "ERA_CLASSICAL",
					"DiploScriptId": "AS2D_DIPLO_CATHERINE_EARLY"
				},
				{
					"EraType": "ERA_MEDIEVAL",
					"DiploScriptId": "AS2D_DIPLO_CATHERINE_MIDDLE"
				},
				{
					"EraType": "ERA_RENAISSANCE",
					"DiploScriptId": "AS2D_DIPLO_CATHERINE_MIDDLE"
				},
				{
					"EraType": "ERA_INDUSTRIAL",
					"DiploScriptId": "AS2D_DIPLO_CATHERINE_LATE"
				},
				{
					"EraType": "ERA_MODERN",
					"DiploScriptId": "AS2D_DIPLO_CATHERINE_LATE"
				},
				{
					"EraType": "ERA_FUTURE",
					"DiploScriptId": "AS2D_DIPLO_CATHERINE_LATE"
				}
			],
			"DiplomacyIntroMusicWar": "",
			"DiplomacyMusicWar": "",
			"getPeaceWeightRand": "3",
			"getMaxGoldPerTurnTradePercent": "10",
			"getDeclareWarTradeRand": "40",
			"getAttackOddsChangeRand": "8",
			"getLostWarAttitudeChange": "-1",
			"getAtWarAttitudeDivisor": "-5",
			"getAtWarAttitudeChangeLimit": "5",
			"getAtPeaceAttitudeDivisor": "60",
			"getAtPeaceAttitudeChangeLimit": "1",
			"getSameReligionAttitudeChange": "1",
			"getSameReligionAttitudeDivisor": "10",
			"getDifferentReligionAttitudeChange": "-1",
			"getDifferentReligionAttitudeDivisor": "-15",
			"getBonusTradeAttitudeDivisor": "50",
			"getBonusTradeAttitudeChangeLimit": "2",
			"getOpenBordersAttitudeDivisor": "25",
			"getOpenBordersAttitudeChangeLimit": "2",
			"getDefensivePactAttitudeDivisor": "12",
			"getDefensivePactAttitudeChangeLimit": "2",
			"getShareWarAttitudeChange": "1",
			"getShareWarAttitudeDivisor": "8",
			"getFavoriteCivicAttitudeChange": "1",
			"getFavoriteCivicAttitudeDivisor": "10",
			"getDemandTributeAttitudeThreshold": 2,
			"getNoGiveHelpAttitudeThreshold": 2,
			"getPermanentAllianceRefuseAttitudeThreshold": 3,
			"getFreedomAppreciation": "10",
			"iNoWarAttitudeProbFurious": 0,
			"iNoWarAttitudeProbAnnoyed": 0,
			"iLoveOfPeace": 0,
			"iFlavorReligion": 0,
			"iFlavorProduction": 0,
			"iFlavorGold": 0,
			"iFlavorScience": 0,
			"iFlavorGrowth": 0,
			"iFlavorEspionage": 0,
			"iContactRandReligionPressure": 250,
			"iContactDelayReligionPressure": 50,
			"iContactRandCivicPressure": 500,
			"iContactDelayCivicPressure": 50,
			"iContactRandJoinWar": 10,
			"iContactDelayJoinWar": 20,
			"iContactRandStopTrading": 50,
			"iContactDelayStopTrading": 20,
			"iContactRandGiveHelp": 500,
			"iContactDelayGiveHelp": 50,
			"iContactRandAskForHelp": 25,
			"iContactDelayAskForHelp": 50,
			"iContactRandDemandTribute": 750,
			"iContactDelayDemandTribute": 50,
			"iContactRandTradeTech": 2,
			"iContactDelayTradeTech": 30,
			"iContactRandTradeBonus": 2,
			"iContactDelayTradeBonus": 20,
			"iContactRandPeaceTreaty": 15,
			"iContactDelayPeaceTreaty": 10,
			"iContactRandOpenBorders": 10,
			"iContactDelayOpenBorders": 40,
			"iContactRandDefensivePact": 80,
			"iContactDelayDefensivePact": 20,
			"iContactRandPermanentAlliance": 80,
			"iContactDelayPermanentAlliance": 20,
			"iContactRandTradeMap": 20,
			"iContactDelayTradeMap": 50,
			"iAggregatedContactProbReligionPressure": 79,
			"iAggregatedContactProbCivicPressure": 58,
			"iAggregatedContactProbJoinWar": 100,
			"iAggregatedContactProbStopTrading": 50,
			"iAggregatedContactProbGiveHelp": 57,
			"iAggregatedContactProbAskForHelp": 100,
			"iAggregatedContactProbDemandTribute": 34,
			"iAggregatedContactProbTradeTech": 95,
			"iAggregatedContactProbTradeBonus": 92,
			"iAggregatedContactProbPeaceTreaty": 70,
			"iAggregatedContactProbOpenBorders": 50,
			"iAggregatedContactProbDefensivePact": 50,
			"iAggregatedContactProbPermanentAlliance": 50,
			"iAggregatedContactProbTradeMap": 50,
			"iMemoryAttitudePercentGiveHelp": 100,
			"iMemoryDecayGiveHelp": 150,
			"iMemoryAttitudePercentAcceptDemand": 100,
			"iMemoryDecayAcceptDemand": 30,
			"iMemoryAttitudePercentAcceptedReligion": 100,
			"iMemoryDecayAcceptedReligion": 100,
			"iMemoryAttitudePercentAcceptedCivic": 100,
			"iMemoryDecayAcceptedCivic": 100,
			"iMemoryAttitudePercentAcceptedJoinWar": 100,
			"iMemoryDecayAcceptedJoinWar": 100,
			"iMemoryAttitudePercentAcceptedStopTrading": 50,
			"iMemoryDecayAcceptedStopTrading": 50,
			"iMemoryAttitudePercentTradedTechToUs": 15,
			"iMemoryDecayTradedTechToUs": 25,
			"iMemoryAttitudePercentVotedForUs": 200,
			"iMemoryDecayVotedForUs": 10,
			"iMemoryAttitudePercentEventGoodToUs": 100,
			"iMemoryDecayEventGoodToUs": 50,
			"iMemoryAttitudePercentLiberatedCities": 150,
			"iMemoryDecayLiberatedCities": 150,
			"iMemoryAttitudePercentIndependence": 100,
			"iMemoryDecayIndependence": 30,
			"iAggregatedPositiveMemoryGiveHelpAffection": 50,
			"iAggregatedPositiveMemoryAcceptDemandAffection": 50,
			"iAggregatedPositiveMemoryAcceptedReligionAffection": 50,
			"iAggregatedPositiveMemoryAcceptedCivicAffection": 50,
			"iAggregatedPositiveMemoryAcceptedJoinWarAffection": 50,
			"iAggregatedPositiveMemoryAcceptedStopTradingAffection": 50,
			"iAggregatedPositiveMemoryTradedTechToUsAffection": 68,
			"iAggregatedPositiveMemoryVotedForUsAffection": 50,
			"iAggregatedPositiveMemoryEventGoodToUsAffection": 50,
			"iAggregatedPositiveMemoryLiberatedCitiesAffection": 50,
			"iAggregatedPositiveMemoryIndependenceAffection": 50,
			"iAggregatedPositiveMemoryGiveHelpResentment": 50,
			"iAggregatedPositiveMemoryAcceptDemandResentment": 50,
			"iAggregatedPositiveMemoryAcceptedReligionResentment": 50,
			"iAggregatedPositiveMemoryAcceptedCivicResentment": 50,
			"iAggregatedPositiveMemoryAcceptedJoinWarResentment": 50,
			"iAggregatedPositiveMemoryAcceptedStopTradingResentment": 50,
			"iAggregatedPositiveMemoryTradedTechToUsResentment": 50,
			"iAggregatedPositiveMemoryVotedForUsResentment": 50,
			"iAggregatedPositiveMemoryEventGoodToUsResentment": 50,
			"iAggregatedPositiveMemoryLiberatedCitiesResentment": 50,
			"iAggregatedPositiveMemoryIndependenceResentment": 50,
			"iMemoryAttitudePercentDeclaredWar": -300,
			"iMemoryDecayDeclaredWar": 150,
			"iMemoryAttitudePercentDeclaredWarOnFriend": -100,
			"iMemoryDecayDeclaredWarOnFriend": 120,
			"iMemoryAttitudePercentHiredWarAlly": -200,
			"iMemoryDecayHiredWarAlly": 75,
			"iMemoryAttitudePercentNukedUs": -200,
			"iMemoryDecayNukedUs": 120,
			"iMemoryAttitudePercentNukedFriend": -100,
			"iMemoryDecayNukedFriend": 80,
			"iMemoryAttitudePercentRazedCity": -250,
			"iMemoryDecayRazedCity": 75,
			"iMemoryAttitudePercentRazedHolyCity": -200,
			"iMemoryDecayRazedHolyCity": 150,
			"iMemoryAttitudePercentSpyCaught": -200,
			"iMemoryDecaySpyCaught": 40,
			"iMemoryAttitudePercentRefusedHelp": -200,
			"iMemoryDecayRefusedHelp": 100,
			"iMemoryAttitudePercentRejectedDemand": -200,
			"iMemoryDecayRejectedDemand": 90,
			"iMemoryAttitudePercentDeniedReligion": -200,
			"iMemoryDecayDeniedReligion": 50,
			"iMemoryAttitudePercentDeniedCivic": -200,
			"iMemoryDecayDeniedCivic": 50,
			"iMemoryAttitudePercentDeniedJoinWar": -200,
			"iMemoryDecayDeniedJoinWar": 100,
			"iMemoryAttitudePercentDeniedStopTrading": -200,
			"iMemoryDecayDeniedStopTrading": 50,
			"iMemoryAttitudePercentStoppedTrading": -100,
			"iMemoryDecayStoppedTrading": 60,
			"iMemoryAttitudePercentStoppedTradingRecent": 0,
			"iMemoryDecayStoppedTradingRecent": 18,
			"iMemoryAttitudePercentHiredTradeEmbargo": -100,
			"iMemoryDecayHiredTradeEmbargo": 60,
			"iMemoryAttitudePercentMadeDemand": -200,
			"iMemoryDecayMadeDemand": 30,
			"iMemoryAttitudePercentCancelledVassalAgreement": 0,
			"iMemoryDecayCancelledVassalAgreement": 10,
			"iMemoryAttitudePercentMadeDemandRecent": 0,
			"iMemoryDecayMadeDemandRecent": 20,
			"iMemoryAttitudePercentCancelledOpenBorders": 0,
			"iMemoryDecayCancelledOpenBorders": 10,
			"iMemoryAttitudePercentCancelledDefensivePact": 0,
			"iMemoryDecayCancelledDefensivePact": 10,
			"iMemoryAttitudePercentReceivedTechFromAny": 0,
			"iMemoryDecayReceivedTechFromAny": 20,
			"iMemoryAttitudePercentVotedAgainstUs": -200,
			"iMemoryDecayVotedAgainstUs": 10,
			"iMemoryAttitudePercentEventBadToUs": -100,
			"iMemoryDecayEventBadToUs": 50,
			"iMemoryAttitudePercentDeclaredWarRecent": 0,
			"iMemoryDecayDeclaredWarRecent": 11,
			"iAggregatedNegativeMemoryDeclaredWarAffection": 50,
			"iAggregatedNegativeMemoryDeclaredWarOnFriendAffection": 50,
			"iAggregatedNegativeMemoryHiredWarAllyAffection": 50,
			"iAggregatedNegativeMemoryNukedUsAffection": 50,
			"iAggregatedNegativeMemoryNukedFriendAffection": 50,
			"iAggregatedNegativeMemoryRazedCityAffection": 50,
			"iAggregatedNegativeMemoryRazedHolyCityAffection": 50,
			"iAggregatedNegativeMemorySpyCaughtAffection": 50,
			"iAggregatedNegativeMemoryRefusedHelpAffection": 50,
			"iAggregatedNegativeMemoryRejectedDemandAffection": 50,
			"iAggregatedNegativeMemoryDeniedReligionAffection": 50,
			"iAggregatedNegativeMemoryDeniedCivicAffection": 50,
			"iAggregatedNegativeMemoryDeniedJoinWarAffection": 50,
			"iAggregatedNegativeMemoryDeniedStopTradingAffection": 50,
			"iAggregatedNegativeMemoryStoppedTradingAffection": 50,
			"iAggregatedNegativeMemoryStoppedTradingRecentAffection": 50,
			"iAggregatedNegativeMemoryHiredTradeEmbargoAffection": 50,
			"iAggregatedNegativeMemoryMadeDemandAffection": 50,
			"iAggregatedNegativeMemoryCancelledVassalAgreementAffection": 50,
			"iAggregatedNegativeMemoryMadeDemandRecentAffection": 50,
			"iAggregatedNegativeMemoryCancelledOpenBordersAffection": 50,
			"iAggregatedNegativeMemoryCancelledDefensivePactAffection": 50,
			"iAggregatedNegativeMemoryReceivedTechFromAnyAffection": 50,
			"iAggregatedNegativeMemoryVotedAgainstUsAffection": 50,
			"iAggregatedNegativeMemoryEventBadToUsAffection": 50,
			"iAggregatedNegativeMemoryDeclaredWarRecentAffection": 50,
			"iAggregatedNegativeMemoryDeclaredWarResentment": 50,
			"iAggregatedNegativeMemoryDeclaredWarOnFriendResentment": 0,
			"iAggregatedNegativeMemoryHiredWarAllyResentment": 50,
			"iAggregatedNegativeMemoryNukedUsResentment": 50,
			"iAggregatedNegativeMemoryNukedFriendResentment": 0,
			"iAggregatedNegativeMemoryRazedCityResentment": 50,
			"iAggregatedNegativeMemoryRazedHolyCityResentment": 50,
			"iAggregatedNegativeMemorySpyCaughtResentment": 100,
			"iAggregatedNegativeMemoryRefusedHelpResentment": 100,
			"iAggregatedNegativeMemoryRejectedDemandResentment": 100,
			"iAggregatedNegativeMemoryDeniedReligionResentment": 100,
			"iAggregatedNegativeMemoryDeniedCivicResentment": 100,
			"iAggregatedNegativeMemoryDeniedJoinWarResentment": 100,
			"iAggregatedNegativeMemoryDeniedStopTradingResentment": 100,
			"iAggregatedNegativeMemoryStoppedTradingResentment": 100,
			"iAggregatedNegativeMemoryStoppedTradingRecentResentment": 50,
			"iAggregatedNegativeMemoryHiredTradeEmbargoResentment": 50,
			"iAggregatedNegativeMemoryMadeDemandResentment": 100,
			"iAggregatedNegativeMemoryCancelledVassalAgreementResentment": 50,
			"iAggregatedNegativeMemoryMadeDemandRecentResentment": 50,
			"iAggregatedNegativeMemoryCancelledOpenBordersResentment": 50,
			"iAggregatedNegativeMemoryCancelledDefensivePactResentment": 50,
			"iAggregatedNegativeMemoryReceivedTechFromAnyResentment": 50,
			"iAggregatedNegativeMemoryVotedAgainstUsResentment": 100,
			"iAggregatedNegativeMemoryEventBadToUsResentment": 50,
			"iAggregatedNegativeMemoryDeclaredWarRecentResentment": 50
		},
		"LEADER_GANDHI": {
			"Type": "LEADER_GANDHI",
			"Description": "TXT_KEY_LEADER_GANDHI",
			"Civilopedia": "TXT_KEY_LEADER_GANDHI_PEDIA",
			"ArtDefineTag": "ART_DEF_LEADER_GANDHI",
			"getWonderConstructRand": "10",
			"getBaseAttitude": "2",
			"getBasePeaceWeight": "10",
			"getWarmongerRespect": "0",
			"getEspionageWeight": "50",
			"getRefuseToTalkWarThreshold": "6",
			"getNoTechTradeThreshold": "15",
			"getTechTradeKnownPercent": "20",
			"getMaxGoldTradePercent": "10",
			"getCultureVictoryWeight": "45",
			"getSpaceVictoryWeight": "30",
			"getConquestVictoryWeight": "0",
			"getDominationVictoryWeight": "5",
			"getDiplomacyVictoryWeight": "70",
			"getMaxWarRand": "400",
			"getMaxWarNearbyPowerRatio": "100",
			"getMaxWarDistantPowerRatio": "60",
			"getMaxWarMinAdjacentLandPercent": "3",
			"getLimitedWarRand": "200",
			"getLimitedWarPowerRatio": "80",
			"getDogpileWarRand": "100",
			"getMakePeaceRand": "10",
			"getDemandRebukedSneakProb": "0",
			"getDemandRebukedWarProb": "0",
			"getRazeCityProb": "0",
			"getBuildUnitProb": "25",
			"getBaseAttackOddsChange": "0",
			"getWorseRankDifferenceAttitudeChange": "0",
			"getBetterRankDifferenceAttitudeChange": "1",
			"getCloseBordersAttitudeChange": "-2",
			"getSameReligionAttitudeChangeLimit": "4",
			"getDifferentReligionAttitudeChangeLimit": "-1",
			"getShareWarAttitudeChangeLimit": "2",
			"getFavoriteCivicAttitudeChangeLimit": "5",
			"getTechRefuseAttitudeThreshold": -1,
			"getCityRefuseAttitudeThreshold": 3,
			"getNativeCityRefuseAttitudeThreshold": 4,
			"getStrategicBonusRefuseAttitudeThreshold": 1,
			"getHappinessBonusRefuseAttitudeThreshold": -1,
			"getHealthBonusRefuseAttitudeThreshold": -1,
			"getMapRefuseAttitudeThreshold": -1,
			"getDeclareWarRefuseAttitudeThreshold": 3,
			"getDeclareWarThemRefuseAttitudeThreshold": 1,
			"getStopTradingRefuseAttitudeThreshold": 3,
			"getStopTradingThemRefuseAttitudeThreshold": 2,
			"getAdoptCivicRefuseAttitudeThreshold": 2,
			"getConvertReligionRefuseAttitudeThreshold": 1,
			"getOpenBordersRefuseAttitudeThreshold": -1,
			"getVassalRefuseAttitudeThreshold": 1,
			"getVassalPowerModifier": "-20",
			"FavoriteCivic": "CIVIC_UNIVERSAL_SUFFRAGE",
			"FavoriteReligion": "RELIGION_HINDUISM",
			"Traits": [
				{
					"TraitType": "TRAIT_SPIRITUAL",
					"bTrait": "1"
				},
				{
					"TraitType": "TRAIT_PHILOSOPHICAL",
					"bTrait": "1"
				}
			],
			"iFlavorCulture": 10,
			"iNoWarAttitudeProbFurious": 20,
			"iNoWarAttitudeProbAnnoyed": 50,
			"iNoWarAttitudeProbCautious": 85,
			"iNoWarAttitudeProbPleased": 110,
			"iNoWarAttitudeProbFriendly": 115,
			"UnitAIWeightModifiers": "",
			"ImprovementWeightModifiers": [
				{
					"ImprovementType": "IMPROVEMENT_FARM",
					"iWeightModifier": "30"
				}
			],
			"DiplomacyIntroMusicPeace": [
				{
					"EraType": "ERA_ANCIENT",
					"DiploScriptId": "AS2D_DIPLO_GANDHI_EARLY_INTRO"
				},
				{
					"EraType": "ERA_CLASSICAL",
					"DiploScriptId": "AS2D_DIPLO_GANDHI_EARLY_INTRO"
				}
			],
			"DiplomacyMusicPeace": [
				{
					"EraType": "ERA_ANCIENT",
					"DiploScriptId": "AS2D_DIPLO_GANDHI_EARLY_LP"
				},
				{
					"EraType": "ERA_CLASSICAL",
					"DiploScriptId": "AS2D_DIPLO_GANDHI_EARLY_LP"
				},
				{
					"EraType": "ERA_MEDIEVAL",
					"DiploScriptId": "AS2D_DIPLO_GANDHI_MIDDLE"
				},
				{
					"EraType": "ERA_RENAISSANCE",
					"DiploScriptId": "AS2D_DIPLO_GANDHI_MIDDLE"
				},
				{
					"EraType": "ERA_INDUSTRIAL",
					"DiploScriptId": "AS2D_DIPLO_GANDHI_LATE"
				},
				{
					"EraType": "ERA_MODERN",
					"DiploScriptId": "AS2D_DIPLO_GANDHI_LATE"
				},
				{
					"EraType": "ERA_FUTURE",
					"DiploScriptId": "AS2D_DIPLO_GANDHI_LATE"
				}
			],
			"DiplomacyIntroMusicWar": "",
			"DiplomacyMusicWar": "",
			"getPeaceWeightRand": "3",
			"getMaxGoldPerTurnTradePercent": "10",
			"getDeclareWarTradeRand": "40",
			"getAttackOddsChangeRand": "8",
			"getLostWarAttitudeChange": "-1",
			"getAtWarAttitudeDivisor": "-5",
			"getAtWarAttitudeChangeLimit": "5",
			"getAtPeaceAttitudeDivisor": "60",
			"getAtPeaceAttitudeChangeLimit": "1",
			"getSameReligionAttitudeChange": "1",
			"getSameReligionAttitudeDivisor": "10",
			"getDifferentReligionAttitudeChange": "-1",
			"getDifferentReligionAttitudeDivisor": "-15",
			"getBonusTradeAttitudeDivisor": "50",
			"getBonusTradeAttitudeChangeLimit": "2",
			"getOpenBordersAttitudeDivisor": "25",
			"getOpenBordersAttitudeChangeLimit": "2",
			"getDefensivePactAttitudeDivisor": "12",
			"getDefensivePactAttitudeChangeLimit": "2",
			"getShareWarAttitudeChange": "1",
			"getShareWarAttitudeDivisor": "8",
			"getFavoriteCivicAttitudeChange": "1",
			"getFavoriteCivicAttitudeDivisor": "10",
			"getDemandTributeAttitudeThreshold": 2,
			"getNoGiveHelpAttitudeThreshold": 2,
			"getDefensivePactRefuseAttitudeThreshold": 3,
			"getPermanentAllianceRefuseAttitudeThreshold": 3,
			"getFreedomAppreciation": "10",
			"iLoveOfPeace": 0,
			"iFlavorMilitary": 0,
			"iFlavorReligion": 0,
			"iFlavorProduction": 0,
			"iFlavorGold": 0,
			"iFlavorScience": 0,
			"iFlavorGrowth": 0,
			"iFlavorEspionage": 0,
			"iContactRandReligionPressure": 500,
			"iContactDelayReligionPressure": 50,
			"iContactRandCivicPressure": 50,
			"iContactDelayCivicPressure": 50,
			"iContactRandJoinWar": 20,
			"iContactDelayJoinWar": 20,
			"iContactRandStopTrading": 50,
			"iContactDelayStopTrading": 20,
			"iContactRandGiveHelp": 25,
			"iContactDelayGiveHelp": 50,
			"iContactRandAskForHelp": 50,
			"iContactDelayAskForHelp": 50,
			"iContactRandDemandTribute": 0,
			"iContactDelayDemandTribute": 50,
			"iContactRandTradeTech": 2,
			"iContactDelayTradeTech": 30,
			"iContactRandTradeBonus": 2,
			"iContactDelayTradeBonus": 20,
			"iContactRandPeaceTreaty": 10,
			"iContactDelayPeaceTreaty": 8,
			"iContactRandOpenBorders": 10,
			"iContactDelayOpenBorders": 40,
			"iContactRandDefensivePact": 80,
			"iContactDelayDefensivePact": 20,
			"iContactRandPermanentAlliance": 80,
			"iContactDelayPermanentAlliance": 20,
			"iContactRandTradeMap": 20,
			"iContactDelayTradeMap": 50,
			"iAggregatedContactProbReligionPressure": 52,
			"iAggregatedContactProbCivicPressure": 100,
			"iAggregatedContactProbJoinWar": 0,
			"iAggregatedContactProbStopTrading": 50,
			"iAggregatedContactProbGiveHelp": 100,
			"iAggregatedContactProbAskForHelp": 98,
			"iAggregatedContactProbDemandTribute": 0,
			"iAggregatedContactProbTradeTech": 95,
			"iAggregatedContactProbTradeBonus": 92,
			"iAggregatedContactProbPeaceTreaty": 100,
			"iAggregatedContactProbOpenBorders": 50,
			"iAggregatedContactProbDefensivePact": 50,
			"iAggregatedContactProbPermanentAlliance": 50,
			"iAggregatedContactProbTradeMap": 50,
			"iMemoryAttitudePercentGiveHelp": 100,
			"iMemoryDecayGiveHelp": 150,
			"iMemoryAttitudePercentAcceptDemand": 100,
			"iMemoryDecayAcceptDemand": 30,
			"iMemoryAttitudePercentAcceptedReligion": 100,
			"iMemoryDecayAcceptedReligion": 100,
			"iMemoryAttitudePercentAcceptedCivic": 100,
			"iMemoryDecayAcceptedCivic": 100,
			"iMemoryAttitudePercentAcceptedJoinWar": 100,
			"iMemoryDecayAcceptedJoinWar": 100,
			"iMemoryAttitudePercentAcceptedStopTrading": 50,
			"iMemoryDecayAcceptedStopTrading": 50,
			"iMemoryAttitudePercentTradedTechToUs": 5,
			"iMemoryDecayTradedTechToUs": 25,
			"iMemoryAttitudePercentVotedForUs": 200,
			"iMemoryDecayVotedForUs": 10,
			"iMemoryAttitudePercentEventGoodToUs": 100,
			"iMemoryDecayEventGoodToUs": 50,
			"iMemoryAttitudePercentLiberatedCities": 150,
			"iMemoryDecayLiberatedCities": 150,
			"iMemoryAttitudePercentIndependence": 100,
			"iMemoryDecayIndependence": 30,
			"iAggregatedPositiveMemoryGiveHelpAffection": 50,
			"iAggregatedPositiveMemoryAcceptDemandAffection": 50,
			"iAggregatedPositiveMemoryAcceptedReligionAffection": 50,
			"iAggregatedPositiveMemoryAcceptedCivicAffection": 50,
			"iAggregatedPositiveMemoryAcceptedJoinWarAffection": 50,
			"iAggregatedPositiveMemoryAcceptedStopTradingAffection": 50,
			"iAggregatedPositiveMemoryTradedTechToUsAffection": 0,
			"iAggregatedPositiveMemoryVotedForUsAffection": 50,
			"iAggregatedPositiveMemoryEventGoodToUsAffection": 50,
			"iAggregatedPositiveMemoryLiberatedCitiesAffection": 50,
			"iAggregatedPositiveMemoryIndependenceAffection": 50,
			"iAggregatedPositiveMemoryGiveHelpResentment": 50,
			"iAggregatedPositiveMemoryAcceptDemandResentment": 50,
			"iAggregatedPositiveMemoryAcceptedReligionResentment": 50,
			"iAggregatedPositiveMemoryAcceptedCivicResentment": 50,
			"iAggregatedPositiveMemoryAcceptedJoinWarResentment": 50,
			"iAggregatedPositiveMemoryAcceptedStopTradingResentment": 50,
			"iAggregatedPositiveMemoryTradedTechToUsResentment": 50,
			"iAggregatedPositiveMemoryVotedForUsResentment": 50,
			"iAggregatedPositiveMemoryEventGoodToUsResentment": 50,
			"iAggregatedPositiveMemoryLiberatedCitiesResentment": 50,
			"iAggregatedPositiveMemoryIndependenceResentment": 50,
			"iMemoryAttitudePercentDeclaredWar": -300,
			"iMemoryDecayDeclaredWar": 150,
			"iMemoryAttitudePercentDeclaredWarOnFriend": -200,
			"iMemoryDecayDeclaredWarOnFriend": 120,
			"iMemoryAttitudePercentHiredWarAlly": -200,
			"iMemoryDecayHiredWarAlly": 75,
			"iMemoryAttitudePercentNukedUs": -200,
			"iMemoryDecayNukedUs": 120,
			"iMemoryAttitudePercentNukedFriend": -200,
			"iMemoryDecayNukedFriend": 80,
			"iMemoryAttitudePercentRazedCity": -250,
			"iMemoryDecayRazedCity": 75,
			"iMemoryAttitudePercentRazedHolyCity": -200,
			"iMemoryDecayRazedHolyCity": 150,
			"iMemoryAttitudePercentSpyCaught": -100,
			"iMemoryDecaySpyCaught": 40,
			"iMemoryAttitudePercentRefusedHelp": 0,
			"iMemoryDecayRefusedHelp": 100,
			"iMemoryAttitudePercentRejectedDemand": 0,
			"iMemoryDecayRejectedDemand": 90,
			"iMemoryAttitudePercentDeniedReligion": 0,
			"iMemoryDecayDeniedReligion": 50,
			"iMemoryAttitudePercentDeniedCivic": 0,
			"iMemoryDecayDeniedCivic": 50,
			"iMemoryAttitudePercentDeniedJoinWar": 0,
			"iMemoryDecayDeniedJoinWar": 100,
			"iMemoryAttitudePercentDeniedStopTrading": 0,
			"iMemoryDecayDeniedStopTrading": 50,
			"iMemoryAttitudePercentStoppedTrading": 0,
			"iMemoryDecayStoppedTrading": 60,
			"iMemoryAttitudePercentStoppedTradingRecent": 0,
			"iMemoryDecayStoppedTradingRecent": 18,
			"iMemoryAttitudePercentHiredTradeEmbargo": -100,
			"iMemoryDecayHiredTradeEmbargo": 60,
			"iMemoryAttitudePercentMadeDemand": -100,
			"iMemoryDecayMadeDemand": 30,
			"iMemoryAttitudePercentCancelledVassalAgreement": 0,
			"iMemoryDecayCancelledVassalAgreement": 10,
			"iMemoryAttitudePercentMadeDemandRecent": 0,
			"iMemoryDecayMadeDemandRecent": 20,
			"iMemoryAttitudePercentCancelledOpenBorders": 0,
			"iMemoryDecayCancelledOpenBorders": 10,
			"iMemoryAttitudePercentCancelledDefensivePact": 0,
			"iMemoryDecayCancelledDefensivePact": 10,
			"iMemoryAttitudePercentReceivedTechFromAny": 0,
			"iMemoryDecayReceivedTechFromAny": 20,
			"iMemoryAttitudePercentVotedAgainstUs": 0,
			"iMemoryDecayVotedAgainstUs": 10,
			"iMemoryAttitudePercentEventBadToUs": -100,
			"iMemoryDecayEventBadToUs": 50,
			"iMemoryAttitudePercentDeclaredWarRecent": 0,
			"iMemoryDecayDeclaredWarRecent": 11,
			"iAggregatedNegativeMemoryDeclaredWarAffection": 50,
			"iAggregatedNegativeMemoryDeclaredWarOnFriendAffection": 50,
			"iAggregatedNegativeMemoryHiredWarAllyAffection": 50,
			"iAggregatedNegativeMemoryNukedUsAffection": 50,
			"iAggregatedNegativeMemoryNukedFriendAffection": 50,
			"iAggregatedNegativeMemoryRazedCityAffection": 50,
			"iAggregatedNegativeMemoryRazedHolyCityAffection": 50,
			"iAggregatedNegativeMemorySpyCaughtAffection": 50,
			"iAggregatedNegativeMemoryRefusedHelpAffection": 50,
			"iAggregatedNegativeMemoryRejectedDemandAffection": 50,
			"iAggregatedNegativeMemoryDeniedReligionAffection": 50,
			"iAggregatedNegativeMemoryDeniedCivicAffection": 50,
			"iAggregatedNegativeMemoryDeniedJoinWarAffection": 50,
			"iAggregatedNegativeMemoryDeniedStopTradingAffection": 50,
			"iAggregatedNegativeMemoryStoppedTradingAffection": 50,
			"iAggregatedNegativeMemoryStoppedTradingRecentAffection": 50,
			"iAggregatedNegativeMemoryHiredTradeEmbargoAffection": 50,
			"iAggregatedNegativeMemoryMadeDemandAffection": 50,
			"iAggregatedNegativeMemoryCancelledVassalAgreementAffection": 50,
			"iAggregatedNegativeMemoryMadeDemandRecentAffection": 50,
			"iAggregatedNegativeMemoryCancelledOpenBordersAffection": 50,
			"iAggregatedNegativeMemoryCancelledDefensivePactAffection": 50,
			"iAggregatedNegativeMemoryReceivedTechFromAnyAffection": 50,
			"iAggregatedNegativeMemoryVotedAgainstUsAffection": 50,
			"iAggregatedNegativeMemoryEventBadToUsAffection": 50,
			"iAggregatedNegativeMemoryDeclaredWarRecentAffection": 50,
			"iAggregatedNegativeMemoryDeclaredWarResentment": 50,
			"iAggregatedNegativeMemoryDeclaredWarOnFriendResentment": 100,
			"iAggregatedNegativeMemoryHiredWarAllyResentment": 50,
			"iAggregatedNegativeMemoryNukedUsResentment": 50,
			"iAggregatedNegativeMemoryNukedFriendResentment": 100,
			"iAggregatedNegativeMemoryRazedCityResentment": 50,
			"iAggregatedNegativeMemoryRazedHolyCityResentment": 50,
			"iAggregatedNegativeMemorySpyCaughtResentment": 0,
			"iAggregatedNegativeMemoryRefusedHelpResentment": 0,
			"iAggregatedNegativeMemoryRejectedDemandResentment": 0,
			"iAggregatedNegativeMemoryDeniedReligionResentment": 0,
			"iAggregatedNegativeMemoryDeniedCivicResentment": 0,
			"iAggregatedNegativeMemoryDeniedJoinWarResentment": 0,
			"iAggregatedNegativeMemoryDeniedStopTradingResentment": 0,
			"iAggregatedNegativeMemoryStoppedTradingResentment": 0,
			"iAggregatedNegativeMemoryStoppedTradingRecentResentment": 50,
			"iAggregatedNegativeMemoryHiredTradeEmbargoResentment": 50,
			"iAggregatedNegativeMemoryMadeDemandResentment": 0,
			"iAggregatedNegativeMemoryCancelledVassalAgreementResentment": 50,
			"iAggregatedNegativeMemoryMadeDemandRecentResentment": 50,
			"iAggregatedNegativeMemoryCancelledOpenBordersResentment": 50,
			"iAggregatedNegativeMemoryCancelledDefensivePactResentment": 50,
			"iAggregatedNegativeMemoryReceivedTechFromAnyResentment": 50,
			"iAggregatedNegativeMemoryVotedAgainstUsResentment": 0,
			"iAggregatedNegativeMemoryEventBadToUsResentment": 50,
			"iAggregatedNegativeMemoryDeclaredWarRecentResentment": 50
		},
		"LEADER_TOKUGAWA": {
			"Type": "LEADER_TOKUGAWA",
			"Description": "TXT_KEY_LEADER_TOKUGAWA",
			"Civilopedia": "TXT_KEY_LEADER_TOKUGAWA_PEDIA",
			"ArtDefineTag": "ART_DEF_LEADER_TOKUGAWA",
			"getWonderConstructRand": "20",
			"getBaseAttitude": "-1",
			"getBasePeaceWeight": "1",
			"getWarmongerRespect": "2",
			"getEspionageWeight": "60",
			"getRefuseToTalkWarThreshold": "10",
			"getNoTechTradeThreshold": "5",
			"getTechTradeKnownPercent": "100",
			"getMaxGoldTradePercent": "5",
			"getCultureVictoryWeight": "25",
			"getSpaceVictoryWeight": "40",
			"getConquestVictoryWeight": "40",
			"getDominationVictoryWeight": "45",
			"getDiplomacyVictoryWeight": "0",
			"getMaxWarRand": "100",
			"getMaxWarNearbyPowerRatio": "100",
			"getMaxWarDistantPowerRatio": "30",
			"getMaxWarMinAdjacentLandPercent": "4",
			"getLimitedWarRand": "60",
			"getLimitedWarPowerRatio": "100",
			"getDogpileWarRand": "25",
			"getMakePeaceRand": "40",
			"getDemandRebukedSneakProb": "60",
			"getDemandRebukedWarProb": "25",
			"getRazeCityProb": "25",
			"getBuildUnitProb": "45",
			"getBaseAttackOddsChange": "0",
			"getWorseRankDifferenceAttitudeChange": "0",
			"getBetterRankDifferenceAttitudeChange": "1",
			"getCloseBordersAttitudeChange": "-3",
			"getSameReligionAttitudeChangeLimit": "3",
			"getDifferentReligionAttitudeChangeLimit": "-1",
			"getShareWarAttitudeChangeLimit": "4",
			"getFavoriteCivicAttitudeChangeLimit": "4",
			"getTechRefuseAttitudeThreshold": 2,
			"getCityRefuseAttitudeThreshold": 2,
			"getNativeCityRefuseAttitudeThreshold": 4,
			"getStrategicBonusRefuseAttitudeThreshold": 3,
			"getHappinessBonusRefuseAttitudeThreshold": 2,
			"getHealthBonusRefuseAttitudeThreshold": 2,
			"getMapRefuseAttitudeThreshold": 4,
			"getDeclareWarRefuseAttitudeThreshold": 2,
			"getDeclareWarThemRefuseAttitudeThreshold": 3,
			"getStopTradingRefuseAttitudeThreshold": 1,
			"getStopTradingThemRefuseAttitudeThreshold": 3,
			"getAdoptCivicRefuseAttitudeThreshold": 3,
			"getConvertReligionRefuseAttitudeThreshold": 3,
			"getOpenBordersRefuseAttitudeThreshold": 2,
			"getDefensivePactRefuseAttitudeThreshold": 2,
			"getVassalRefuseAttitudeThreshold": 2,
			"getVassalPowerModifier": "0",
			"FavoriteCivic": "CIVIC_MERCANTILISM",
			"FavoriteReligion": "RELIGION_BUDDHISM",
			"Traits": [
				{
					"TraitType": "TRAIT_PROTECTIVE",
					"bTrait": "1"
				},
				{
					"TraitType": "TRAIT_ORGANIZED",
					"bTrait": "1"
				}
			],
			"iFlavorMilitary": 2,
			"iFlavorScience": 5,
			"iNoWarAttitudeProbAnnoyed": 10,
			"iNoWarAttitudeProbCautious": 50,
			"iNoWarAttitudeProbPleased": 90,
			"iNoWarAttitudeProbFriendly": 90,
			"UnitAIWeightModifiers": [
				{
					"UnitAIType": "UNITAI_CITY_COUNTER",
					"iWeightModifier": "25"
				},
				{
					"UnitAIType": "UNITAI_WORKER",
					"iWeightModifier": "25"
				}
			],
			"ImprovementWeightModifiers": [
				{
					"ImprovementType": "IMPROVEMENT_FARM",
					"iWeightModifier": "20"
				},
				{
					"ImprovementType": "IMPROVEMENT_LUMBERMILL",
					"iWeightModifier": "20"
				}
			],
			"DiplomacyIntroMusicPeace": [
				{
					"EraType": "ERA_ANCIENT",
					"DiploScriptId": "AS2D_DIPLO_TOKUGAWA_EARLY_INTRO"
				},
				{
					"EraType": "ERA_CLASSICAL",
					"DiploScriptId": "AS2D_DIPLO_TOKUGAWA_EARLY_INTRO"
				}
			],
			"DiplomacyMusicPeace": [
				{
					"EraType": "ERA_ANCIENT",
					"DiploScriptId": "AS2D_DIPLO_TOKUGAWA_EARLY_LP"
				},
				{
					"EraType": "ERA_CLASSICAL",
					"DiploScriptId": "AS2D_DIPLO_TOKUGAWA_EARLY_LP"
				},
				{
					"EraType": "ERA_MEDIEVAL",
					"DiploScriptId": "AS2D_DIPLO_TOKUGAWA_MIDDLE"
				},
				{
					"EraType": "ERA_RENAISSANCE",
					"DiploScriptId": "AS2D_DIPLO_TOKUGAWA_MIDDLE"
				},
				{
					"EraType": "ERA_INDUSTRIAL",
					"DiploScriptId": "AS2D_DIPLO_TOKUGAWA_LATE"
				},
				{
					"EraType": "ERA_MODERN",
					"DiploScriptId": "AS2D_DIPLO_TOKUGAWA_LATE"
				},
				{
					"EraType": "ERA_FUTURE",
					"DiploScriptId": "AS2D_DIPLO_TOKUGAWA_LATE"
				}
			],
			"DiplomacyIntroMusicWar": "",
			"DiplomacyMusicWar": "",
			"getPeaceWeightRand": "3",
			"getMaxGoldPerTurnTradePercent": "10",
			"getDeclareWarTradeRand": "40",
			"getAttackOddsChangeRand": "8",
			"getLostWarAttitudeChange": "-1",
			"getAtWarAttitudeDivisor": "-5",
			"getAtWarAttitudeChangeLimit": "5",
			"getAtPeaceAttitudeDivisor": "60",
			"getAtPeaceAttitudeChangeLimit": "1",
			"getSameReligionAttitudeChange": "1",
			"getSameReligionAttitudeDivisor": "10",
			"getDifferentReligionAttitudeChange": "-1",
			"getDifferentReligionAttitudeDivisor": "-15",
			"getBonusTradeAttitudeDivisor": "50",
			"getBonusTradeAttitudeChangeLimit": "2",
			"getOpenBordersAttitudeDivisor": "25",
			"getOpenBordersAttitudeChangeLimit": "2",
			"getDefensivePactAttitudeDivisor": "12",
			"getDefensivePactAttitudeChangeLimit": "2",
			"getShareWarAttitudeChange": "1",
			"getShareWarAttitudeDivisor": "8",
			"getFavoriteCivicAttitudeChange": "1",
			"getFavoriteCivicAttitudeDivisor": "10",
			"getDemandTributeAttitudeThreshold": 2,
			"getNoGiveHelpAttitudeThreshold": 2,
			"getPermanentAllianceRefuseAttitudeThreshold": 3,
			"getFreedomAppreciation": "10",
			"iNoWarAttitudeProbFurious": 0,
			"iLoveOfPeace": 0,
			"iFlavorReligion": 0,
			"iFlavorProduction": 0,
			"iFlavorGold": 0,
			"iFlavorCulture": 0,
			"iFlavorGrowth": 0,
			"iFlavorEspionage": 0,
			"iContactRandReligionPressure": 500,
			"iContactDelayReligionPressure": 50,
			"iContactRandCivicPressure": 250,
			"iContactDelayCivicPressure": 50,
			"iContactRandJoinWar": 20,
			"iContactDelayJoinWar": 20,
			"iContactRandStopTrading": 50,
			"iContactDelayStopTrading": 20,
			"iContactRandGiveHelp": 0,
			"iContactDelayGiveHelp": 50,
			"iContactRandAskForHelp": 1000,
			"iContactDelayAskForHelp": 50,
			"iContactRandDemandTribute": 1000,
			"iContactDelayDemandTribute": 50,
			"iContactRandTradeTech": 20,
			"iContactDelayTradeTech": 30,
			"iContactRandTradeBonus": 16,
			"iContactDelayTradeBonus": 20,
			"iContactRandPeaceTreaty": 25,
			"iContactDelayPeaceTreaty": 20,
			"iContactRandOpenBorders": 10,
			"iContactDelayOpenBorders": 40,
			"iContactRandDefensivePact": 80,
			"iContactDelayDefensivePact": 20,
			"iContactRandPermanentAlliance": 80,
			"iContactDelayPermanentAlliance": 20,
			"iContactRandTradeMap": 20,
			"iContactDelayTradeMap": 50,
			"iAggregatedContactProbReligionPressure": 52,
			"iAggregatedContactProbCivicPressure": 81,
			"iAggregatedContactProbJoinWar": 0,
			"iAggregatedContactProbStopTrading": 50,
			"iAggregatedContactProbGiveHelp": 0,
			"iAggregatedContactProbAskForHelp": 0,
			"iAggregatedContactProbDemandTribute": 11,
			"iAggregatedContactProbTradeTech": 0,
			"iAggregatedContactProbTradeBonus": 0,
			"iAggregatedContactProbPeaceTreaty": 0,
			"iAggregatedContactProbOpenBorders": 50,
			"iAggregatedContactProbDefensivePact": 50,
			"iAggregatedContactProbPermanentAlliance": 50,
			"iAggregatedContactProbTradeMap": 50,
			"iMemoryAttitudePercentGiveHelp": 100,
			"iMemoryDecayGiveHelp": 150,
			"iMemoryAttitudePercentAcceptDemand": 100,
			"iMemoryDecayAcceptDemand": 30,
			"iMemoryAttitudePercentAcceptedReligion": 100,
			"iMemoryDecayAcceptedReligion": 100,
			"iMemoryAttitudePercentAcceptedCivic": 100,
			"iMemoryDecayAcceptedCivic": 100,
			"iMemoryAttitudePercentAcceptedJoinWar": 100,
			"iMemoryDecayAcceptedJoinWar": 100,
			"iMemoryAttitudePercentAcceptedStopTrading": 50,
			"iMemoryDecayAcceptedStopTrading": 50,
			"iMemoryAttitudePercentTradedTechToUs": 5,
			"iMemoryDecayTradedTechToUs": 25,
			"iMemoryAttitudePercentVotedForUs": 200,
			"iMemoryDecayVotedForUs": 10,
			"iMemoryAttitudePercentEventGoodToUs": 100,
			"iMemoryDecayEventGoodToUs": 50,
			"iMemoryAttitudePercentLiberatedCities": 150,
			"iMemoryDecayLiberatedCities": 150,
			"iMemoryAttitudePercentIndependence": 100,
			"iMemoryDecayIndependence": 30,
			"iAggregatedPositiveMemoryGiveHelpAffection": 50,
			"iAggregatedPositiveMemoryAcceptDemandAffection": 50,
			"iAggregatedPositiveMemoryAcceptedReligionAffection": 50,
			"iAggregatedPositiveMemoryAcceptedCivicAffection": 50,
			"iAggregatedPositiveMemoryAcceptedJoinWarAffection": 50,
			"iAggregatedPositiveMemoryAcceptedStopTradingAffection": 50,
			"iAggregatedPositiveMemoryTradedTechToUsAffection": 0,
			"iAggregatedPositiveMemoryVotedForUsAffection": 50,
			"iAggregatedPositiveMemoryEventGoodToUsAffection": 50,
			"iAggregatedPositiveMemoryLiberatedCitiesAffection": 50,
			"iAggregatedPositiveMemoryIndependenceAffection": 50,
			"iAggregatedPositiveMemoryGiveHelpResentment": 50,
			"iAggregatedPositiveMemoryAcceptDemandResentment": 50,
			"iAggregatedPositiveMemoryAcceptedReligionResentment": 50,
			"iAggregatedPositiveMemoryAcceptedCivicResentment": 50,
			"iAggregatedPositiveMemoryAcceptedJoinWarResentment": 50,
			"iAggregatedPositiveMemoryAcceptedStopTradingResentment": 50,
			"iAggregatedPositiveMemoryTradedTechToUsResentment": 50,
			"iAggregatedPositiveMemoryVotedForUsResentment": 50,
			"iAggregatedPositiveMemoryEventGoodToUsResentment": 50,
			"iAggregatedPositiveMemoryLiberatedCitiesResentment": 50,
			"iAggregatedPositiveMemoryIndependenceResentment": 50,
			"iMemoryAttitudePercentDeclaredWar": -300,
			"iMemoryDecayDeclaredWar": 150,
			"iMemoryAttitudePercentDeclaredWarOnFriend": -100,
			"iMemoryDecayDeclaredWarOnFriend": 120,
			"iMemoryAttitudePercentHiredWarAlly": -200,
			"iMemoryDecayHiredWarAlly": 75,
			"iMemoryAttitudePercentNukedUs": -200,
			"iMemoryDecayNukedUs": 120,
			"iMemoryAttitudePercentNukedFriend": -100,
			"iMemoryDecayNukedFriend": 80,
			"iMemoryAttitudePercentRazedCity": -250,
			"iMemoryDecayRazedCity": 75,
			"iMemoryAttitudePercentRazedHolyCity": -200,
			"iMemoryDecayRazedHolyCity": 150,
			"iMemoryAttitudePercentSpyCaught": -100,
			"iMemoryDecaySpyCaught": 40,
			"iMemoryAttitudePercentRefusedHelp": -200,
			"iMemoryDecayRefusedHelp": 100,
			"iMemoryAttitudePercentRejectedDemand": -200,
			"iMemoryDecayRejectedDemand": 90,
			"iMemoryAttitudePercentDeniedReligion": -200,
			"iMemoryDecayDeniedReligion": 50,
			"iMemoryAttitudePercentDeniedCivic": -200,
			"iMemoryDecayDeniedCivic": 50,
			"iMemoryAttitudePercentDeniedJoinWar": -200,
			"iMemoryDecayDeniedJoinWar": 100,
			"iMemoryAttitudePercentDeniedStopTrading": -200,
			"iMemoryDecayDeniedStopTrading": 50,
			"iMemoryAttitudePercentStoppedTrading": -100,
			"iMemoryDecayStoppedTrading": 60,
			"iMemoryAttitudePercentStoppedTradingRecent": 0,
			"iMemoryDecayStoppedTradingRecent": 18,
			"iMemoryAttitudePercentHiredTradeEmbargo": -100,
			"iMemoryDecayHiredTradeEmbargo": 60,
			"iMemoryAttitudePercentMadeDemand": -150,
			"iMemoryDecayMadeDemand": 30,
			"iMemoryAttitudePercentCancelledVassalAgreement": 0,
			"iMemoryDecayCancelledVassalAgreement": 10,
			"iMemoryAttitudePercentMadeDemandRecent": 0,
			"iMemoryDecayMadeDemandRecent": 20,
			"iMemoryAttitudePercentCancelledOpenBorders": 0,
			"iMemoryDecayCancelledOpenBorders": 10,
			"iMemoryAttitudePercentCancelledDefensivePact": 0,
			"iMemoryDecayCancelledDefensivePact": 10,
			"iMemoryAttitudePercentReceivedTechFromAny": 0,
			"iMemoryDecayReceivedTechFromAny": 20,
			"iMemoryAttitudePercentVotedAgainstUs": -200,
			"iMemoryDecayVotedAgainstUs": 10,
			"iMemoryAttitudePercentEventBadToUs": -100,
			"iMemoryDecayEventBadToUs": 50,
			"iMemoryAttitudePercentDeclaredWarRecent": 0,
			"iMemoryDecayDeclaredWarRecent": 11,
			"iAggregatedNegativeMemoryDeclaredWarAffection": 50,
			"iAggregatedNegativeMemoryDeclaredWarOnFriendAffection": 50,
			"iAggregatedNegativeMemoryHiredWarAllyAffection": 50,
			"iAggregatedNegativeMemoryNukedUsAffection": 50,
			"iAggregatedNegativeMemoryNukedFriendAffection": 50,
			"iAggregatedNegativeMemoryRazedCityAffection": 50,
			"iAggregatedNegativeMemoryRazedHolyCityAffection": 50,
			"iAggregatedNegativeMemorySpyCaughtAffection": 50,
			"iAggregatedNegativeMemoryRefusedHelpAffection": 50,
			"iAggregatedNegativeMemoryRejectedDemandAffection": 50,
			"iAggregatedNegativeMemoryDeniedReligionAffection": 50,
			"iAggregatedNegativeMemoryDeniedCivicAffection": 50,
			"iAggregatedNegativeMemoryDeniedJoinWarAffection": 50,
			"iAggregatedNegativeMemoryDeniedStopTradingAffection": 50,
			"iAggregatedNegativeMemoryStoppedTradingAffection": 50,
			"iAggregatedNegativeMemoryStoppedTradingRecentAffection": 50,
			"iAggregatedNegativeMemoryHiredTradeEmbargoAffection": 50,
			"iAggregatedNegativeMemoryMadeDemandAffection": 50,
			"iAggregatedNegativeMemoryCancelledVassalAgreementAffection": 50,
			"iAggregatedNegativeMemoryMadeDemandRecentAffection": 50,
			"iAggregatedNegativeMemoryCancelledOpenBordersAffection": 50,
			"iAggregatedNegativeMemoryCancelledDefensivePactAffection": 50,
			"iAggregatedNegativeMemoryReceivedTechFromAnyAffection": 50,
			"iAggregatedNegativeMemoryVotedAgainstUsAffection": 50,
			"iAggregatedNegativeMemoryEventBadToUsAffection": 50,
			"iAggregatedNegativeMemoryDeclaredWarRecentAffection": 50,
			"iAggregatedNegativeMemoryDeclaredWarResentment": 50,
			"iAggregatedNegativeMemoryDeclaredWarOnFriendResentment": 0,
			"iAggregatedNegativeMemoryHiredWarAllyResentment": 50,
			"iAggregatedNegativeMemoryNukedUsResentment": 50,
			"iAggregatedNegativeMemoryNukedFriendResentment": 0,
			"iAggregatedNegativeMemoryRazedCityResentment": 50,
			"iAggregatedNegativeMemoryRazedHolyCityResentment": 50,
			"iAggregatedNegativeMemorySpyCaughtResentment": 0,
			"iAggregatedNegativeMemoryRefusedHelpResentment": 100,
			"iAggregatedNegativeMemoryRejectedDemandResentment": 100,
			"iAggregatedNegativeMemoryDeniedReligionResentment": 100,
			"iAggregatedNegativeMemoryDeniedCivicResentment": 100,
			"iAggregatedNegativeMemoryDeniedJoinWarResentment": 100,
			"iAggregatedNegativeMemoryDeniedStopTradingResentment": 100,
			"iAggregatedNegativeMemoryStoppedTradingResentment": 100,
			"iAggregatedNegativeMemoryStoppedTradingRecentResentment": 50,
			"iAggregatedNegativeMemoryHiredTradeEmbargoResentment": 50,
			"iAggregatedNegativeMemoryMadeDemandResentment": 50,
			"iAggregatedNegativeMemoryCancelledVassalAgreementResentment": 50,
			"iAggregatedNegativeMemoryMadeDemandRecentResentment": 50,
			"iAggregatedNegativeMemoryCancelledOpenBordersResentment": 50,
			"iAggregatedNegativeMemoryCancelledDefensivePactResentment": 50,
			"iAggregatedNegativeMemoryReceivedTechFromAnyResentment": 50,
			"iAggregatedNegativeMemoryVotedAgainstUsResentment": 100,
			"iAggregatedNegativeMemoryEventBadToUsResentment": 50,
			"iAggregatedNegativeMemoryDeclaredWarRecentResentment": 50
		},
    }
