# <!-- custom: --- Test data module of expected parsed leaders_data py output to test against the real parsed leaders data py file during its creation --> --- 
# (c) 2025 wonderingabout & becomingthrough

def get_expected_output_PARSED_XML_LEADERS_DATA_SAMPLE():
	return {
		"LEADER_BARBARIAN": {
			"Type": "LEADER_BARBARIAN",
			"Description": "TXT_KEY_LEADER_BARBARIAN",
			"Civilopedia": "TXT_KEY_LEADER_BARBARIAN_PEDIA",
			"ArtDefineTag": "ART_DEF_LEADER_BARBARIAN",
			"iWonderConstructRand": 0,
			"iBaseAttitude": 0,
			"iBasePeaceWeight": 0,
			"iPeaceWeightRand": 0,
			"iWarmongerRespect": 0,
			"iEspionageWeight": 0,
			"iRefuseToTalkWarThreshold": 0,
			"iNoTechTradeThreshold": 0,
			"iTechTradeKnownPercent": 0,
			"iMaxGoldTradePercent": 0,
			"iMaxGoldPerTurnTradePercent": 0,
			"iCultureVictoryWeight": 0,
			"iSpaceVictoryWeight": 0,
			"iConquestVictoryWeight": 70,
			"iDominationVictoryWeight": 30,
			"iDiplomacyVictoryWeight": 0,
			"iMaxWarRand": 0,
			"iMaxWarNearbyPowerRatio": 0,
			"iMaxWarDistantPowerRatio": 0,
			"iMaxWarMinAdjacentLandPercent": 0,
			"iLimitedWarRand": 0,
			"iLimitedWarPowerRatio": 0,
			"iDogpileWarRand": 0,
			"iMakePeaceRand": 0,
			"iDeclareWarTradeRand": 0,
			"iDemandRebukedSneakProb": 0,
			"iDemandRebukedWarProb": 0,
			"iRazeCityProb": 75,
			"iBuildUnitProb": 70,
			"iBaseAttackOddsChange": 1,
			"iAttackOddsChangeRand": 16,
			"iWorseRankDifferenceAttitudeChange": -2,
			"iBetterRankDifferenceAttitudeChange": 0,
			"iCloseBordersAttitudeChange": -2,
			"iLostWarAttitudeChange": 0,
			"iAtWarAttitudeDivisor": 0,
			"iAtWarAttitudeChangeLimit": 0,
			"iAtPeaceAttitudeDivisor": 0,
			"iAtPeaceAttitudeChangeLimit": 0,
			"iSameReligionAttitudeChange": 0,
			"iSameReligionAttitudeDivisor": 0,
			"iSameReligionAttitudeChangeLimit": 0,
			"iDifferentReligionAttitudeChange": 0,
			"iDifferentReligionAttitudeDivisor": 0,
			"iDifferentReligionAttitudeChangeLimit": 0,
			"iBonusTradeAttitudeDivisor": 0,
			"iBonusTradeAttitudeChangeLimit": 0,
			"iOpenBordersAttitudeDivisor": 0,
			"iOpenBordersAttitudeChangeLimit": 0,
			"iDefensivePactAttitudeDivisor": 0,
			"iDefensivePactAttitudeChangeLimit": 0,
			"iShareWarAttitudeChange": 0,
			"iShareWarAttitudeDivisor": 0,
			"iShareWarAttitudeChangeLimit": 0,
			"iFavoriteCivicAttitudeChange": 0,
			"iFavoriteCivicAttitudeDivisor": 0,
			"iFavoriteCivicAttitudeChangeLimit": 0,
			"iDemandTributeAttitudeThreshold": -1,
			"iNoGiveHelpAttitudeThreshold": -1,
			"iTechRefuseAttitudeThreshold": -1,
			"iCityRefuseAttitudeThreshold": -1,
			"iNativeCityRefuseAttitudeThreshold": -1,
			"iStrategicBonusRefuseAttitudeThreshold": -1,
			"iHappinessBonusRefuseAttitudeThreshold": -1,
			"iHealthBonusRefuseAttitudeThreshold": -1,
			"iMapRefuseAttitudeThreshold": -1,
			"iDeclareWarRefuseAttitudeThreshold": -1,
			"iDeclareWarThemRefuseAttitudeThreshold": -1,
			"iStopTradingRefuseAttitudeThreshold": -1,
			"iStopTradingThemRefuseAttitudeThreshold": -1,
			"iAdoptCivicRefuseAttitudeThreshold": -1,
			"iConvertReligionRefuseAttitudeThreshold": -1,
			"iOpenBordersRefuseAttitudeThreshold": -1,
			"iDefensivePactRefuseAttitudeThreshold": -1,
			"iPermanentAllianceRefuseAttitudeThreshold": -1,
			"iVassalRefuseAttitudeThreshold": -1,
			"iVassalPowerModifier": 0,
			"iFreedomAppreciation": 0,
			"FavoriteCivic": "NONE",
			"FavoriteReligion": "NONE",
			"Traits": "",
			"iFlavorMilitary": 10,
			"UnitAIWeightModifiers": [
				{
					"UnitAIType": "UNITAI_RESERVE",
					"iWeightModifier": "75"
				},
				{
					"UnitAIType": "UNITAI_ATTACK_CITY",
					"iWeightModifier": "75"
				},
				{
					"UnitAIType": "UNITAI_WORKER",
					"iWeightModifier": "75"
				}
			],
			"ImprovementWeightModifiers": "",
			"DiplomacyIntroMusicPeace": "",
			"DiplomacyMusicPeace": [
				{
					"EraType": "ERA_ANCIENT",
					"DiploScriptId": "AS2D_DIPLO_RAGNAR_EARLY"
				},
				{
					"EraType": "ERA_CLASSICAL",
					"DiploScriptId": "AS2D_DIPLO_RAGNAR_EARLY"
				},
				{
					"EraType": "ERA_MEDIEVAL",
					"DiploScriptId": "AS2D_DIPLO_RAGNAR_MIDDLE"
				},
				{
					"EraType": "ERA_RENAISSANCE",
					"DiploScriptId": "AS2D_DIPLO_RAGNAR_MIDDLE"
				},
				{
					"EraType": "ERA_INDUSTRIAL",
					"DiploScriptId": "AS2D_DIPLO_RAGNAR_LATE"
				},
				{
					"EraType": "ERA_MODERN",
					"DiploScriptId": "AS2D_DIPLO_RAGNAR_LATE"
				},
				{
					"EraType": "ERA_FUTURE",
					"DiploScriptId": "AS2D_DIPLO_RAGNAR_LATE"
				}
			],
			"DiplomacyIntroMusicWar": "",
			"DiplomacyMusicWar": [
				{
					"EraType": "ERA_ANCIENT",
					"DiploScriptId": "AS2D_DIPLO_WARDRUMS_EARLY"
				},
				{
					"EraType": "ERA_CLASSICAL",
					"DiploScriptId": "AS2D_DIPLO_WARDRUMS_EARLY"
				},
				{
					"EraType": "ERA_MEDIEVAL",
					"DiploScriptId": "AS2D_DIPLO_WARDRUMS_MIDDLE"
				},
				{
					"EraType": "ERA_RENAISSANCE",
					"DiploScriptId": "AS2D_DIPLO_WARDRUMS_MIDDLE"
				},
				{
					"EraType": "ERA_INDUSTRIAL",
					"DiploScriptId": "AS2D_DIPLO_WARDRUMS_LATE"
				},
				{
					"EraType": "ERA_MODERN",
					"DiploScriptId": "AS2D_DIPLO_WARDRUMS_LATE"
				},
				{
					"EraType": "ERA_FUTURE",
					"DiploScriptId": "AS2D_DIPLO_WARDRUMS_LATE"
				}
			],
			"iNoWarAttitudeProbFurious": 0,
			"iNoWarAttitudeProbAnnoyed": 0,
			"iNoWarAttitudeProbCautious": 0,
			"iNoWarAttitudeProbPleased": 0,
			"iNoWarAttitudeProbFriendly": 100,
			"iLoveOfPeace": 0,
			"iFlavorReligion": 0,
			"iFlavorProduction": 0,
			"iFlavorGold": 0,
			"iFlavorScience": 0,
			"iFlavorCulture": 0,
			"iFlavorGrowth": 0,
			"iFlavorEspionage": 0,
			"iContactRandReligionPressure": -1,
			"iContactDelayReligionPressure": 50,
			"iContactRandCivicPressure": -1,
			"iContactDelayCivicPressure": 50,
			"iContactRandJoinWar": -1,
			"iContactDelayJoinWar": 20,
			"iContactRandStopTrading": -1,
			"iContactDelayStopTrading": 20,
			"iContactRandGiveHelp": -1,
			"iContactDelayGiveHelp": 50,
			"iContactRandAskForHelp": -1,
			"iContactDelayAskForHelp": 50,
			"iContactRandDemandTribute": -1,
			"iContactDelayDemandTribute": 50,
			"iContactRandTradeTech": -1,
			"iContactDelayTradeTech": 30,
			"iContactRandTradeBonus": -1,
			"iContactDelayTradeBonus": 20,
			"iContactRandPeaceTreaty": -1,
			"iContactDelayPeaceTreaty": -1,
			"iContactRandOpenBorders": 10,
			"iContactDelayOpenBorders": 40,
			"iContactRandDefensivePact": 80,
			"iContactDelayDefensivePact": 20,
			"iContactRandPermanentAlliance": 80,
			"iContactDelayPermanentAlliance": 20,
			"iContactRandTradeMap": 20,
			"iContactDelayTradeMap": 50,
			"iAggregatedContactProbReligionPressure": -999,
			"iAggregatedContactProbCivicPressure": -999,
			"iAggregatedContactProbJoinWar": -999,
			"iAggregatedContactProbStopTrading": -999,
			"iAggregatedContactProbGiveHelp": -999,
			"iAggregatedContactProbAskForHelp": -999,
			"iAggregatedContactProbDemandTribute": -999,
			"iAggregatedContactProbTradeTech": -999,
			"iAggregatedContactProbTradeBonus": -999,
			"iAggregatedContactProbPeaceTreaty": -999,
			"iAggregatedContactProbOpenBorders": -999,
			"iAggregatedContactProbDefensivePact": -999,
			"iAggregatedContactProbPermanentAlliance": -999,
			"iAggregatedContactProbTradeMap": -999,
			"iMemoryAttitudePercentGiveHelp": 100,
			"iMemoryDecayGiveHelp": 150,
			"iMemoryAttitudePercentAcceptDemand": 100,
			"iMemoryDecayAcceptDemand": 30,
			"iMemoryAttitudePercentAcceptedReligion": 100,
			"iMemoryDecayAcceptedReligion": 100,
			"iMemoryAttitudePercentAcceptedCivic": 100,
			"iMemoryDecayAcceptedCivic": 100,
			"iMemoryAttitudePercentAcceptedJoinWar": 100,
			"iMemoryDecayAcceptedJoinWar": 100,
			"iMemoryAttitudePercentAcceptedStopTrading": 50,
			"iMemoryDecayAcceptedStopTrading": 50,
			"iMemoryAttitudePercentTradedTechToUs": -1,
			"iMemoryDecayTradedTechToUs": 25,
			"iMemoryAttitudePercentVotedForUs": 200,
			"iMemoryDecayVotedForUs": 10,
			"iMemoryAttitudePercentEventGoodToUs": 100,
			"iMemoryDecayEventGoodToUs": 50,
			"iMemoryAttitudePercentLiberatedCities": 150,
			"iMemoryDecayLiberatedCities": 150,
			"iMemoryAttitudePercentIndependence": 100,
			"iMemoryDecayIndependence": 30,
			"iAggregatedPositiveMemoryGiveHelpAffection": -999,
			"iAggregatedPositiveMemoryAcceptDemandAffection": -999,
			"iAggregatedPositiveMemoryAcceptedReligionAffection": -999,
			"iAggregatedPositiveMemoryAcceptedCivicAffection": -999,
			"iAggregatedPositiveMemoryAcceptedJoinWarAffection": -999,
			"iAggregatedPositiveMemoryAcceptedStopTradingAffection": -999,
			"iAggregatedPositiveMemoryTradedTechToUsAffection": -999,
			"iAggregatedPositiveMemoryVotedForUsAffection": -999,
			"iAggregatedPositiveMemoryEventGoodToUsAffection": -999,
			"iAggregatedPositiveMemoryLiberatedCitiesAffection": -999,
			"iAggregatedPositiveMemoryIndependenceAffection": -999,
			"iAggregatedPositiveMemoryGiveHelpResentment": -999,
			"iAggregatedPositiveMemoryAcceptDemandResentment": -999,
			"iAggregatedPositiveMemoryAcceptedReligionResentment": -999,
			"iAggregatedPositiveMemoryAcceptedCivicResentment": -999,
			"iAggregatedPositiveMemoryAcceptedJoinWarResentment": -999,
			"iAggregatedPositiveMemoryAcceptedStopTradingResentment": -999,
			"iAggregatedPositiveMemoryTradedTechToUsResentment": -999,
			"iAggregatedPositiveMemoryVotedForUsResentment": -999,
			"iAggregatedPositiveMemoryEventGoodToUsResentment": -999,
			"iAggregatedPositiveMemoryLiberatedCitiesResentment": -999,
			"iAggregatedPositiveMemoryIndependenceResentment": -999,
			"iMemoryAttitudePercentDeclaredWar": -300,
			"iMemoryDecayDeclaredWar": 150,
			"iMemoryAttitudePercentDeclaredWarOnFriend": -100,
			"iMemoryDecayDeclaredWarOnFriend": 120,
			"iMemoryAttitudePercentHiredWarAlly": -200,
			"iMemoryDecayHiredWarAlly": 75,
			"iMemoryAttitudePercentNukedUs": -200,
			"iMemoryDecayNukedUs": 120,
			"iMemoryAttitudePercentNukedFriend": -100,
			"iMemoryDecayNukedFriend": 80,
			"iMemoryAttitudePercentRazedCity": -250,
			"iMemoryDecayRazedCity": 75,
			"iMemoryAttitudePercentRazedHolyCity": -200,
			"iMemoryDecayRazedHolyCity": 150,
			"iMemoryAttitudePercentSpyCaught": -100,
			"iMemoryDecaySpyCaught": 40,
			"iMemoryAttitudePercentRefusedHelp": -100,
			"iMemoryDecayRefusedHelp": 100,
			"iMemoryAttitudePercentRejectedDemand": -100,
			"iMemoryDecayRejectedDemand": 90,
			"iMemoryAttitudePercentDeniedReligion": -100,
			"iMemoryDecayDeniedReligion": 50,
			"iMemoryAttitudePercentDeniedCivic": -100,
			"iMemoryDecayDeniedCivic": 50,
			"iMemoryAttitudePercentDeniedJoinWar": -100,
			"iMemoryDecayDeniedJoinWar": 100,
			"iMemoryAttitudePercentDeniedStopTrading": -100,
			"iMemoryDecayDeniedStopTrading": 50,
			"iMemoryAttitudePercentStoppedTrading": -100,
			"iMemoryDecayStoppedTrading": 60,
			"iMemoryAttitudePercentStoppedTradingRecent": 0,
			"iMemoryDecayStoppedTradingRecent": 18,
			"iMemoryAttitudePercentHiredTradeEmbargo": -100,
			"iMemoryDecayHiredTradeEmbargo": 60,
			"iMemoryAttitudePercentMadeDemand": -100,
			"iMemoryDecayMadeDemand": 30,
			"iMemoryAttitudePercentCancelledVassalAgreement": 0,
			"iMemoryDecayCancelledVassalAgreement": 10,
			"iMemoryAttitudePercentMadeDemandRecent": 0,
			"iMemoryDecayMadeDemandRecent": 20,
			"iMemoryAttitudePercentCancelledOpenBorders": 0,
			"iMemoryDecayCancelledOpenBorders": 10,
			"iMemoryAttitudePercentCancelledDefensivePact": 0,
			"iMemoryDecayCancelledDefensivePact": 10,
			"iMemoryAttitudePercentReceivedTechFromAny": 0,
			"iMemoryDecayReceivedTechFromAny": 20,
			"iMemoryAttitudePercentVotedAgainstUs": -200,
			"iMemoryDecayVotedAgainstUs": 10,
			"iMemoryAttitudePercentEventBadToUs": -100,
			"iMemoryDecayEventBadToUs": 50,
			"iMemoryAttitudePercentDeclaredWarRecent": 0,
			"iMemoryDecayDeclaredWarRecent": 11,
			"iAggregatedNegativeMemoryDeclaredWarAffection": -999,
			"iAggregatedNegativeMemoryDeclaredWarOnFriendAffection": -999,
			"iAggregatedNegativeMemoryHiredWarAllyAffection": -999,
			"iAggregatedNegativeMemoryNukedUsAffection": -999,
			"iAggregatedNegativeMemoryNukedFriendAffection": -999,
			"iAggregatedNegativeMemoryRazedCityAffection": -999,
			"iAggregatedNegativeMemoryRazedHolyCityAffection": -999,
			"iAggregatedNegativeMemorySpyCaughtAffection": -999,
			"iAggregatedNegativeMemoryRefusedHelpAffection": -999,
			"iAggregatedNegativeMemoryRejectedDemandAffection": -999,
			"iAggregatedNegativeMemoryDeniedReligionAffection": -999,
			"iAggregatedNegativeMemoryDeniedCivicAffection": -999,
			"iAggregatedNegativeMemoryDeniedJoinWarAffection": -999,
			"iAggregatedNegativeMemoryDeniedStopTradingAffection": -999,
			"iAggregatedNegativeMemoryStoppedTradingAffection": -999,
			"iAggregatedNegativeMemoryStoppedTradingRecentAffection": -999,
			"iAggregatedNegativeMemoryHiredTradeEmbargoAffection": -999,
			"iAggregatedNegativeMemoryMadeDemandAffection": -999,
			"iAggregatedNegativeMemoryCancelledVassalAgreementAffection": -999,
			"iAggregatedNegativeMemoryMadeDemandRecentAffection": -999,
			"iAggregatedNegativeMemoryCancelledOpenBordersAffection": -999,
			"iAggregatedNegativeMemoryCancelledDefensivePactAffection": -999,
			"iAggregatedNegativeMemoryReceivedTechFromAnyAffection": -999,
			"iAggregatedNegativeMemoryVotedAgainstUsAffection": -999,
			"iAggregatedNegativeMemoryEventBadToUsAffection": -999,
			"iAggregatedNegativeMemoryDeclaredWarRecentAffection": -999,
			"iAggregatedNegativeMemoryDeclaredWarResentment": -999,
			"iAggregatedNegativeMemoryDeclaredWarOnFriendResentment": -999,
			"iAggregatedNegativeMemoryHiredWarAllyResentment": -999,
			"iAggregatedNegativeMemoryNukedUsResentment": -999,
			"iAggregatedNegativeMemoryNukedFriendResentment": -999,
			"iAggregatedNegativeMemoryRazedCityResentment": -999,
			"iAggregatedNegativeMemoryRazedHolyCityResentment": -999,
			"iAggregatedNegativeMemorySpyCaughtResentment": -999,
			"iAggregatedNegativeMemoryRefusedHelpResentment": -999,
			"iAggregatedNegativeMemoryRejectedDemandResentment": -999,
			"iAggregatedNegativeMemoryDeniedReligionResentment": -999,
			"iAggregatedNegativeMemoryDeniedCivicResentment": -999,
			"iAggregatedNegativeMemoryDeniedJoinWarResentment": -999,
			"iAggregatedNegativeMemoryDeniedStopTradingResentment": -999,
			"iAggregatedNegativeMemoryStoppedTradingResentment": -999,
			"iAggregatedNegativeMemoryStoppedTradingRecentResentment": -999,
			"iAggregatedNegativeMemoryHiredTradeEmbargoResentment": -999,
			"iAggregatedNegativeMemoryMadeDemandResentment": -999,
			"iAggregatedNegativeMemoryCancelledVassalAgreementResentment": -999,
			"iAggregatedNegativeMemoryMadeDemandRecentResentment": -999,
			"iAggregatedNegativeMemoryCancelledOpenBordersResentment": -999,
			"iAggregatedNegativeMemoryCancelledDefensivePactResentment": -999,
			"iAggregatedNegativeMemoryReceivedTechFromAnyResentment": -999,
			"iAggregatedNegativeMemoryVotedAgainstUsResentment": -999,
			"iAggregatedNegativeMemoryEventBadToUsResentment": -999,
			"iAggregatedNegativeMemoryDeclaredWarRecentResentment": -999
		},
		"LEADER_DEFAULTS": {
			"Type": "LEADER_DEFAULTS",
			"Description": "",
			"Civilopedia": "",
			"ArtDefineTag": "",
			"iWonderConstructRand": 0,
			"iBaseAttitude": 0,
			"iBasePeaceWeight": 0,
			"iPeaceWeightRand": 3,
			"iWarmongerRespect": 0,
			"iEspionageWeight": 0,
			"iRefuseToTalkWarThreshold": 0,
			"iNoTechTradeThreshold": 0,
			"iTechTradeKnownPercent": 0,
			"iMaxGoldTradePercent": 0,
			"iMaxGoldPerTurnTradePercent": 10,
			"iCultureVictoryWeight": 30,
			"iSpaceVictoryWeight": 30,
			"iConquestVictoryWeight": 30,
			"iDominationVictoryWeight": 30,
			"iDiplomacyVictoryWeight": 30,
			"iMaxWarRand": 0,
			"iMaxWarNearbyPowerRatio": 0,
			"iMaxWarDistantPowerRatio": 0,
			"iMaxWarMinAdjacentLandPercent": 0,
			"iLimitedWarRand": 0,
			"iLimitedWarPowerRatio": 0,
			"iDogpileWarRand": 0,
			"iMakePeaceRand": 0,
			"iDeclareWarTradeRand": 40,
			"iDemandRebukedSneakProb": 0,
			"iDemandRebukedWarProb": 0,
			"iRazeCityProb": 0,
			"iBuildUnitProb": 0,
			"iBaseAttackOddsChange": 0,
			"iAttackOddsChangeRand": 8,
			"iWorseRankDifferenceAttitudeChange": 0,
			"iBetterRankDifferenceAttitudeChange": 0,
			"iCloseBordersAttitudeChange": 0,
			"iLostWarAttitudeChange": -1,
			"iAtWarAttitudeDivisor": -5,
			"iAtWarAttitudeChangeLimit": 5,
			"iAtPeaceAttitudeDivisor": 60,
			"iAtPeaceAttitudeChangeLimit": 1,
			"iSameReligionAttitudeChange": 1,
			"iSameReligionAttitudeDivisor": 10,
			"iSameReligionAttitudeChangeLimit": 0,
			"iDifferentReligionAttitudeChange": -1,
			"iDifferentReligionAttitudeDivisor": -15,
			"iDifferentReligionAttitudeChangeLimit": 0,
			"iBonusTradeAttitudeDivisor": 50,
			"iBonusTradeAttitudeChangeLimit": 2,
			"iOpenBordersAttitudeDivisor": 25,
			"iOpenBordersAttitudeChangeLimit": 2,
			"iDefensivePactAttitudeDivisor": 12,
			"iDefensivePactAttitudeChangeLimit": 2,
			"iShareWarAttitudeChange": 1,
			"iShareWarAttitudeDivisor": 8,
			"iShareWarAttitudeChangeLimit": 0,
			"iFavoriteCivicAttitudeChange": 1,
			"iFavoriteCivicAttitudeDivisor": 10,
			"iFavoriteCivicAttitudeChangeLimit": 0,
			"iDemandTributeAttitudeThreshold": 2,
			"iNoGiveHelpAttitudeThreshold": 2,
			"iTechRefuseAttitudeThreshold": -1,
			"iCityRefuseAttitudeThreshold": 2,
			"iNativeCityRefuseAttitudeThreshold": 3,
			"iStrategicBonusRefuseAttitudeThreshold": -1,
			"iHappinessBonusRefuseAttitudeThreshold": -1,
			"iHealthBonusRefuseAttitudeThreshold": -1,
			"iMapRefuseAttitudeThreshold": -1,
			"iDeclareWarRefuseAttitudeThreshold": -1,
			"iDeclareWarThemRefuseAttitudeThreshold": -1,
			"iStopTradingRefuseAttitudeThreshold": -1,
			"iStopTradingThemRefuseAttitudeThreshold": -1,
			"iAdoptCivicRefuseAttitudeThreshold": -1,
			"iConvertReligionRefuseAttitudeThreshold": -1,
			"iOpenBordersRefuseAttitudeThreshold": -1,
			"iDefensivePactRefuseAttitudeThreshold": 3,
			"iPermanentAllianceRefuseAttitudeThreshold": 3,
			"iVassalRefuseAttitudeThreshold": -1,
			"iVassalPowerModifier": 0,
			"iFreedomAppreciation": 10,
			"FavoriteCivic": "NONE",
			"FavoriteReligion": "NONE",
			"Traits": "",
			"iNoWarAttitudeProbFurious": 0,
			"iNoWarAttitudeProbAnnoyed": 0,
			"iNoWarAttitudeProbCautious": 0,
			"iNoWarAttitudeProbPleased": 0,
			"iNoWarAttitudeProbFriendly": 100,
			"iLoveOfPeace": 0,
			"UnitAIWeightModifiers": "",
			"ImprovementWeightModifiers": "",
			"DiplomacyIntroMusicPeace": [
				{
					"EraType": "ERA_ANCIENT"
				},
				{
					"EraType": "ERA_CLASSICAL"
				},
				{
					"EraType": "ERA_MEDIEVAL"
				},
				{
					"EraType": "ERA_RENAISSANCE"
				},
				{
					"EraType": "ERA_INDUSTRIAL"
				},
				{
					"EraType": "ERA_MODERN"
				},
				{
					"EraType": "ERA_FUTURE"
				}
			],
			"DiplomacyMusicPeace": [
				{
					"EraType": "ERA_ANCIENT"
				},
				{
					"EraType": "ERA_CLASSICAL"
				},
				{
					"EraType": "ERA_MEDIEVAL"
				},
				{
					"EraType": "ERA_RENAISSANCE"
				},
				{
					"EraType": "ERA_INDUSTRIAL"
				},
				{
					"EraType": "ERA_MODERN"
				},
				{
					"EraType": "ERA_FUTURE"
				}
			],
			"DiplomacyIntroMusicWar": [
				{
					"EraType": "ERA_ANCIENT"
				},
				{
					"EraType": "ERA_CLASSICAL"
				},
				{
					"EraType": "ERA_MEDIEVAL"
				},
				{
					"EraType": "ERA_RENAISSANCE"
				},
				{
					"EraType": "ERA_INDUSTRIAL"
				},
				{
					"EraType": "ERA_MODERN"
				},
				{
					"EraType": "ERA_FUTURE"
				}
			],
			"DiplomacyMusicWar": [
				{
					"EraType": "ERA_ANCIENT",
					"DiploScriptId": "AS2D_DIPLO_WARDRUMS_EARLY"
				},
				{
					"EraType": "ERA_CLASSICAL",
					"DiploScriptId": "AS2D_DIPLO_WARDRUMS_EARLY"
				},
				{
					"EraType": "ERA_MEDIEVAL",
					"DiploScriptId": "AS2D_DIPLO_WARDRUMS_MIDDLE"
				},
				{
					"EraType": "ERA_RENAISSANCE",
					"DiploScriptId": "AS2D_DIPLO_WARDRUMS_MIDDLE"
				},
				{
					"EraType": "ERA_INDUSTRIAL",
					"DiploScriptId": "AS2D_DIPLO_WARDRUMS_LATE"
				},
				{
					"EraType": "ERA_MODERN",
					"DiploScriptId": "AS2D_DIPLO_WARDRUMS_LATE"
				},
				{
					"EraType": "ERA_FUTURE",
					"DiploScriptId": "AS2D_DIPLO_WARDRUMS_LATE"
				}
			],
			"iFlavorMilitary": 0,
			"iFlavorReligion": 0,
			"iFlavorProduction": 0,
			"iFlavorGold": 0,
			"iFlavorScience": 0,
			"iFlavorCulture": 0,
			"iFlavorGrowth": 0,
			"iFlavorEspionage": 0,
			"iContactRandReligionPressure": -1,
			"iContactDelayReligionPressure": 50,
			"iContactRandCivicPressure": -1,
			"iContactDelayCivicPressure": 50,
			"iContactRandJoinWar": -1,
			"iContactDelayJoinWar": 20,
			"iContactRandStopTrading": -1,
			"iContactDelayStopTrading": 20,
			"iContactRandGiveHelp": -1,
			"iContactDelayGiveHelp": 50,
			"iContactRandAskForHelp": -1,
			"iContactDelayAskForHelp": 50,
			"iContactRandDemandTribute": -1,
			"iContactDelayDemandTribute": 50,
			"iContactRandTradeTech": -1,
			"iContactDelayTradeTech": 30,
			"iContactRandTradeBonus": -1,
			"iContactDelayTradeBonus": 20,
			"iContactRandPeaceTreaty": -1,
			"iContactDelayPeaceTreaty": -1,
			"iContactRandOpenBorders": 10,
			"iContactDelayOpenBorders": 40,
			"iContactRandDefensivePact": 80,
			"iContactDelayDefensivePact": 20,
			"iContactRandPermanentAlliance": 80,
			"iContactDelayPermanentAlliance": 20,
			"iContactRandTradeMap": 20,
			"iContactDelayTradeMap": 50,
			"iAggregatedContactProbReligionPressure": -999,
			"iAggregatedContactProbCivicPressure": -999,
			"iAggregatedContactProbJoinWar": -999,
			"iAggregatedContactProbStopTrading": -999,
			"iAggregatedContactProbGiveHelp": -999,
			"iAggregatedContactProbAskForHelp": -999,
			"iAggregatedContactProbDemandTribute": -999,
			"iAggregatedContactProbTradeTech": -999,
			"iAggregatedContactProbTradeBonus": -999,
			"iAggregatedContactProbPeaceTreaty": -999,
			"iAggregatedContactProbOpenBorders": -999,
			"iAggregatedContactProbDefensivePact": -999,
			"iAggregatedContactProbPermanentAlliance": -999,
			"iAggregatedContactProbTradeMap": -999,
			"iMemoryAttitudePercentGiveHelp": 100,
			"iMemoryDecayGiveHelp": 150,
			"iMemoryAttitudePercentAcceptDemand": 100,
			"iMemoryDecayAcceptDemand": 30,
			"iMemoryAttitudePercentAcceptedReligion": 100,
			"iMemoryDecayAcceptedReligion": 100,
			"iMemoryAttitudePercentAcceptedCivic": 100,
			"iMemoryDecayAcceptedCivic": 100,
			"iMemoryAttitudePercentAcceptedJoinWar": 100,
			"iMemoryDecayAcceptedJoinWar": 100,
			"iMemoryAttitudePercentAcceptedStopTrading": 50,
			"iMemoryDecayAcceptedStopTrading": 50,
			"iMemoryAttitudePercentTradedTechToUs": -1,
			"iMemoryDecayTradedTechToUs": 25,
			"iMemoryAttitudePercentVotedForUs": 200,
			"iMemoryDecayVotedForUs": 10,
			"iMemoryAttitudePercentEventGoodToUs": 100,
			"iMemoryDecayEventGoodToUs": 50,
			"iMemoryAttitudePercentLiberatedCities": 150,
			"iMemoryDecayLiberatedCities": 150,
			"iMemoryAttitudePercentIndependence": 100,
			"iMemoryDecayIndependence": 30,
			"iAggregatedPositiveMemoryGiveHelpAffection": -999,
			"iAggregatedPositiveMemoryAcceptDemandAffection": -999,
			"iAggregatedPositiveMemoryAcceptedReligionAffection": -999,
			"iAggregatedPositiveMemoryAcceptedCivicAffection": -999,
			"iAggregatedPositiveMemoryAcceptedJoinWarAffection": -999,
			"iAggregatedPositiveMemoryAcceptedStopTradingAffection": -999,
			"iAggregatedPositiveMemoryTradedTechToUsAffection": -999,
			"iAggregatedPositiveMemoryVotedForUsAffection": -999,
			"iAggregatedPositiveMemoryEventGoodToUsAffection": -999,
			"iAggregatedPositiveMemoryLiberatedCitiesAffection": -999,
			"iAggregatedPositiveMemoryIndependenceAffection": -999,
			"iAggregatedPositiveMemoryGiveHelpResentment": -999,
			"iAggregatedPositiveMemoryAcceptDemandResentment": -999,
			"iAggregatedPositiveMemoryAcceptedReligionResentment": -999,
			"iAggregatedPositiveMemoryAcceptedCivicResentment": -999,
			"iAggregatedPositiveMemoryAcceptedJoinWarResentment": -999,
			"iAggregatedPositiveMemoryAcceptedStopTradingResentment": -999,
			"iAggregatedPositiveMemoryTradedTechToUsResentment": -999,
			"iAggregatedPositiveMemoryVotedForUsResentment": -999,
			"iAggregatedPositiveMemoryEventGoodToUsResentment": -999,
			"iAggregatedPositiveMemoryLiberatedCitiesResentment": -999,
			"iAggregatedPositiveMemoryIndependenceResentment": -999,
			"iMemoryAttitudePercentDeclaredWar": -300,
			"iMemoryDecayDeclaredWar": 150,
			"iMemoryAttitudePercentDeclaredWarOnFriend": -100,
			"iMemoryDecayDeclaredWarOnFriend": 120,
			"iMemoryAttitudePercentHiredWarAlly": -200,
			"iMemoryDecayHiredWarAlly": 75,
			"iMemoryAttitudePercentNukedUs": -200,
			"iMemoryDecayNukedUs": 120,
			"iMemoryAttitudePercentNukedFriend": -100,
			"iMemoryDecayNukedFriend": 80,
			"iMemoryAttitudePercentRazedCity": -250,
			"iMemoryDecayRazedCity": 75,
			"iMemoryAttitudePercentRazedHolyCity": -200,
			"iMemoryDecayRazedHolyCity": 150,
			"iMemoryAttitudePercentSpyCaught": -100,
			"iMemoryDecaySpyCaught": 40,
			"iMemoryAttitudePercentRefusedHelp": -100,
			"iMemoryDecayRefusedHelp": 100,
			"iMemoryAttitudePercentRejectedDemand": -100,
			"iMemoryDecayRejectedDemand": 90,
			"iMemoryAttitudePercentDeniedReligion": -100,
			"iMemoryDecayDeniedReligion": 50,
			"iMemoryAttitudePercentDeniedCivic": -100,
			"iMemoryDecayDeniedCivic": 50,
			"iMemoryAttitudePercentDeniedJoinWar": -100,
			"iMemoryDecayDeniedJoinWar": 100,
			"iMemoryAttitudePercentDeniedStopTrading": -100,
			"iMemoryDecayDeniedStopTrading": 50,
			"iMemoryAttitudePercentStoppedTrading": -100,
			"iMemoryDecayStoppedTrading": 60,
			"iMemoryAttitudePercentStoppedTradingRecent": 0,
			"iMemoryDecayStoppedTradingRecent": 18,
			"iMemoryAttitudePercentHiredTradeEmbargo": -100,
			"iMemoryDecayHiredTradeEmbargo": 60,
			"iMemoryAttitudePercentMadeDemand": -100,
			"iMemoryDecayMadeDemand": 30,
			"iMemoryAttitudePercentCancelledVassalAgreement": 0,
			"iMemoryDecayCancelledVassalAgreement": 10,
			"iMemoryAttitudePercentMadeDemandRecent": 0,
			"iMemoryDecayMadeDemandRecent": 20,
			"iMemoryAttitudePercentCancelledOpenBorders": 0,
			"iMemoryDecayCancelledOpenBorders": 10,
			"iMemoryAttitudePercentCancelledDefensivePact": 0,
			"iMemoryDecayCancelledDefensivePact": 10,
			"iMemoryAttitudePercentReceivedTechFromAny": 0,
			"iMemoryDecayReceivedTechFromAny": 20,
			"iMemoryAttitudePercentVotedAgainstUs": -200,
			"iMemoryDecayVotedAgainstUs": 10,
			"iMemoryAttitudePercentEventBadToUs": -100,
			"iMemoryDecayEventBadToUs": 50,
			"iMemoryAttitudePercentDeclaredWarRecent": 0,
			"iMemoryDecayDeclaredWarRecent": 11,
			"iAggregatedNegativeMemoryDeclaredWarAffection": -999,
			"iAggregatedNegativeMemoryDeclaredWarOnFriendAffection": -999,
			"iAggregatedNegativeMemoryHiredWarAllyAffection": -999,
			"iAggregatedNegativeMemoryNukedUsAffection": -999,
			"iAggregatedNegativeMemoryNukedFriendAffection": -999,
			"iAggregatedNegativeMemoryRazedCityAffection": -999,
			"iAggregatedNegativeMemoryRazedHolyCityAffection": -999,
			"iAggregatedNegativeMemorySpyCaughtAffection": -999,
			"iAggregatedNegativeMemoryRefusedHelpAffection": -999,
			"iAggregatedNegativeMemoryRejectedDemandAffection": -999,
			"iAggregatedNegativeMemoryDeniedReligionAffection": -999,
			"iAggregatedNegativeMemoryDeniedCivicAffection": -999,
			"iAggregatedNegativeMemoryDeniedJoinWarAffection": -999,
			"iAggregatedNegativeMemoryDeniedStopTradingAffection": -999,
			"iAggregatedNegativeMemoryStoppedTradingAffection": -999,
			"iAggregatedNegativeMemoryStoppedTradingRecentAffection": -999,
			"iAggregatedNegativeMemoryHiredTradeEmbargoAffection": -999,
			"iAggregatedNegativeMemoryMadeDemandAffection": -999,
			"iAggregatedNegativeMemoryCancelledVassalAgreementAffection": -999,
			"iAggregatedNegativeMemoryMadeDemandRecentAffection": -999,
			"iAggregatedNegativeMemoryCancelledOpenBordersAffection": -999,
			"iAggregatedNegativeMemoryCancelledDefensivePactAffection": -999,
			"iAggregatedNegativeMemoryReceivedTechFromAnyAffection": -999,
			"iAggregatedNegativeMemoryVotedAgainstUsAffection": -999,
			"iAggregatedNegativeMemoryEventBadToUsAffection": -999,
			"iAggregatedNegativeMemoryDeclaredWarRecentAffection": -999,
			"iAggregatedNegativeMemoryDeclaredWarResentment": -999,
			"iAggregatedNegativeMemoryDeclaredWarOnFriendResentment": -999,
			"iAggregatedNegativeMemoryHiredWarAllyResentment": -999,
			"iAggregatedNegativeMemoryNukedUsResentment": -999,
			"iAggregatedNegativeMemoryNukedFriendResentment": -999,
			"iAggregatedNegativeMemoryRazedCityResentment": -999,
			"iAggregatedNegativeMemoryRazedHolyCityResentment": -999,
			"iAggregatedNegativeMemorySpyCaughtResentment": -999,
			"iAggregatedNegativeMemoryRefusedHelpResentment": -999,
			"iAggregatedNegativeMemoryRejectedDemandResentment": -999,
			"iAggregatedNegativeMemoryDeniedReligionResentment": -999,
			"iAggregatedNegativeMemoryDeniedCivicResentment": -999,
			"iAggregatedNegativeMemoryDeniedJoinWarResentment": -999,
			"iAggregatedNegativeMemoryDeniedStopTradingResentment": -999,
			"iAggregatedNegativeMemoryStoppedTradingResentment": -999,
			"iAggregatedNegativeMemoryStoppedTradingRecentResentment": -999,
			"iAggregatedNegativeMemoryHiredTradeEmbargoResentment": -999,
			"iAggregatedNegativeMemoryMadeDemandResentment": -999,
			"iAggregatedNegativeMemoryCancelledVassalAgreementResentment": -999,
			"iAggregatedNegativeMemoryMadeDemandRecentResentment": -999,
			"iAggregatedNegativeMemoryCancelledOpenBordersResentment": -999,
			"iAggregatedNegativeMemoryCancelledDefensivePactResentment": -999,
			"iAggregatedNegativeMemoryReceivedTechFromAnyResentment": -999,
			"iAggregatedNegativeMemoryVotedAgainstUsResentment": -999,
			"iAggregatedNegativeMemoryEventBadToUsResentment": -999,
			"iAggregatedNegativeMemoryDeclaredWarRecentResentment": -999
		},
		"LEADER_ALEXANDER": {
			"Type": "LEADER_ALEXANDER",
			"Description": "TXT_KEY_LEADER_ALEXANDER",
			"Civilopedia": "TXT_KEY_LEADER_ALEXANDER_PEDIA",
			"ArtDefineTag": "ART_DEF_LEADER_ALEXANDER",
			"iWonderConstructRand": 20,
			"iBaseAttitude": 0,
			"iBasePeaceWeight": 0,
			"iWarmongerRespect": 2,
			"iEspionageWeight": 100,
			"iRefuseToTalkWarThreshold": 8,
			"iNoTechTradeThreshold": 5,
			"iTechTradeKnownPercent": 30,
			"iMaxGoldTradePercent": 5,
			"iCultureVictoryWeight": 25,
			"iSpaceVictoryWeight": 25,
			"iConquestVictoryWeight": 35,
			"iDominationVictoryWeight": 65,
			"iDiplomacyVictoryWeight": 0,
			"iMaxWarRand": 50,
			"iMaxWarNearbyPowerRatio": 90,
			"iMaxWarDistantPowerRatio": 70,
			"iMaxWarMinAdjacentLandPercent": 0,
			"iLimitedWarRand": 40,
			"iLimitedWarPowerRatio": 130,
			"iDogpileWarRand": 50,
			"iMakePeaceRand": 40,
			"iDemandRebukedSneakProb": 40,
			"iDemandRebukedWarProb": 25,
			"iRazeCityProb": 0,
			"iBuildUnitProb": 35,
			"iBaseAttackOddsChange": 4,
			"iWorseRankDifferenceAttitudeChange": -2,
			"iBetterRankDifferenceAttitudeChange": 0,
			"iCloseBordersAttitudeChange": -4,
			"iSameReligionAttitudeChangeLimit": 4,
			"iDifferentReligionAttitudeChangeLimit": -1,
			"iShareWarAttitudeChangeLimit": 4,
			"iFavoriteCivicAttitudeChangeLimit": 2,
			"iTechRefuseAttitudeThreshold": 1,
			"iCityRefuseAttitudeThreshold": 2,
			"iNativeCityRefuseAttitudeThreshold": 3,
			"iStrategicBonusRefuseAttitudeThreshold": 2,
			"iHappinessBonusRefuseAttitudeThreshold": 1,
			"iHealthBonusRefuseAttitudeThreshold": 1,
			"iMapRefuseAttitudeThreshold": 3,
			"iDeclareWarRefuseAttitudeThreshold": 1,
			"iDeclareWarThemRefuseAttitudeThreshold": 3,
			"iStopTradingRefuseAttitudeThreshold": 2,
			"iStopTradingThemRefuseAttitudeThreshold": 2,
			"iAdoptCivicRefuseAttitudeThreshold": 3,
			"iConvertReligionRefuseAttitudeThreshold": 2,
			"iOpenBordersRefuseAttitudeThreshold": 1,
			"iVassalRefuseAttitudeThreshold": 3,
			"iVassalPowerModifier": 20,
			"FavoriteCivic": "CIVIC_VASSALAGE",
			"FavoriteReligion": "RELIGION_PAGANISM",
			"Traits": [
				{
					"TraitType": "TRAIT_PHILOSOPHICAL",
					"bTrait": "1"
				},
				{
					"TraitType": "TRAIT_AGGRESSIVE",
					"bTrait": "1"
				}
			],
			"iFlavorMilitary": 5,
			"iFlavorGrowth": 2,
			"iNoWarAttitudeProbCautious": 20,
			"iNoWarAttitudeProbPleased": 80,
			"iNoWarAttitudeProbFriendly": 80,
			"UnitAIWeightModifiers": [
				{
					"UnitAIType": "UNITAI_SETTLE",
					"iWeightModifier": "25"
				},
				{
					"UnitAIType": "UNITAI_COLLATERAL",
					"iWeightModifier": "25"
				}
			],
			"ImprovementWeightModifiers": [
				{
					"ImprovementType": "IMPROVEMENT_MINE",
					"iWeightModifier": "30"
				}
			],
			"DiplomacyIntroMusicPeace": "",
			"DiplomacyMusicPeace": [
				{
					"EraType": "ERA_ANCIENT",
					"DiploScriptId": "AS2D_DIPLO_ALEXANDER_EARLY"
				},
				{
					"EraType": "ERA_CLASSICAL",
					"DiploScriptId": "AS2D_DIPLO_ALEXANDER_EARLY"
				},
				{
					"EraType": "ERA_MEDIEVAL",
					"DiploScriptId": "AS2D_DIPLO_ALEXANDER_MIDDLE"
				},
				{
					"EraType": "ERA_RENAISSANCE",
					"DiploScriptId": "AS2D_DIPLO_ALEXANDER_MIDDLE"
				},
				{
					"EraType": "ERA_INDUSTRIAL",
					"DiploScriptId": "AS2D_DIPLO_ALEXANDER_LATE"
				},
				{
					"EraType": "ERA_MODERN",
					"DiploScriptId": "AS2D_DIPLO_ALEXANDER_LATE"
				},
				{
					"EraType": "ERA_FUTURE",
					"DiploScriptId": "AS2D_DIPLO_ALEXANDER_LATE"
				}
			],
			"DiplomacyIntroMusicWar": "",
			"DiplomacyMusicWar": "",
			"iPeaceWeightRand": 3,
			"iMaxGoldPerTurnTradePercent": 10,
			"iDeclareWarTradeRand": 40,
			"iAttackOddsChangeRand": 8,
			"iLostWarAttitudeChange": -1,
			"iAtWarAttitudeDivisor": -5,
			"iAtWarAttitudeChangeLimit": 5,
			"iAtPeaceAttitudeDivisor": 60,
			"iAtPeaceAttitudeChangeLimit": 1,
			"iSameReligionAttitudeChange": 1,
			"iSameReligionAttitudeDivisor": 10,
			"iDifferentReligionAttitudeChange": -1,
			"iDifferentReligionAttitudeDivisor": -15,
			"iBonusTradeAttitudeDivisor": 50,
			"iBonusTradeAttitudeChangeLimit": 2,
			"iOpenBordersAttitudeDivisor": 25,
			"iOpenBordersAttitudeChangeLimit": 2,
			"iDefensivePactAttitudeDivisor": 12,
			"iDefensivePactAttitudeChangeLimit": 2,
			"iShareWarAttitudeChange": 1,
			"iShareWarAttitudeDivisor": 8,
			"iFavoriteCivicAttitudeChange": 1,
			"iFavoriteCivicAttitudeDivisor": 10,
			"iDemandTributeAttitudeThreshold": 2,
			"iNoGiveHelpAttitudeThreshold": 2,
			"iDefensivePactRefuseAttitudeThreshold": 3,
			"iPermanentAllianceRefuseAttitudeThreshold": 3,
			"iFreedomAppreciation": 10,
			"iNoWarAttitudeProbFurious": 0,
			"iNoWarAttitudeProbAnnoyed": 0,
			"iLoveOfPeace": 0,
			"iFlavorReligion": 0,
			"iFlavorProduction": 0,
			"iFlavorGold": 0,
			"iFlavorScience": 0,
			"iFlavorCulture": 0,
			"iFlavorEspionage": 0,
			"iContactRandReligionPressure": 250,
			"iContactDelayReligionPressure": 50,
			"iContactRandCivicPressure": 1000,
			"iContactDelayCivicPressure": 50,
			"iContactRandJoinWar": 20,
			"iContactDelayJoinWar": 20,
			"iContactRandStopTrading": 50,
			"iContactDelayStopTrading": 20,
			"iContactRandGiveHelp": 500,
			"iContactDelayGiveHelp": 50,
			"iContactRandAskForHelp": 250,
			"iContactDelayAskForHelp": 50,
			"iContactRandDemandTribute": 250,
			"iContactDelayDemandTribute": 50,
			"iContactRandTradeTech": 5,
			"iContactDelayTradeTech": 30,
			"iContactRandTradeBonus": 5,
			"iContactDelayTradeBonus": 20,
			"iContactRandPeaceTreaty": 20,
			"iContactDelayPeaceTreaty": 15,
			"iContactRandOpenBorders": 10,
			"iContactDelayOpenBorders": 40,
			"iContactRandDefensivePact": 80,
			"iContactDelayDefensivePact": 20,
			"iContactRandPermanentAlliance": 80,
			"iContactDelayPermanentAlliance": 20,
			"iContactRandTradeMap": 20,
			"iContactDelayTradeMap": 50,
			"iAggregatedContactProbReligionPressure": 79,
			"iAggregatedContactProbCivicPressure": 12,
			"iAggregatedContactProbJoinWar": 0,
			"iAggregatedContactProbStopTrading": 50,
			"iAggregatedContactProbGiveHelp": 57,
			"iAggregatedContactProbAskForHelp": 78,
			"iAggregatedContactProbDemandTribute": 80,
			"iAggregatedContactProbTradeTech": 79,
			"iAggregatedContactProbTradeBonus": 72,
			"iAggregatedContactProbPeaceTreaty": 35,
			"iAggregatedContactProbOpenBorders": 50,
			"iAggregatedContactProbDefensivePact": 50,
			"iAggregatedContactProbPermanentAlliance": 50,
			"iAggregatedContactProbTradeMap": 50,
			"iMemoryAttitudePercentGiveHelp": 100,
			"iMemoryDecayGiveHelp": 150,
			"iMemoryAttitudePercentAcceptDemand": 100,
			"iMemoryDecayAcceptDemand": 30,
			"iMemoryAttitudePercentAcceptedReligion": 100,
			"iMemoryDecayAcceptedReligion": 100,
			"iMemoryAttitudePercentAcceptedCivic": 100,
			"iMemoryDecayAcceptedCivic": 100,
			"iMemoryAttitudePercentAcceptedJoinWar": 100,
			"iMemoryDecayAcceptedJoinWar": 100,
			"iMemoryAttitudePercentAcceptedStopTrading": 50,
			"iMemoryDecayAcceptedStopTrading": 50,
			"iMemoryAttitudePercentTradedTechToUs": 10,
			"iMemoryDecayTradedTechToUs": 25,
			"iMemoryAttitudePercentVotedForUs": 200,
			"iMemoryDecayVotedForUs": 10,
			"iMemoryAttitudePercentEventGoodToUs": 100,
			"iMemoryDecayEventGoodToUs": 50,
			"iMemoryAttitudePercentLiberatedCities": 150,
			"iMemoryDecayLiberatedCities": 150,
			"iMemoryAttitudePercentIndependence": 100,
			"iMemoryDecayIndependence": 30,
			"iAggregatedPositiveMemoryGiveHelpAffection": 50,
			"iAggregatedPositiveMemoryAcceptDemandAffection": 50,
			"iAggregatedPositiveMemoryAcceptedReligionAffection": 50,
			"iAggregatedPositiveMemoryAcceptedCivicAffection": 50,
			"iAggregatedPositiveMemoryAcceptedJoinWarAffection": 50,
			"iAggregatedPositiveMemoryAcceptedStopTradingAffection": 50,
			"iAggregatedPositiveMemoryTradedTechToUsAffection": 32,
			"iAggregatedPositiveMemoryVotedForUsAffection": 50,
			"iAggregatedPositiveMemoryEventGoodToUsAffection": 50,
			"iAggregatedPositiveMemoryLiberatedCitiesAffection": 50,
			"iAggregatedPositiveMemoryIndependenceAffection": 50,
			"iAggregatedPositiveMemoryGiveHelpResentment": 50,
			"iAggregatedPositiveMemoryAcceptDemandResentment": 50,
			"iAggregatedPositiveMemoryAcceptedReligionResentment": 50,
			"iAggregatedPositiveMemoryAcceptedCivicResentment": 50,
			"iAggregatedPositiveMemoryAcceptedJoinWarResentment": 50,
			"iAggregatedPositiveMemoryAcceptedStopTradingResentment": 50,
			"iAggregatedPositiveMemoryTradedTechToUsResentment": 50,
			"iAggregatedPositiveMemoryVotedForUsResentment": 50,
			"iAggregatedPositiveMemoryEventGoodToUsResentment": 50,
			"iAggregatedPositiveMemoryLiberatedCitiesResentment": 50,
			"iAggregatedPositiveMemoryIndependenceResentment": 50,
			"iMemoryAttitudePercentDeclaredWar": -300,
			"iMemoryDecayDeclaredWar": 150,
			"iMemoryAttitudePercentDeclaredWarOnFriend": -100,
			"iMemoryDecayDeclaredWarOnFriend": 120,
			"iMemoryAttitudePercentHiredWarAlly": -200,
			"iMemoryDecayHiredWarAlly": 75,
			"iMemoryAttitudePercentNukedUs": -200,
			"iMemoryDecayNukedUs": 120,
			"iMemoryAttitudePercentNukedFriend": -100,
			"iMemoryDecayNukedFriend": 80,
			"iMemoryAttitudePercentRazedCity": -250,
			"iMemoryDecayRazedCity": 75,
			"iMemoryAttitudePercentRazedHolyCity": -200,
			"iMemoryDecayRazedHolyCity": 150,
			"iMemoryAttitudePercentSpyCaught": -100,
			"iMemoryDecaySpyCaught": 40,
			"iMemoryAttitudePercentRefusedHelp": -100,
			"iMemoryDecayRefusedHelp": 100,
			"iMemoryAttitudePercentRejectedDemand": -100,
			"iMemoryDecayRejectedDemand": 90,
			"iMemoryAttitudePercentDeniedReligion": -100,
			"iMemoryDecayDeniedReligion": 50,
			"iMemoryAttitudePercentDeniedCivic": -100,
			"iMemoryDecayDeniedCivic": 50,
			"iMemoryAttitudePercentDeniedJoinWar": -100,
			"iMemoryDecayDeniedJoinWar": 100,
			"iMemoryAttitudePercentDeniedStopTrading": -100,
			"iMemoryDecayDeniedStopTrading": 50,
			"iMemoryAttitudePercentStoppedTrading": -100,
			"iMemoryDecayStoppedTrading": 60,
			"iMemoryAttitudePercentStoppedTradingRecent": 0,
			"iMemoryDecayStoppedTradingRecent": 18,
			"iMemoryAttitudePercentHiredTradeEmbargo": -100,
			"iMemoryDecayHiredTradeEmbargo": 60,
			"iMemoryAttitudePercentMadeDemand": -100,
			"iMemoryDecayMadeDemand": 30,
			"iMemoryAttitudePercentCancelledVassalAgreement": 0,
			"iMemoryDecayCancelledVassalAgreement": 10,
			"iMemoryAttitudePercentMadeDemandRecent": 0,
			"iMemoryDecayMadeDemandRecent": 20,
			"iMemoryAttitudePercentCancelledOpenBorders": 0,
			"iMemoryDecayCancelledOpenBorders": 10,
			"iMemoryAttitudePercentCancelledDefensivePact": 0,
			"iMemoryDecayCancelledDefensivePact": 10,
			"iMemoryAttitudePercentReceivedTechFromAny": 0,
			"iMemoryDecayReceivedTechFromAny": 20,
			"iMemoryAttitudePercentVotedAgainstUs": -200,
			"iMemoryDecayVotedAgainstUs": 10,
			"iMemoryAttitudePercentEventBadToUs": -100,
			"iMemoryDecayEventBadToUs": 50,
			"iMemoryAttitudePercentDeclaredWarRecent": 0,
			"iMemoryDecayDeclaredWarRecent": 11,
			"iAggregatedNegativeMemoryDeclaredWarAffection": 50,
			"iAggregatedNegativeMemoryDeclaredWarOnFriendAffection": 50,
			"iAggregatedNegativeMemoryHiredWarAllyAffection": 50,
			"iAggregatedNegativeMemoryNukedUsAffection": 50,
			"iAggregatedNegativeMemoryNukedFriendAffection": 50,
			"iAggregatedNegativeMemoryRazedCityAffection": 50,
			"iAggregatedNegativeMemoryRazedHolyCityAffection": 50,
			"iAggregatedNegativeMemorySpyCaughtAffection": 50,
			"iAggregatedNegativeMemoryRefusedHelpAffection": 50,
			"iAggregatedNegativeMemoryRejectedDemandAffection": 50,
			"iAggregatedNegativeMemoryDeniedReligionAffection": 50,
			"iAggregatedNegativeMemoryDeniedCivicAffection": 50,
			"iAggregatedNegativeMemoryDeniedJoinWarAffection": 50,
			"iAggregatedNegativeMemoryDeniedStopTradingAffection": 50,
			"iAggregatedNegativeMemoryStoppedTradingAffection": 50,
			"iAggregatedNegativeMemoryStoppedTradingRecentAffection": 50,
			"iAggregatedNegativeMemoryHiredTradeEmbargoAffection": 50,
			"iAggregatedNegativeMemoryMadeDemandAffection": 50,
			"iAggregatedNegativeMemoryCancelledVassalAgreementAffection": 50,
			"iAggregatedNegativeMemoryMadeDemandRecentAffection": 50,
			"iAggregatedNegativeMemoryCancelledOpenBordersAffection": 50,
			"iAggregatedNegativeMemoryCancelledDefensivePactAffection": 50,
			"iAggregatedNegativeMemoryReceivedTechFromAnyAffection": 50,
			"iAggregatedNegativeMemoryVotedAgainstUsAffection": 50,
			"iAggregatedNegativeMemoryEventBadToUsAffection": 50,
			"iAggregatedNegativeMemoryDeclaredWarRecentAffection": 50,
			"iAggregatedNegativeMemoryDeclaredWarResentment": 50,
			"iAggregatedNegativeMemoryDeclaredWarOnFriendResentment": 0,
			"iAggregatedNegativeMemoryHiredWarAllyResentment": 50,
			"iAggregatedNegativeMemoryNukedUsResentment": 50,
			"iAggregatedNegativeMemoryNukedFriendResentment": 0,
			"iAggregatedNegativeMemoryRazedCityResentment": 50,
			"iAggregatedNegativeMemoryRazedHolyCityResentment": 50,
			"iAggregatedNegativeMemorySpyCaughtResentment": 0,
			"iAggregatedNegativeMemoryRefusedHelpResentment": 50,
			"iAggregatedNegativeMemoryRejectedDemandResentment": 50,
			"iAggregatedNegativeMemoryDeniedReligionResentment": 50,
			"iAggregatedNegativeMemoryDeniedCivicResentment": 50,
			"iAggregatedNegativeMemoryDeniedJoinWarResentment": 50,
			"iAggregatedNegativeMemoryDeniedStopTradingResentment": 50,
			"iAggregatedNegativeMemoryStoppedTradingResentment": 100,
			"iAggregatedNegativeMemoryStoppedTradingRecentResentment": 50,
			"iAggregatedNegativeMemoryHiredTradeEmbargoResentment": 50,
			"iAggregatedNegativeMemoryMadeDemandResentment": 0,
			"iAggregatedNegativeMemoryCancelledVassalAgreementResentment": 50,
			"iAggregatedNegativeMemoryMadeDemandRecentResentment": 50,
			"iAggregatedNegativeMemoryCancelledOpenBordersResentment": 50,
			"iAggregatedNegativeMemoryCancelledDefensivePactResentment": 50,
			"iAggregatedNegativeMemoryReceivedTechFromAnyResentment": 50,
			"iAggregatedNegativeMemoryVotedAgainstUsResentment": 100,
			"iAggregatedNegativeMemoryEventBadToUsResentment": 50,
			"iAggregatedNegativeMemoryDeclaredWarRecentResentment": 50
		},
		"LEADER_CATHERINE": {
			"Type": "LEADER_CATHERINE",
			"Description": "TXT_KEY_LEADER_CATHERINE",
			"Civilopedia": "TXT_KEY_LEADER_CATHERINE_PEDIA",
			"ArtDefineTag": "ART_DEF_LEADER_CATHERINE",
			"iWonderConstructRand": 30,
			"iBaseAttitude": 1,
			"iBasePeaceWeight": 2,
			"iWarmongerRespect": 2,
			"iEspionageWeight": 130,
			"iRefuseToTalkWarThreshold": 6,
			"iNoTechTradeThreshold": 15,
			"iTechTradeKnownPercent": 20,
			"iMaxGoldTradePercent": 5,
			"iCultureVictoryWeight": 30,
			"iSpaceVictoryWeight": 45,
			"iConquestVictoryWeight": 25,
			"iDominationVictoryWeight": 40,
			"iDiplomacyVictoryWeight": 10,
			"iMaxWarRand": 100,
			"iMaxWarNearbyPowerRatio": 90,
			"iMaxWarDistantPowerRatio": 40,
			"iMaxWarMinAdjacentLandPercent": 1,
			"iLimitedWarRand": 80,
			"iLimitedWarPowerRatio": 110,
			"iDogpileWarRand": 25,
			"iMakePeaceRand": 10,
			"iDemandRebukedSneakProb": 80,
			"iDemandRebukedWarProb": 0,
			"iRazeCityProb": 0,
			"iBuildUnitProb": 25,
			"iBaseAttackOddsChange": 2,
			"iWorseRankDifferenceAttitudeChange": -2,
			"iBetterRankDifferenceAttitudeChange": 0,
			"iCloseBordersAttitudeChange": -4,
			"iSameReligionAttitudeChangeLimit": 4,
			"iDifferentReligionAttitudeChangeLimit": -2,
			"iShareWarAttitudeChangeLimit": 2,
			"iFavoriteCivicAttitudeChangeLimit": 3,
			"iTechRefuseAttitudeThreshold": -1,
			"iCityRefuseAttitudeThreshold": 3,
			"iNativeCityRefuseAttitudeThreshold": 4,
			"iStrategicBonusRefuseAttitudeThreshold": 2,
			"iHappinessBonusRefuseAttitudeThreshold": 1,
			"iHealthBonusRefuseAttitudeThreshold": 0,
			"iMapRefuseAttitudeThreshold": 3,
			"iDeclareWarRefuseAttitudeThreshold": 3,
			"iDeclareWarThemRefuseAttitudeThreshold": 4,
			"iStopTradingRefuseAttitudeThreshold": 1,
			"iStopTradingThemRefuseAttitudeThreshold": 1,
			"iAdoptCivicRefuseAttitudeThreshold": 1,
			"iConvertReligionRefuseAttitudeThreshold": 2,
			"iOpenBordersRefuseAttitudeThreshold": 0,
			"iDefensivePactRefuseAttitudeThreshold": 2,
			"iVassalRefuseAttitudeThreshold": 1,
			"iVassalPowerModifier": -20,
			"FavoriteCivic": "CIVIC_HEREDITARY_RULE",
			"FavoriteReligion": "RELIGION_CHRISTIANITY",
			"Traits": [
				{
					"TraitType": "TRAIT_CREATIVE",
					"bTrait": "1"
				},
				{
					"TraitType": "TRAIT_IMPERIALIST",
					"bTrait": "1"
				}
			],
			"iFlavorCulture": 5,
			"iFlavorMilitary": 2,
			"iNoWarAttitudeProbCautious": 20,
			"iNoWarAttitudeProbPleased": 80,
			"iNoWarAttitudeProbFriendly": 80,
			"UnitAIWeightModifiers": [
				{
					"UnitAIType": "UNITAI_RESERVE",
					"iWeightModifier": "25"
				}
			],
			"ImprovementWeightModifiers": [
				{
					"ImprovementType": "IMPROVEMENT_FARM",
					"iWeightModifier": "20"
				},
				{
					"ImprovementType": "IMPROVEMENT_LUMBERMILL",
					"iWeightModifier": "20"
				}
			],
			"DiplomacyIntroMusicPeace": "",
			"DiplomacyMusicPeace": [
				{
					"EraType": "ERA_ANCIENT",
					"DiploScriptId": "AS2D_DIPLO_CATHERINE_EARLY"
				},
				{
					"EraType": "ERA_CLASSICAL",
					"DiploScriptId": "AS2D_DIPLO_CATHERINE_EARLY"
				},
				{
					"EraType": "ERA_MEDIEVAL",
					"DiploScriptId": "AS2D_DIPLO_CATHERINE_MIDDLE"
				},
				{
					"EraType": "ERA_RENAISSANCE",
					"DiploScriptId": "AS2D_DIPLO_CATHERINE_MIDDLE"
				},
				{
					"EraType": "ERA_INDUSTRIAL",
					"DiploScriptId": "AS2D_DIPLO_CATHERINE_LATE"
				},
				{
					"EraType": "ERA_MODERN",
					"DiploScriptId": "AS2D_DIPLO_CATHERINE_LATE"
				},
				{
					"EraType": "ERA_FUTURE",
					"DiploScriptId": "AS2D_DIPLO_CATHERINE_LATE"
				}
			],
			"DiplomacyIntroMusicWar": "",
			"DiplomacyMusicWar": "",
			"iPeaceWeightRand": 3,
			"iMaxGoldPerTurnTradePercent": 10,
			"iDeclareWarTradeRand": 40,
			"iAttackOddsChangeRand": 8,
			"iLostWarAttitudeChange": -1,
			"iAtWarAttitudeDivisor": -5,
			"iAtWarAttitudeChangeLimit": 5,
			"iAtPeaceAttitudeDivisor": 60,
			"iAtPeaceAttitudeChangeLimit": 1,
			"iSameReligionAttitudeChange": 1,
			"iSameReligionAttitudeDivisor": 10,
			"iDifferentReligionAttitudeChange": -1,
			"iDifferentReligionAttitudeDivisor": -15,
			"iBonusTradeAttitudeDivisor": 50,
			"iBonusTradeAttitudeChangeLimit": 2,
			"iOpenBordersAttitudeDivisor": 25,
			"iOpenBordersAttitudeChangeLimit": 2,
			"iDefensivePactAttitudeDivisor": 12,
			"iDefensivePactAttitudeChangeLimit": 2,
			"iShareWarAttitudeChange": 1,
			"iShareWarAttitudeDivisor": 8,
			"iFavoriteCivicAttitudeChange": 1,
			"iFavoriteCivicAttitudeDivisor": 10,
			"iDemandTributeAttitudeThreshold": 2,
			"iNoGiveHelpAttitudeThreshold": 2,
			"iPermanentAllianceRefuseAttitudeThreshold": 3,
			"iFreedomAppreciation": 10,
			"iNoWarAttitudeProbFurious": 0,
			"iNoWarAttitudeProbAnnoyed": 0,
			"iLoveOfPeace": 0,
			"iFlavorReligion": 0,
			"iFlavorProduction": 0,
			"iFlavorGold": 0,
			"iFlavorScience": 0,
			"iFlavorGrowth": 0,
			"iFlavorEspionage": 0,
			"iContactRandReligionPressure": 250,
			"iContactDelayReligionPressure": 50,
			"iContactRandCivicPressure": 500,
			"iContactDelayCivicPressure": 50,
			"iContactRandJoinWar": 10,
			"iContactDelayJoinWar": 20,
			"iContactRandStopTrading": 50,
			"iContactDelayStopTrading": 20,
			"iContactRandGiveHelp": 500,
			"iContactDelayGiveHelp": 50,
			"iContactRandAskForHelp": 25,
			"iContactDelayAskForHelp": 50,
			"iContactRandDemandTribute": 750,
			"iContactDelayDemandTribute": 50,
			"iContactRandTradeTech": 2,
			"iContactDelayTradeTech": 30,
			"iContactRandTradeBonus": 2,
			"iContactDelayTradeBonus": 20,
			"iContactRandPeaceTreaty": 15,
			"iContactDelayPeaceTreaty": 10,
			"iContactRandOpenBorders": 10,
			"iContactDelayOpenBorders": 40,
			"iContactRandDefensivePact": 80,
			"iContactDelayDefensivePact": 20,
			"iContactRandPermanentAlliance": 80,
			"iContactDelayPermanentAlliance": 20,
			"iContactRandTradeMap": 20,
			"iContactDelayTradeMap": 50,
			"iAggregatedContactProbReligionPressure": 79,
			"iAggregatedContactProbCivicPressure": 58,
			"iAggregatedContactProbJoinWar": 100,
			"iAggregatedContactProbStopTrading": 50,
			"iAggregatedContactProbGiveHelp": 57,
			"iAggregatedContactProbAskForHelp": 100,
			"iAggregatedContactProbDemandTribute": 34,
			"iAggregatedContactProbTradeTech": 95,
			"iAggregatedContactProbTradeBonus": 92,
			"iAggregatedContactProbPeaceTreaty": 70,
			"iAggregatedContactProbOpenBorders": 50,
			"iAggregatedContactProbDefensivePact": 50,
			"iAggregatedContactProbPermanentAlliance": 50,
			"iAggregatedContactProbTradeMap": 50,
			"iMemoryAttitudePercentGiveHelp": 100,
			"iMemoryDecayGiveHelp": 150,
			"iMemoryAttitudePercentAcceptDemand": 100,
			"iMemoryDecayAcceptDemand": 30,
			"iMemoryAttitudePercentAcceptedReligion": 100,
			"iMemoryDecayAcceptedReligion": 100,
			"iMemoryAttitudePercentAcceptedCivic": 100,
			"iMemoryDecayAcceptedCivic": 100,
			"iMemoryAttitudePercentAcceptedJoinWar": 100,
			"iMemoryDecayAcceptedJoinWar": 100,
			"iMemoryAttitudePercentAcceptedStopTrading": 50,
			"iMemoryDecayAcceptedStopTrading": 50,
			"iMemoryAttitudePercentTradedTechToUs": 15,
			"iMemoryDecayTradedTechToUs": 25,
			"iMemoryAttitudePercentVotedForUs": 200,
			"iMemoryDecayVotedForUs": 10,
			"iMemoryAttitudePercentEventGoodToUs": 100,
			"iMemoryDecayEventGoodToUs": 50,
			"iMemoryAttitudePercentLiberatedCities": 150,
			"iMemoryDecayLiberatedCities": 150,
			"iMemoryAttitudePercentIndependence": 100,
			"iMemoryDecayIndependence": 30,
			"iAggregatedPositiveMemoryGiveHelpAffection": 50,
			"iAggregatedPositiveMemoryAcceptDemandAffection": 50,
			"iAggregatedPositiveMemoryAcceptedReligionAffection": 50,
			"iAggregatedPositiveMemoryAcceptedCivicAffection": 50,
			"iAggregatedPositiveMemoryAcceptedJoinWarAffection": 50,
			"iAggregatedPositiveMemoryAcceptedStopTradingAffection": 50,
			"iAggregatedPositiveMemoryTradedTechToUsAffection": 68,
			"iAggregatedPositiveMemoryVotedForUsAffection": 50,
			"iAggregatedPositiveMemoryEventGoodToUsAffection": 50,
			"iAggregatedPositiveMemoryLiberatedCitiesAffection": 50,
			"iAggregatedPositiveMemoryIndependenceAffection": 50,
			"iAggregatedPositiveMemoryGiveHelpResentment": 50,
			"iAggregatedPositiveMemoryAcceptDemandResentment": 50,
			"iAggregatedPositiveMemoryAcceptedReligionResentment": 50,
			"iAggregatedPositiveMemoryAcceptedCivicResentment": 50,
			"iAggregatedPositiveMemoryAcceptedJoinWarResentment": 50,
			"iAggregatedPositiveMemoryAcceptedStopTradingResentment": 50,
			"iAggregatedPositiveMemoryTradedTechToUsResentment": 50,
			"iAggregatedPositiveMemoryVotedForUsResentment": 50,
			"iAggregatedPositiveMemoryEventGoodToUsResentment": 50,
			"iAggregatedPositiveMemoryLiberatedCitiesResentment": 50,
			"iAggregatedPositiveMemoryIndependenceResentment": 50,
			"iMemoryAttitudePercentDeclaredWar": -300,
			"iMemoryDecayDeclaredWar": 150,
			"iMemoryAttitudePercentDeclaredWarOnFriend": -100,
			"iMemoryDecayDeclaredWarOnFriend": 120,
			"iMemoryAttitudePercentHiredWarAlly": -200,
			"iMemoryDecayHiredWarAlly": 75,
			"iMemoryAttitudePercentNukedUs": -200,
			"iMemoryDecayNukedUs": 120,
			"iMemoryAttitudePercentNukedFriend": -100,
			"iMemoryDecayNukedFriend": 80,
			"iMemoryAttitudePercentRazedCity": -250,
			"iMemoryDecayRazedCity": 75,
			"iMemoryAttitudePercentRazedHolyCity": -200,
			"iMemoryDecayRazedHolyCity": 150,
			"iMemoryAttitudePercentSpyCaught": -200,
			"iMemoryDecaySpyCaught": 40,
			"iMemoryAttitudePercentRefusedHelp": -200,
			"iMemoryDecayRefusedHelp": 100,
			"iMemoryAttitudePercentRejectedDemand": -200,
			"iMemoryDecayRejectedDemand": 90,
			"iMemoryAttitudePercentDeniedReligion": -200,
			"iMemoryDecayDeniedReligion": 50,
			"iMemoryAttitudePercentDeniedCivic": -200,
			"iMemoryDecayDeniedCivic": 50,
			"iMemoryAttitudePercentDeniedJoinWar": -200,
			"iMemoryDecayDeniedJoinWar": 100,
			"iMemoryAttitudePercentDeniedStopTrading": -200,
			"iMemoryDecayDeniedStopTrading": 50,
			"iMemoryAttitudePercentStoppedTrading": -100,
			"iMemoryDecayStoppedTrading": 60,
			"iMemoryAttitudePercentStoppedTradingRecent": 0,
			"iMemoryDecayStoppedTradingRecent": 18,
			"iMemoryAttitudePercentHiredTradeEmbargo": -100,
			"iMemoryDecayHiredTradeEmbargo": 60,
			"iMemoryAttitudePercentMadeDemand": -200,
			"iMemoryDecayMadeDemand": 30,
			"iMemoryAttitudePercentCancelledVassalAgreement": 0,
			"iMemoryDecayCancelledVassalAgreement": 10,
			"iMemoryAttitudePercentMadeDemandRecent": 0,
			"iMemoryDecayMadeDemandRecent": 20,
			"iMemoryAttitudePercentCancelledOpenBorders": 0,
			"iMemoryDecayCancelledOpenBorders": 10,
			"iMemoryAttitudePercentCancelledDefensivePact": 0,
			"iMemoryDecayCancelledDefensivePact": 10,
			"iMemoryAttitudePercentReceivedTechFromAny": 0,
			"iMemoryDecayReceivedTechFromAny": 20,
			"iMemoryAttitudePercentVotedAgainstUs": -200,
			"iMemoryDecayVotedAgainstUs": 10,
			"iMemoryAttitudePercentEventBadToUs": -100,
			"iMemoryDecayEventBadToUs": 50,
			"iMemoryAttitudePercentDeclaredWarRecent": 0,
			"iMemoryDecayDeclaredWarRecent": 11,
			"iAggregatedNegativeMemoryDeclaredWarAffection": 50,
			"iAggregatedNegativeMemoryDeclaredWarOnFriendAffection": 50,
			"iAggregatedNegativeMemoryHiredWarAllyAffection": 50,
			"iAggregatedNegativeMemoryNukedUsAffection": 50,
			"iAggregatedNegativeMemoryNukedFriendAffection": 50,
			"iAggregatedNegativeMemoryRazedCityAffection": 50,
			"iAggregatedNegativeMemoryRazedHolyCityAffection": 50,
			"iAggregatedNegativeMemorySpyCaughtAffection": 50,
			"iAggregatedNegativeMemoryRefusedHelpAffection": 50,
			"iAggregatedNegativeMemoryRejectedDemandAffection": 50,
			"iAggregatedNegativeMemoryDeniedReligionAffection": 50,
			"iAggregatedNegativeMemoryDeniedCivicAffection": 50,
			"iAggregatedNegativeMemoryDeniedJoinWarAffection": 50,
			"iAggregatedNegativeMemoryDeniedStopTradingAffection": 50,
			"iAggregatedNegativeMemoryStoppedTradingAffection": 50,
			"iAggregatedNegativeMemoryStoppedTradingRecentAffection": 50,
			"iAggregatedNegativeMemoryHiredTradeEmbargoAffection": 50,
			"iAggregatedNegativeMemoryMadeDemandAffection": 50,
			"iAggregatedNegativeMemoryCancelledVassalAgreementAffection": 50,
			"iAggregatedNegativeMemoryMadeDemandRecentAffection": 50,
			"iAggregatedNegativeMemoryCancelledOpenBordersAffection": 50,
			"iAggregatedNegativeMemoryCancelledDefensivePactAffection": 50,
			"iAggregatedNegativeMemoryReceivedTechFromAnyAffection": 50,
			"iAggregatedNegativeMemoryVotedAgainstUsAffection": 50,
			"iAggregatedNegativeMemoryEventBadToUsAffection": 50,
			"iAggregatedNegativeMemoryDeclaredWarRecentAffection": 50,
			"iAggregatedNegativeMemoryDeclaredWarResentment": 50,
			"iAggregatedNegativeMemoryDeclaredWarOnFriendResentment": 0,
			"iAggregatedNegativeMemoryHiredWarAllyResentment": 50,
			"iAggregatedNegativeMemoryNukedUsResentment": 50,
			"iAggregatedNegativeMemoryNukedFriendResentment": 0,
			"iAggregatedNegativeMemoryRazedCityResentment": 50,
			"iAggregatedNegativeMemoryRazedHolyCityResentment": 50,
			"iAggregatedNegativeMemorySpyCaughtResentment": 100,
			"iAggregatedNegativeMemoryRefusedHelpResentment": 100,
			"iAggregatedNegativeMemoryRejectedDemandResentment": 100,
			"iAggregatedNegativeMemoryDeniedReligionResentment": 100,
			"iAggregatedNegativeMemoryDeniedCivicResentment": 100,
			"iAggregatedNegativeMemoryDeniedJoinWarResentment": 100,
			"iAggregatedNegativeMemoryDeniedStopTradingResentment": 100,
			"iAggregatedNegativeMemoryStoppedTradingResentment": 100,
			"iAggregatedNegativeMemoryStoppedTradingRecentResentment": 50,
			"iAggregatedNegativeMemoryHiredTradeEmbargoResentment": 50,
			"iAggregatedNegativeMemoryMadeDemandResentment": 100,
			"iAggregatedNegativeMemoryCancelledVassalAgreementResentment": 50,
			"iAggregatedNegativeMemoryMadeDemandRecentResentment": 50,
			"iAggregatedNegativeMemoryCancelledOpenBordersResentment": 50,
			"iAggregatedNegativeMemoryCancelledDefensivePactResentment": 50,
			"iAggregatedNegativeMemoryReceivedTechFromAnyResentment": 50,
			"iAggregatedNegativeMemoryVotedAgainstUsResentment": 100,
			"iAggregatedNegativeMemoryEventBadToUsResentment": 50,
			"iAggregatedNegativeMemoryDeclaredWarRecentResentment": 50
		},
		"LEADER_GANDHI": {
			"Type": "LEADER_GANDHI",
			"Description": "TXT_KEY_LEADER_GANDHI",
			"Civilopedia": "TXT_KEY_LEADER_GANDHI_PEDIA",
			"ArtDefineTag": "ART_DEF_LEADER_GANDHI",
			"iWonderConstructRand": 10,
			"iBaseAttitude": 2,
			"iBasePeaceWeight": 10,
			"iWarmongerRespect": 0,
			"iEspionageWeight": 50,
			"iRefuseToTalkWarThreshold": 6,
			"iNoTechTradeThreshold": 15,
			"iTechTradeKnownPercent": 20,
			"iMaxGoldTradePercent": 10,
			"iCultureVictoryWeight": 45,
			"iSpaceVictoryWeight": 30,
			"iConquestVictoryWeight": 0,
			"iDominationVictoryWeight": 5,
			"iDiplomacyVictoryWeight": 70,
			"iMaxWarRand": 400,
			"iMaxWarNearbyPowerRatio": 100,
			"iMaxWarDistantPowerRatio": 60,
			"iMaxWarMinAdjacentLandPercent": 3,
			"iLimitedWarRand": 200,
			"iLimitedWarPowerRatio": 80,
			"iDogpileWarRand": 100,
			"iMakePeaceRand": 10,
			"iDemandRebukedSneakProb": 0,
			"iDemandRebukedWarProb": 0,
			"iRazeCityProb": 0,
			"iBuildUnitProb": 15,
			"iBaseAttackOddsChange": 0,
			"iWorseRankDifferenceAttitudeChange": 0,
			"iBetterRankDifferenceAttitudeChange": 1,
			"iCloseBordersAttitudeChange": -2,
			"iSameReligionAttitudeChangeLimit": 4,
			"iDifferentReligionAttitudeChangeLimit": -1,
			"iShareWarAttitudeChangeLimit": 2,
			"iFavoriteCivicAttitudeChangeLimit": 5,
			"iTechRefuseAttitudeThreshold": -1,
			"iCityRefuseAttitudeThreshold": 3,
			"iNativeCityRefuseAttitudeThreshold": 4,
			"iStrategicBonusRefuseAttitudeThreshold": 1,
			"iHappinessBonusRefuseAttitudeThreshold": -1,
			"iHealthBonusRefuseAttitudeThreshold": -1,
			"iMapRefuseAttitudeThreshold": -1,
			"iDeclareWarRefuseAttitudeThreshold": 3,
			"iDeclareWarThemRefuseAttitudeThreshold": 1,
			"iStopTradingRefuseAttitudeThreshold": 3,
			"iStopTradingThemRefuseAttitudeThreshold": 2,
			"iAdoptCivicRefuseAttitudeThreshold": 2,
			"iConvertReligionRefuseAttitudeThreshold": 1,
			"iOpenBordersRefuseAttitudeThreshold": -1,
			"iVassalRefuseAttitudeThreshold": 1,
			"iVassalPowerModifier": -20,
			"FavoriteCivic": "CIVIC_UNIVERSAL_SUFFRAGE",
			"FavoriteReligion": "RELIGION_HINDUISM",
			"Traits": [
				{
					"TraitType": "TRAIT_SPIRITUAL",
					"bTrait": "1"
				},
				{
					"TraitType": "TRAIT_PHILOSOPHICAL",
					"bTrait": "1"
				}
			],
			"iFlavorCulture": 10,
			"iNoWarAttitudeProbFurious": 20,
			"iNoWarAttitudeProbAnnoyed": 50,
			"iNoWarAttitudeProbCautious": 85,
			"iNoWarAttitudeProbPleased": 110,
			"iNoWarAttitudeProbFriendly": 115,
			"UnitAIWeightModifiers": "",
			"ImprovementWeightModifiers": [
				{
					"ImprovementType": "IMPROVEMENT_FARM",
					"iWeightModifier": "30"
				}
			],
			"DiplomacyIntroMusicPeace": [
				{
					"EraType": "ERA_ANCIENT",
					"DiploScriptId": "AS2D_DIPLO_GANDHI_EARLY_INTRO"
				},
				{
					"EraType": "ERA_CLASSICAL",
					"DiploScriptId": "AS2D_DIPLO_GANDHI_EARLY_INTRO"
				}
			],
			"DiplomacyMusicPeace": [
				{
					"EraType": "ERA_ANCIENT",
					"DiploScriptId": "AS2D_DIPLO_GANDHI_EARLY_LP"
				},
				{
					"EraType": "ERA_CLASSICAL",
					"DiploScriptId": "AS2D_DIPLO_GANDHI_EARLY_LP"
				},
				{
					"EraType": "ERA_MEDIEVAL",
					"DiploScriptId": "AS2D_DIPLO_GANDHI_MIDDLE"
				},
				{
					"EraType": "ERA_RENAISSANCE",
					"DiploScriptId": "AS2D_DIPLO_GANDHI_MIDDLE"
				},
				{
					"EraType": "ERA_INDUSTRIAL",
					"DiploScriptId": "AS2D_DIPLO_GANDHI_LATE"
				},
				{
					"EraType": "ERA_MODERN",
					"DiploScriptId": "AS2D_DIPLO_GANDHI_LATE"
				},
				{
					"EraType": "ERA_FUTURE",
					"DiploScriptId": "AS2D_DIPLO_GANDHI_LATE"
				}
			],
			"DiplomacyIntroMusicWar": "",
			"DiplomacyMusicWar": "",
			"iPeaceWeightRand": 3,
			"iMaxGoldPerTurnTradePercent": 10,
			"iDeclareWarTradeRand": 40,
			"iAttackOddsChangeRand": 8,
			"iLostWarAttitudeChange": -1,
			"iAtWarAttitudeDivisor": -5,
			"iAtWarAttitudeChangeLimit": 5,
			"iAtPeaceAttitudeDivisor": 60,
			"iAtPeaceAttitudeChangeLimit": 1,
			"iSameReligionAttitudeChange": 1,
			"iSameReligionAttitudeDivisor": 10,
			"iDifferentReligionAttitudeChange": -1,
			"iDifferentReligionAttitudeDivisor": -15,
			"iBonusTradeAttitudeDivisor": 50,
			"iBonusTradeAttitudeChangeLimit": 2,
			"iOpenBordersAttitudeDivisor": 25,
			"iOpenBordersAttitudeChangeLimit": 2,
			"iDefensivePactAttitudeDivisor": 12,
			"iDefensivePactAttitudeChangeLimit": 2,
			"iShareWarAttitudeChange": 1,
			"iShareWarAttitudeDivisor": 8,
			"iFavoriteCivicAttitudeChange": 1,
			"iFavoriteCivicAttitudeDivisor": 10,
			"iDemandTributeAttitudeThreshold": 2,
			"iNoGiveHelpAttitudeThreshold": 2,
			"iDefensivePactRefuseAttitudeThreshold": 3,
			"iPermanentAllianceRefuseAttitudeThreshold": 3,
			"iFreedomAppreciation": 10,
			"iLoveOfPeace": 0,
			"iFlavorMilitary": 0,
			"iFlavorReligion": 0,
			"iFlavorProduction": 0,
			"iFlavorGold": 0,
			"iFlavorScience": 0,
			"iFlavorGrowth": 0,
			"iFlavorEspionage": 0,
			"iContactRandReligionPressure": 500,
			"iContactDelayReligionPressure": 50,
			"iContactRandCivicPressure": 50,
			"iContactDelayCivicPressure": 50,
			"iContactRandJoinWar": 20,
			"iContactDelayJoinWar": 20,
			"iContactRandStopTrading": 50,
			"iContactDelayStopTrading": 20,
			"iContactRandGiveHelp": 25,
			"iContactDelayGiveHelp": 50,
			"iContactRandAskForHelp": 50,
			"iContactDelayAskForHelp": 50,
			"iContactRandDemandTribute": 0,
			"iContactDelayDemandTribute": 50,
			"iContactRandTradeTech": 2,
			"iContactDelayTradeTech": 30,
			"iContactRandTradeBonus": 2,
			"iContactDelayTradeBonus": 20,
			"iContactRandPeaceTreaty": 10,
			"iContactDelayPeaceTreaty": 8,
			"iContactRandOpenBorders": 10,
			"iContactDelayOpenBorders": 40,
			"iContactRandDefensivePact": 80,
			"iContactDelayDefensivePact": 20,
			"iContactRandPermanentAlliance": 80,
			"iContactDelayPermanentAlliance": 20,
			"iContactRandTradeMap": 20,
			"iContactDelayTradeMap": 50,
			"iAggregatedContactProbReligionPressure": 52,
			"iAggregatedContactProbCivicPressure": 100,
			"iAggregatedContactProbJoinWar": 0,
			"iAggregatedContactProbStopTrading": 50,
			"iAggregatedContactProbGiveHelp": 100,
			"iAggregatedContactProbAskForHelp": 98,
			"iAggregatedContactProbDemandTribute": 0,
			"iAggregatedContactProbTradeTech": 95,
			"iAggregatedContactProbTradeBonus": 92,
			"iAggregatedContactProbPeaceTreaty": 100,
			"iAggregatedContactProbOpenBorders": 50,
			"iAggregatedContactProbDefensivePact": 50,
			"iAggregatedContactProbPermanentAlliance": 50,
			"iAggregatedContactProbTradeMap": 50,
			"iMemoryAttitudePercentGiveHelp": 100,
			"iMemoryDecayGiveHelp": 150,
			"iMemoryAttitudePercentAcceptDemand": 100,
			"iMemoryDecayAcceptDemand": 30,
			"iMemoryAttitudePercentAcceptedReligion": 100,
			"iMemoryDecayAcceptedReligion": 100,
			"iMemoryAttitudePercentAcceptedCivic": 100,
			"iMemoryDecayAcceptedCivic": 100,
			"iMemoryAttitudePercentAcceptedJoinWar": 100,
			"iMemoryDecayAcceptedJoinWar": 100,
			"iMemoryAttitudePercentAcceptedStopTrading": 50,
			"iMemoryDecayAcceptedStopTrading": 50,
			"iMemoryAttitudePercentTradedTechToUs": 5,
			"iMemoryDecayTradedTechToUs": 25,
			"iMemoryAttitudePercentVotedForUs": 200,
			"iMemoryDecayVotedForUs": 10,
			"iMemoryAttitudePercentEventGoodToUs": 100,
			"iMemoryDecayEventGoodToUs": 50,
			"iMemoryAttitudePercentLiberatedCities": 150,
			"iMemoryDecayLiberatedCities": 150,
			"iMemoryAttitudePercentIndependence": 100,
			"iMemoryDecayIndependence": 30,
			"iAggregatedPositiveMemoryGiveHelpAffection": 50,
			"iAggregatedPositiveMemoryAcceptDemandAffection": 50,
			"iAggregatedPositiveMemoryAcceptedReligionAffection": 50,
			"iAggregatedPositiveMemoryAcceptedCivicAffection": 50,
			"iAggregatedPositiveMemoryAcceptedJoinWarAffection": 50,
			"iAggregatedPositiveMemoryAcceptedStopTradingAffection": 50,
			"iAggregatedPositiveMemoryTradedTechToUsAffection": 0,
			"iAggregatedPositiveMemoryVotedForUsAffection": 50,
			"iAggregatedPositiveMemoryEventGoodToUsAffection": 50,
			"iAggregatedPositiveMemoryLiberatedCitiesAffection": 50,
			"iAggregatedPositiveMemoryIndependenceAffection": 50,
			"iAggregatedPositiveMemoryGiveHelpResentment": 50,
			"iAggregatedPositiveMemoryAcceptDemandResentment": 50,
			"iAggregatedPositiveMemoryAcceptedReligionResentment": 50,
			"iAggregatedPositiveMemoryAcceptedCivicResentment": 50,
			"iAggregatedPositiveMemoryAcceptedJoinWarResentment": 50,
			"iAggregatedPositiveMemoryAcceptedStopTradingResentment": 50,
			"iAggregatedPositiveMemoryTradedTechToUsResentment": 50,
			"iAggregatedPositiveMemoryVotedForUsResentment": 50,
			"iAggregatedPositiveMemoryEventGoodToUsResentment": 50,
			"iAggregatedPositiveMemoryLiberatedCitiesResentment": 50,
			"iAggregatedPositiveMemoryIndependenceResentment": 50,
			"iMemoryAttitudePercentDeclaredWar": -300,
			"iMemoryDecayDeclaredWar": 150,
			"iMemoryAttitudePercentDeclaredWarOnFriend": -200,
			"iMemoryDecayDeclaredWarOnFriend": 120,
			"iMemoryAttitudePercentHiredWarAlly": -200,
			"iMemoryDecayHiredWarAlly": 75,
			"iMemoryAttitudePercentNukedUs": -200,
			"iMemoryDecayNukedUs": 120,
			"iMemoryAttitudePercentNukedFriend": -200,
			"iMemoryDecayNukedFriend": 80,
			"iMemoryAttitudePercentRazedCity": -250,
			"iMemoryDecayRazedCity": 75,
			"iMemoryAttitudePercentRazedHolyCity": -200,
			"iMemoryDecayRazedHolyCity": 150,
			"iMemoryAttitudePercentSpyCaught": -100,
			"iMemoryDecaySpyCaught": 40,
			"iMemoryAttitudePercentRefusedHelp": 0,
			"iMemoryDecayRefusedHelp": 100,
			"iMemoryAttitudePercentRejectedDemand": 0,
			"iMemoryDecayRejectedDemand": 90,
			"iMemoryAttitudePercentDeniedReligion": 0,
			"iMemoryDecayDeniedReligion": 50,
			"iMemoryAttitudePercentDeniedCivic": 0,
			"iMemoryDecayDeniedCivic": 50,
			"iMemoryAttitudePercentDeniedJoinWar": 0,
			"iMemoryDecayDeniedJoinWar": 100,
			"iMemoryAttitudePercentDeniedStopTrading": 0,
			"iMemoryDecayDeniedStopTrading": 50,
			"iMemoryAttitudePercentStoppedTrading": 0,
			"iMemoryDecayStoppedTrading": 60,
			"iMemoryAttitudePercentStoppedTradingRecent": 0,
			"iMemoryDecayStoppedTradingRecent": 18,
			"iMemoryAttitudePercentHiredTradeEmbargo": -100,
			"iMemoryDecayHiredTradeEmbargo": 60,
			"iMemoryAttitudePercentMadeDemand": -100,
			"iMemoryDecayMadeDemand": 30,
			"iMemoryAttitudePercentCancelledVassalAgreement": 0,
			"iMemoryDecayCancelledVassalAgreement": 10,
			"iMemoryAttitudePercentMadeDemandRecent": 0,
			"iMemoryDecayMadeDemandRecent": 20,
			"iMemoryAttitudePercentCancelledOpenBorders": 0,
			"iMemoryDecayCancelledOpenBorders": 10,
			"iMemoryAttitudePercentCancelledDefensivePact": 0,
			"iMemoryDecayCancelledDefensivePact": 10,
			"iMemoryAttitudePercentReceivedTechFromAny": 0,
			"iMemoryDecayReceivedTechFromAny": 20,
			"iMemoryAttitudePercentVotedAgainstUs": 0,
			"iMemoryDecayVotedAgainstUs": 10,
			"iMemoryAttitudePercentEventBadToUs": -100,
			"iMemoryDecayEventBadToUs": 50,
			"iMemoryAttitudePercentDeclaredWarRecent": 0,
			"iMemoryDecayDeclaredWarRecent": 11,
			"iAggregatedNegativeMemoryDeclaredWarAffection": 50,
			"iAggregatedNegativeMemoryDeclaredWarOnFriendAffection": 50,
			"iAggregatedNegativeMemoryHiredWarAllyAffection": 50,
			"iAggregatedNegativeMemoryNukedUsAffection": 50,
			"iAggregatedNegativeMemoryNukedFriendAffection": 50,
			"iAggregatedNegativeMemoryRazedCityAffection": 50,
			"iAggregatedNegativeMemoryRazedHolyCityAffection": 50,
			"iAggregatedNegativeMemorySpyCaughtAffection": 50,
			"iAggregatedNegativeMemoryRefusedHelpAffection": 50,
			"iAggregatedNegativeMemoryRejectedDemandAffection": 50,
			"iAggregatedNegativeMemoryDeniedReligionAffection": 50,
			"iAggregatedNegativeMemoryDeniedCivicAffection": 50,
			"iAggregatedNegativeMemoryDeniedJoinWarAffection": 50,
			"iAggregatedNegativeMemoryDeniedStopTradingAffection": 50,
			"iAggregatedNegativeMemoryStoppedTradingAffection": 50,
			"iAggregatedNegativeMemoryStoppedTradingRecentAffection": 50,
			"iAggregatedNegativeMemoryHiredTradeEmbargoAffection": 50,
			"iAggregatedNegativeMemoryMadeDemandAffection": 50,
			"iAggregatedNegativeMemoryCancelledVassalAgreementAffection": 50,
			"iAggregatedNegativeMemoryMadeDemandRecentAffection": 50,
			"iAggregatedNegativeMemoryCancelledOpenBordersAffection": 50,
			"iAggregatedNegativeMemoryCancelledDefensivePactAffection": 50,
			"iAggregatedNegativeMemoryReceivedTechFromAnyAffection": 50,
			"iAggregatedNegativeMemoryVotedAgainstUsAffection": 50,
			"iAggregatedNegativeMemoryEventBadToUsAffection": 50,
			"iAggregatedNegativeMemoryDeclaredWarRecentAffection": 50,
			"iAggregatedNegativeMemoryDeclaredWarResentment": 50,
			"iAggregatedNegativeMemoryDeclaredWarOnFriendResentment": 100,
			"iAggregatedNegativeMemoryHiredWarAllyResentment": 50,
			"iAggregatedNegativeMemoryNukedUsResentment": 50,
			"iAggregatedNegativeMemoryNukedFriendResentment": 100,
			"iAggregatedNegativeMemoryRazedCityResentment": 50,
			"iAggregatedNegativeMemoryRazedHolyCityResentment": 50,
			"iAggregatedNegativeMemorySpyCaughtResentment": 0,
			"iAggregatedNegativeMemoryRefusedHelpResentment": 0,
			"iAggregatedNegativeMemoryRejectedDemandResentment": 0,
			"iAggregatedNegativeMemoryDeniedReligionResentment": 0,
			"iAggregatedNegativeMemoryDeniedCivicResentment": 0,
			"iAggregatedNegativeMemoryDeniedJoinWarResentment": 0,
			"iAggregatedNegativeMemoryDeniedStopTradingResentment": 0,
			"iAggregatedNegativeMemoryStoppedTradingResentment": 0,
			"iAggregatedNegativeMemoryStoppedTradingRecentResentment": 50,
			"iAggregatedNegativeMemoryHiredTradeEmbargoResentment": 50,
			"iAggregatedNegativeMemoryMadeDemandResentment": 0,
			"iAggregatedNegativeMemoryCancelledVassalAgreementResentment": 50,
			"iAggregatedNegativeMemoryMadeDemandRecentResentment": 50,
			"iAggregatedNegativeMemoryCancelledOpenBordersResentment": 50,
			"iAggregatedNegativeMemoryCancelledDefensivePactResentment": 50,
			"iAggregatedNegativeMemoryReceivedTechFromAnyResentment": 50,
			"iAggregatedNegativeMemoryVotedAgainstUsResentment": 0,
			"iAggregatedNegativeMemoryEventBadToUsResentment": 50,
			"iAggregatedNegativeMemoryDeclaredWarRecentResentment": 50
		},
		"LEADER_TOKUGAWA": {
			"Type": "LEADER_TOKUGAWA",
			"Description": "TXT_KEY_LEADER_TOKUGAWA",
			"Civilopedia": "TXT_KEY_LEADER_TOKUGAWA_PEDIA",
			"ArtDefineTag": "ART_DEF_LEADER_TOKUGAWA",
			"iWonderConstructRand": 20,
			"iBaseAttitude": -1,
			"iBasePeaceWeight": 1,
			"iWarmongerRespect": 2,
			"iEspionageWeight": 60,
			"iRefuseToTalkWarThreshold": 10,
			"iNoTechTradeThreshold": 5,
			"iTechTradeKnownPercent": 100,
			"iMaxGoldTradePercent": 5,
			"iCultureVictoryWeight": 25,
			"iSpaceVictoryWeight": 40,
			"iConquestVictoryWeight": 40,
			"iDominationVictoryWeight": 45,
			"iDiplomacyVictoryWeight": 0,
			"iMaxWarRand": 100,
			"iMaxWarNearbyPowerRatio": 100,
			"iMaxWarDistantPowerRatio": 30,
			"iMaxWarMinAdjacentLandPercent": 4,
			"iLimitedWarRand": 60,
			"iLimitedWarPowerRatio": 100,
			"iDogpileWarRand": 25,
			"iMakePeaceRand": 40,
			"iDemandRebukedSneakProb": 60,
			"iDemandRebukedWarProb": 25,
			"iRazeCityProb": 25,
			"iBuildUnitProb": 30,
			"iBaseAttackOddsChange": 0,
			"iWorseRankDifferenceAttitudeChange": 0,
			"iBetterRankDifferenceAttitudeChange": 1,
			"iCloseBordersAttitudeChange": -3,
			"iSameReligionAttitudeChangeLimit": 3,
			"iDifferentReligionAttitudeChangeLimit": -1,
			"iShareWarAttitudeChangeLimit": 4,
			"iFavoriteCivicAttitudeChangeLimit": 4,
			"iTechRefuseAttitudeThreshold": 2,
			"iCityRefuseAttitudeThreshold": 2,
			"iNativeCityRefuseAttitudeThreshold": 4,
			"iStrategicBonusRefuseAttitudeThreshold": 3,
			"iHappinessBonusRefuseAttitudeThreshold": 2,
			"iHealthBonusRefuseAttitudeThreshold": 2,
			"iMapRefuseAttitudeThreshold": 4,
			"iDeclareWarRefuseAttitudeThreshold": 2,
			"iDeclareWarThemRefuseAttitudeThreshold": 3,
			"iStopTradingRefuseAttitudeThreshold": 1,
			"iStopTradingThemRefuseAttitudeThreshold": 3,
			"iAdoptCivicRefuseAttitudeThreshold": 3,
			"iConvertReligionRefuseAttitudeThreshold": 3,
			"iOpenBordersRefuseAttitudeThreshold": 2,
			"iDefensivePactRefuseAttitudeThreshold": 2,
			"iVassalRefuseAttitudeThreshold": 2,
			"iVassalPowerModifier": 0,
			"FavoriteCivic": "CIVIC_MERCANTILISM",
			"FavoriteReligion": "RELIGION_BUDDHISM",
			"Traits": [
				{
					"TraitType": "TRAIT_PROTECTIVE",
					"bTrait": "1"
				},
				{
					"TraitType": "TRAIT_AGGRESSIVE",
					"bTrait": "1"
				}
			],
			"iFlavorMilitary": 2,
			"iFlavorScience": 5,
			"iNoWarAttitudeProbAnnoyed": 10,
			"iNoWarAttitudeProbCautious": 50,
			"iNoWarAttitudeProbPleased": 90,
			"iNoWarAttitudeProbFriendly": 90,
			"UnitAIWeightModifiers": [
				{
					"UnitAIType": "UNITAI_CITY_COUNTER",
					"iWeightModifier": "25"
				},
				{
					"UnitAIType": "UNITAI_WORKER",
					"iWeightModifier": "25"
				}
			],
			"ImprovementWeightModifiers": [
				{
					"ImprovementType": "IMPROVEMENT_FARM",
					"iWeightModifier": "20"
				},
				{
					"ImprovementType": "IMPROVEMENT_LUMBERMILL",
					"iWeightModifier": "20"
				}
			],
			"DiplomacyIntroMusicPeace": [
				{
					"EraType": "ERA_ANCIENT",
					"DiploScriptId": "AS2D_DIPLO_TOKUGAWA_EARLY_INTRO"
				},
				{
					"EraType": "ERA_CLASSICAL",
					"DiploScriptId": "AS2D_DIPLO_TOKUGAWA_EARLY_INTRO"
				}
			],
			"DiplomacyMusicPeace": [
				{
					"EraType": "ERA_ANCIENT",
					"DiploScriptId": "AS2D_DIPLO_TOKUGAWA_EARLY_LP"
				},
				{
					"EraType": "ERA_CLASSICAL",
					"DiploScriptId": "AS2D_DIPLO_TOKUGAWA_EARLY_LP"
				},
				{
					"EraType": "ERA_MEDIEVAL",
					"DiploScriptId": "AS2D_DIPLO_TOKUGAWA_MIDDLE"
				},
				{
					"EraType": "ERA_RENAISSANCE",
					"DiploScriptId": "AS2D_DIPLO_TOKUGAWA_MIDDLE"
				},
				{
					"EraType": "ERA_INDUSTRIAL",
					"DiploScriptId": "AS2D_DIPLO_TOKUGAWA_LATE"
				},
				{
					"EraType": "ERA_MODERN",
					"DiploScriptId": "AS2D_DIPLO_TOKUGAWA_LATE"
				},
				{
					"EraType": "ERA_FUTURE",
					"DiploScriptId": "AS2D_DIPLO_TOKUGAWA_LATE"
				}
			],
			"DiplomacyIntroMusicWar": "",
			"DiplomacyMusicWar": "",
			"iPeaceWeightRand": 3,
			"iMaxGoldPerTurnTradePercent": 10,
			"iDeclareWarTradeRand": 40,
			"iAttackOddsChangeRand": 8,
			"iLostWarAttitudeChange": -1,
			"iAtWarAttitudeDivisor": -5,
			"iAtWarAttitudeChangeLimit": 5,
			"iAtPeaceAttitudeDivisor": 60,
			"iAtPeaceAttitudeChangeLimit": 1,
			"iSameReligionAttitudeChange": 1,
			"iSameReligionAttitudeDivisor": 10,
			"iDifferentReligionAttitudeChange": -1,
			"iDifferentReligionAttitudeDivisor": -15,
			"iBonusTradeAttitudeDivisor": 50,
			"iBonusTradeAttitudeChangeLimit": 2,
			"iOpenBordersAttitudeDivisor": 25,
			"iOpenBordersAttitudeChangeLimit": 2,
			"iDefensivePactAttitudeDivisor": 12,
			"iDefensivePactAttitudeChangeLimit": 2,
			"iShareWarAttitudeChange": 1,
			"iShareWarAttitudeDivisor": 8,
			"iFavoriteCivicAttitudeChange": 1,
			"iFavoriteCivicAttitudeDivisor": 10,
			"iDemandTributeAttitudeThreshold": 2,
			"iNoGiveHelpAttitudeThreshold": 2,
			"iPermanentAllianceRefuseAttitudeThreshold": 3,
			"iFreedomAppreciation": 10,
			"iNoWarAttitudeProbFurious": 0,
			"iLoveOfPeace": 0,
			"iFlavorReligion": 0,
			"iFlavorProduction": 0,
			"iFlavorGold": 0,
			"iFlavorCulture": 0,
			"iFlavorGrowth": 0,
			"iFlavorEspionage": 0,
			"iContactRandReligionPressure": 500,
			"iContactDelayReligionPressure": 50,
			"iContactRandCivicPressure": 250,
			"iContactDelayCivicPressure": 50,
			"iContactRandJoinWar": 20,
			"iContactDelayJoinWar": 20,
			"iContactRandStopTrading": 50,
			"iContactDelayStopTrading": 20,
			"iContactRandGiveHelp": 0,
			"iContactDelayGiveHelp": 50,
			"iContactRandAskForHelp": 1000,
			"iContactDelayAskForHelp": 50,
			"iContactRandDemandTribute": 1000,
			"iContactDelayDemandTribute": 50,
			"iContactRandTradeTech": 20,
			"iContactDelayTradeTech": 30,
			"iContactRandTradeBonus": 16,
			"iContactDelayTradeBonus": 20,
			"iContactRandPeaceTreaty": 25,
			"iContactDelayPeaceTreaty": 20,
			"iContactRandOpenBorders": 10,
			"iContactDelayOpenBorders": 40,
			"iContactRandDefensivePact": 80,
			"iContactDelayDefensivePact": 20,
			"iContactRandPermanentAlliance": 80,
			"iContactDelayPermanentAlliance": 20,
			"iContactRandTradeMap": 20,
			"iContactDelayTradeMap": 50,
			"iAggregatedContactProbReligionPressure": 52,
			"iAggregatedContactProbCivicPressure": 81,
			"iAggregatedContactProbJoinWar": 0,
			"iAggregatedContactProbStopTrading": 50,
			"iAggregatedContactProbGiveHelp": 0,
			"iAggregatedContactProbAskForHelp": 0,
			"iAggregatedContactProbDemandTribute": 11,
			"iAggregatedContactProbTradeTech": 0,
			"iAggregatedContactProbTradeBonus": 0,
			"iAggregatedContactProbPeaceTreaty": 0,
			"iAggregatedContactProbOpenBorders": 50,
			"iAggregatedContactProbDefensivePact": 50,
			"iAggregatedContactProbPermanentAlliance": 50,
			"iAggregatedContactProbTradeMap": 50,
			"iMemoryAttitudePercentGiveHelp": 100,
			"iMemoryDecayGiveHelp": 150,
			"iMemoryAttitudePercentAcceptDemand": 100,
			"iMemoryDecayAcceptDemand": 30,
			"iMemoryAttitudePercentAcceptedReligion": 100,
			"iMemoryDecayAcceptedReligion": 100,
			"iMemoryAttitudePercentAcceptedCivic": 100,
			"iMemoryDecayAcceptedCivic": 100,
			"iMemoryAttitudePercentAcceptedJoinWar": 100,
			"iMemoryDecayAcceptedJoinWar": 100,
			"iMemoryAttitudePercentAcceptedStopTrading": 50,
			"iMemoryDecayAcceptedStopTrading": 50,
			"iMemoryAttitudePercentTradedTechToUs": 5,
			"iMemoryDecayTradedTechToUs": 25,
			"iMemoryAttitudePercentVotedForUs": 200,
			"iMemoryDecayVotedForUs": 10,
			"iMemoryAttitudePercentEventGoodToUs": 100,
			"iMemoryDecayEventGoodToUs": 50,
			"iMemoryAttitudePercentLiberatedCities": 150,
			"iMemoryDecayLiberatedCities": 150,
			"iMemoryAttitudePercentIndependence": 100,
			"iMemoryDecayIndependence": 30,
			"iAggregatedPositiveMemoryGiveHelpAffection": 50,
			"iAggregatedPositiveMemoryAcceptDemandAffection": 50,
			"iAggregatedPositiveMemoryAcceptedReligionAffection": 50,
			"iAggregatedPositiveMemoryAcceptedCivicAffection": 50,
			"iAggregatedPositiveMemoryAcceptedJoinWarAffection": 50,
			"iAggregatedPositiveMemoryAcceptedStopTradingAffection": 50,
			"iAggregatedPositiveMemoryTradedTechToUsAffection": 0,
			"iAggregatedPositiveMemoryVotedForUsAffection": 50,
			"iAggregatedPositiveMemoryEventGoodToUsAffection": 50,
			"iAggregatedPositiveMemoryLiberatedCitiesAffection": 50,
			"iAggregatedPositiveMemoryIndependenceAffection": 50,
			"iAggregatedPositiveMemoryGiveHelpResentment": 50,
			"iAggregatedPositiveMemoryAcceptDemandResentment": 50,
			"iAggregatedPositiveMemoryAcceptedReligionResentment": 50,
			"iAggregatedPositiveMemoryAcceptedCivicResentment": 50,
			"iAggregatedPositiveMemoryAcceptedJoinWarResentment": 50,
			"iAggregatedPositiveMemoryAcceptedStopTradingResentment": 50,
			"iAggregatedPositiveMemoryTradedTechToUsResentment": 50,
			"iAggregatedPositiveMemoryVotedForUsResentment": 50,
			"iAggregatedPositiveMemoryEventGoodToUsResentment": 50,
			"iAggregatedPositiveMemoryLiberatedCitiesResentment": 50,
			"iAggregatedPositiveMemoryIndependenceResentment": 50,
			"iMemoryAttitudePercentDeclaredWar": -300,
			"iMemoryDecayDeclaredWar": 150,
			"iMemoryAttitudePercentDeclaredWarOnFriend": -100,
			"iMemoryDecayDeclaredWarOnFriend": 120,
			"iMemoryAttitudePercentHiredWarAlly": -200,
			"iMemoryDecayHiredWarAlly": 75,
			"iMemoryAttitudePercentNukedUs": -200,
			"iMemoryDecayNukedUs": 120,
			"iMemoryAttitudePercentNukedFriend": -100,
			"iMemoryDecayNukedFriend": 80,
			"iMemoryAttitudePercentRazedCity": -250,
			"iMemoryDecayRazedCity": 75,
			"iMemoryAttitudePercentRazedHolyCity": -200,
			"iMemoryDecayRazedHolyCity": 150,
			"iMemoryAttitudePercentSpyCaught": -100,
			"iMemoryDecaySpyCaught": 40,
			"iMemoryAttitudePercentRefusedHelp": -200,
			"iMemoryDecayRefusedHelp": 100,
			"iMemoryAttitudePercentRejectedDemand": -200,
			"iMemoryDecayRejectedDemand": 90,
			"iMemoryAttitudePercentDeniedReligion": -200,
			"iMemoryDecayDeniedReligion": 50,
			"iMemoryAttitudePercentDeniedCivic": -200,
			"iMemoryDecayDeniedCivic": 50,
			"iMemoryAttitudePercentDeniedJoinWar": -200,
			"iMemoryDecayDeniedJoinWar": 100,
			"iMemoryAttitudePercentDeniedStopTrading": -200,
			"iMemoryDecayDeniedStopTrading": 50,
			"iMemoryAttitudePercentStoppedTrading": -100,
			"iMemoryDecayStoppedTrading": 60,
			"iMemoryAttitudePercentStoppedTradingRecent": 0,
			"iMemoryDecayStoppedTradingRecent": 18,
			"iMemoryAttitudePercentHiredTradeEmbargo": -100,
			"iMemoryDecayHiredTradeEmbargo": 60,
			"iMemoryAttitudePercentMadeDemand": -150,
			"iMemoryDecayMadeDemand": 30,
			"iMemoryAttitudePercentCancelledVassalAgreement": 0,
			"iMemoryDecayCancelledVassalAgreement": 10,
			"iMemoryAttitudePercentMadeDemandRecent": 0,
			"iMemoryDecayMadeDemandRecent": 20,
			"iMemoryAttitudePercentCancelledOpenBorders": 0,
			"iMemoryDecayCancelledOpenBorders": 10,
			"iMemoryAttitudePercentCancelledDefensivePact": 0,
			"iMemoryDecayCancelledDefensivePact": 10,
			"iMemoryAttitudePercentReceivedTechFromAny": 0,
			"iMemoryDecayReceivedTechFromAny": 20,
			"iMemoryAttitudePercentVotedAgainstUs": -200,
			"iMemoryDecayVotedAgainstUs": 10,
			"iMemoryAttitudePercentEventBadToUs": -100,
			"iMemoryDecayEventBadToUs": 50,
			"iMemoryAttitudePercentDeclaredWarRecent": 0,
			"iMemoryDecayDeclaredWarRecent": 11,
			"iAggregatedNegativeMemoryDeclaredWarAffection": 50,
			"iAggregatedNegativeMemoryDeclaredWarOnFriendAffection": 50,
			"iAggregatedNegativeMemoryHiredWarAllyAffection": 50,
			"iAggregatedNegativeMemoryNukedUsAffection": 50,
			"iAggregatedNegativeMemoryNukedFriendAffection": 50,
			"iAggregatedNegativeMemoryRazedCityAffection": 50,
			"iAggregatedNegativeMemoryRazedHolyCityAffection": 50,
			"iAggregatedNegativeMemorySpyCaughtAffection": 50,
			"iAggregatedNegativeMemoryRefusedHelpAffection": 50,
			"iAggregatedNegativeMemoryRejectedDemandAffection": 50,
			"iAggregatedNegativeMemoryDeniedReligionAffection": 50,
			"iAggregatedNegativeMemoryDeniedCivicAffection": 50,
			"iAggregatedNegativeMemoryDeniedJoinWarAffection": 50,
			"iAggregatedNegativeMemoryDeniedStopTradingAffection": 50,
			"iAggregatedNegativeMemoryStoppedTradingAffection": 50,
			"iAggregatedNegativeMemoryStoppedTradingRecentAffection": 50,
			"iAggregatedNegativeMemoryHiredTradeEmbargoAffection": 50,
			"iAggregatedNegativeMemoryMadeDemandAffection": 50,
			"iAggregatedNegativeMemoryCancelledVassalAgreementAffection": 50,
			"iAggregatedNegativeMemoryMadeDemandRecentAffection": 50,
			"iAggregatedNegativeMemoryCancelledOpenBordersAffection": 50,
			"iAggregatedNegativeMemoryCancelledDefensivePactAffection": 50,
			"iAggregatedNegativeMemoryReceivedTechFromAnyAffection": 50,
			"iAggregatedNegativeMemoryVotedAgainstUsAffection": 50,
			"iAggregatedNegativeMemoryEventBadToUsAffection": 50,
			"iAggregatedNegativeMemoryDeclaredWarRecentAffection": 50,
			"iAggregatedNegativeMemoryDeclaredWarResentment": 50,
			"iAggregatedNegativeMemoryDeclaredWarOnFriendResentment": 0,
			"iAggregatedNegativeMemoryHiredWarAllyResentment": 50,
			"iAggregatedNegativeMemoryNukedUsResentment": 50,
			"iAggregatedNegativeMemoryNukedFriendResentment": 0,
			"iAggregatedNegativeMemoryRazedCityResentment": 50,
			"iAggregatedNegativeMemoryRazedHolyCityResentment": 50,
			"iAggregatedNegativeMemorySpyCaughtResentment": 0,
			"iAggregatedNegativeMemoryRefusedHelpResentment": 100,
			"iAggregatedNegativeMemoryRejectedDemandResentment": 100,
			"iAggregatedNegativeMemoryDeniedReligionResentment": 100,
			"iAggregatedNegativeMemoryDeniedCivicResentment": 100,
			"iAggregatedNegativeMemoryDeniedJoinWarResentment": 100,
			"iAggregatedNegativeMemoryDeniedStopTradingResentment": 100,
			"iAggregatedNegativeMemoryStoppedTradingResentment": 100,
			"iAggregatedNegativeMemoryStoppedTradingRecentResentment": 50,
			"iAggregatedNegativeMemoryHiredTradeEmbargoResentment": 50,
			"iAggregatedNegativeMemoryMadeDemandResentment": 50,
			"iAggregatedNegativeMemoryCancelledVassalAgreementResentment": 50,
			"iAggregatedNegativeMemoryMadeDemandRecentResentment": 50,
			"iAggregatedNegativeMemoryCancelledOpenBordersResentment": 50,
			"iAggregatedNegativeMemoryCancelledDefensivePactResentment": 50,
			"iAggregatedNegativeMemoryReceivedTechFromAnyResentment": 50,
			"iAggregatedNegativeMemoryVotedAgainstUsResentment": 100,
			"iAggregatedNegativeMemoryEventBadToUsResentment": 50,
			"iAggregatedNegativeMemoryDeclaredWarRecentResentment": 50
		},
    }
