# <!-- custom: --- Test data module of expected parsed leaders_data py output to test against the real parsed leaders data py file during its creation --> --- 
# (c) 2025 wonderingabout & becomingthrough

def get_expected_output_PARSED_XML_LEADERS_DATA_SAMPLE():
	return {
		"LEADER_BARBARIAN": {
			"Type": "LEADER_BARBARIAN",
			"Description": "TXT_KEY_LEADER_BARBARIAN",
			"Civilopedia": "TXT_KEY_LEADER_BARBARIAN_PEDIA",
			"ArtDefineTag": "ART_DEF_LEADER_BARBARIAN",
			"iWonderConstructRand": 0,
			"iBaseAttitude": 0,
			"iBasePeaceWeight": 0,
			"iPeaceWeightRand": 0,
			"iWarmongerRespect": 0,
			"iEspionageWeight": 0,
			"iRefuseToTalkWarThreshold": 0,
			"iNoTechTradeThreshold": 0,
			"iTechTradeKnownPercent": 0,
			"iMaxGoldTradePercent": 0,
			"iMaxGoldPerTurnTradePercent": 0,
			"iCultureVictoryWeight": 0,
			"iSpaceVictoryWeight": 0,
			"iConquestVictoryWeight": 70,
			"iDominationVictoryWeight": 30,
			"iDiplomacyVictoryWeight": 0,
			"iMaxWarRand": 0,
			"iMaxWarNearbyPowerRatio": 0,
			"iMaxWarDistantPowerRatio": 0,
			"iMaxWarMinAdjacentLandPercent": 0,
			"iLimitedWarRand": 0,
			"iLimitedWarPowerRatio": 0,
			"iDogpileWarRand": 0,
			"iMakePeaceRand": 0,
			"iDeclareWarTradeRand": 0,
			"iDemandRebukedSneakProb": 0,
			"iDemandRebukedWarProb": 0,
			"iRazeCityProb": 75,
			"iBuildUnitProb": 70,
			"iBaseAttackOddsChange": 1,
			"iAttackOddsChangeRand": 16,
			"iWorseRankDifferenceAttitudeChange": -2,
			"iBetterRankDifferenceAttitudeChange": 0,
			"iCloseBordersAttitudeChange": -2,
			"iLostWarAttitudeChange": 0,
			"iAtWarAttitudeDivisor": 0,
			"iAtWarAttitudeChangeLimit": 0,
			"iAtPeaceAttitudeDivisor": 0,
			"iAtPeaceAttitudeChangeLimit": 0,
			"iSameReligionAttitudeChange": 0,
			"iSameReligionAttitudeDivisor": 0,
			"iSameReligionAttitudeChangeLimit": 0,
			"iDifferentReligionAttitudeChange": 0,
			"iDifferentReligionAttitudeDivisor": 0,
			"iDifferentReligionAttitudeChangeLimit": 0,
			"iBonusTradeAttitudeDivisor": 0,
			"iBonusTradeAttitudeChangeLimit": 0,
			"iOpenBordersAttitudeDivisor": 0,
			"iOpenBordersAttitudeChangeLimit": 0,
			"iDefensivePactAttitudeDivisor": 0,
			"iDefensivePactAttitudeChangeLimit": 0,
			"iShareWarAttitudeChange": 0,
			"iShareWarAttitudeDivisor": 0,
			"iShareWarAttitudeChangeLimit": 0,
			"iFavoriteCivicAttitudeChange": 0,
			"iFavoriteCivicAttitudeDivisor": 0,
			"iFavoriteCivicAttitudeChangeLimit": 0,
			"iDemandTributeAttitudeThreshold": -3,
			"iNoGiveHelpAttitudeThreshold": -3,
			"iTechRefuseAttitudeThreshold": -3,
			"iCityRefuseAttitudeThreshold": -3,
			"iNativeCityRefuseAttitudeThreshold": -3,
			"iStrategicBonusRefuseAttitudeThreshold": -3,
			"iHappinessBonusRefuseAttitudeThreshold": -3,
			"iHealthBonusRefuseAttitudeThreshold": -3,
			"iMapRefuseAttitudeThreshold": -3,
			"iDeclareWarRefuseAttitudeThreshold": -3,
			"iDeclareWarThemRefuseAttitudeThreshold": -3,
			"iStopTradingRefuseAttitudeThreshold": -3,
			"iStopTradingThemRefuseAttitudeThreshold": -3,
			"iAdoptCivicRefuseAttitudeThreshold": -3,
			"iConvertReligionRefuseAttitudeThreshold": -3,
			"iOpenBordersRefuseAttitudeThreshold": -3,
			"iDefensivePactRefuseAttitudeThreshold": -3,
			"iPermanentAllianceRefuseAttitudeThreshold": -3,
			"iVassalRefuseAttitudeThreshold": -3,
			"iVassalPowerModifier": 0,
			"iFreedomAppreciation": 0,
			"FavoriteCivic": "NONE",
			"FavoriteReligion": "NONE",
			"Traits": "",
			"iFlavorMilitary": 10,
			"iNoWarAttitudeProbFurious": 0,
			"iNoWarAttitudeProbAnnoyed": 0,
			"iNoWarAttitudeProbCautious": 0,
			"iNoWarAttitudeProbPleased": 0,
			"iNoWarAttitudeProbFriendly": 100,
			"UnitAIWeightModifiers": [
				{
					"UnitAIType": "UNITAI_RESERVE",
					"iWeightModifier": "75"
				},
				{
					"UnitAIType": "UNITAI_ATTACK_CITY",
					"iWeightModifier": "75"
				},
				{
					"UnitAIType": "UNITAI_WORKER",
					"iWeightModifier": "75"
				}
			],
			"ImprovementWeightModifiers": "",
			"DiplomacyIntroMusicPeace": "",
			"DiplomacyMusicPeace": [
				{
					"EraType": "ERA_ANCIENT",
					"DiploScriptId": "AS2D_DIPLO_RAGNAR_EARLY"
				},
				{
					"EraType": "ERA_CLASSICAL",
					"DiploScriptId": "AS2D_DIPLO_RAGNAR_EARLY"
				},
				{
					"EraType": "ERA_MEDIEVAL",
					"DiploScriptId": "AS2D_DIPLO_RAGNAR_MIDDLE"
				},
				{
					"EraType": "ERA_RENAISSANCE",
					"DiploScriptId": "AS2D_DIPLO_RAGNAR_MIDDLE"
				},
				{
					"EraType": "ERA_INDUSTRIAL",
					"DiploScriptId": "AS2D_DIPLO_RAGNAR_LATE"
				},
				{
					"EraType": "ERA_MODERN",
					"DiploScriptId": "AS2D_DIPLO_RAGNAR_LATE"
				},
				{
					"EraType": "ERA_FUTURE",
					"DiploScriptId": "AS2D_DIPLO_RAGNAR_LATE"
				}
			],
			"DiplomacyIntroMusicWar": "",
			"DiplomacyMusicWar": [
				{
					"EraType": "ERA_ANCIENT",
					"DiploScriptId": "AS2D_DIPLO_WARDRUMS_EARLY"
				},
				{
					"EraType": "ERA_CLASSICAL",
					"DiploScriptId": "AS2D_DIPLO_WARDRUMS_EARLY"
				},
				{
					"EraType": "ERA_MEDIEVAL",
					"DiploScriptId": "AS2D_DIPLO_WARDRUMS_MIDDLE"
				},
				{
					"EraType": "ERA_RENAISSANCE",
					"DiploScriptId": "AS2D_DIPLO_WARDRUMS_MIDDLE"
				},
				{
					"EraType": "ERA_INDUSTRIAL",
					"DiploScriptId": "AS2D_DIPLO_WARDRUMS_LATE"
				},
				{
					"EraType": "ERA_MODERN",
					"DiploScriptId": "AS2D_DIPLO_WARDRUMS_LATE"
				},
				{
					"EraType": "ERA_FUTURE",
					"DiploScriptId": "AS2D_DIPLO_WARDRUMS_LATE"
				}
			],
			"iLoveOfPeace": 0,
			"iFlavorReligion": 0,
			"iFlavorProduction": 0,
			"iFlavorGold": 0,
			"iFlavorScience": 0,
			"iFlavorCulture": 0,
			"iFlavorGrowth": 0,
			"iFlavorEspionage": 0,
			"iContactReligionPressureDelayRaw": 50,
			"iContactReligionPressureRandRaw": -1,
			"iContactCivicPressureDelayRaw": 50,
			"iContactCivicPressureRandRaw": -1,
			"iContactJoinWarDelayRaw": 20,
			"iContactJoinWarRandRaw": -1,
			"iContactStopTradingDelayRaw": 20,
			"iContactStopTradingRandRaw": -1,
			"iContactGiveHelpDelayRaw": 50,
			"iContactGiveHelpRandRaw": -1,
			"iContactAskForHelpDelayRaw": 50,
			"iContactAskForHelpRandRaw": -1,
			"iContactDemandTributeDelayRaw": 50,
			"iContactDemandTributeRandRaw": -1,
			"iContactTradeTechDelayRaw": 30,
			"iContactTradeTechRandRaw": -1,
			"iContactTradeBonusDelayRaw": 20,
			"iContactTradeBonusRandRaw": -1,
			"iContactPeaceTreatyDelayRaw": -1,
			"iContactPeaceTreatyRandRaw": -1,
			"iContactOpenBordersDelayRaw": 40,
			"iContactOpenBordersRandRaw": 10,
			"iContactDefensivePactDelayRaw": 20,
			"iContactDefensivePactRandRaw": 80,
			"iContactPermanentAllianceDelayRaw": 20,
			"iContactPermanentAllianceRandRaw": 80,
			"iContactTradeMapDelayRaw": 50,
			"iContactTradeMapRandRaw": 20,
			"iAggregatedContactReligionPressureProb": -999,
			"iAggregatedContactCivicPressureProb": -999,
			"iAggregatedContactJoinWarProb": -999,
			"iAggregatedContactStopTradingProb": -999,
			"iAggregatedContactGiveHelpProb": -999,
			"iAggregatedContactAskForHelpProb": -999,
			"iAggregatedContactDemandTributeProb": -999,
			"iAggregatedContactTradeTechProb": -999,
			"iAggregatedContactTradeBonusProb": -999,
			"iAggregatedContactPeaceTreatyProb": -999,
			"iAggregatedContactOpenBordersProb": -999,
			"iAggregatedContactDefensivePactProb": -999,
			"iAggregatedContactPermanentAllianceProb": -999,
			"iAggregatedContactTradeMapProb": -999,
			"iPositiveMemoryAttitudeGiveHelpRaw": 100,
			"iPositiveMemoryDecayGiveHelpRaw": 150,
			"iPositiveMemoryAttitudeAcceptDemandRaw": 100,
			"iPositiveMemoryDecayAcceptDemandRaw": 30,
			"iPositiveMemoryAttitudeAcceptedReligionRaw": 100,
			"iPositiveMemoryDecayAcceptedReligionRaw": 100,
			"iPositiveMemoryAttitudeAcceptedCivicRaw": 100,
			"iPositiveMemoryDecayAcceptedCivicRaw": 100,
			"iPositiveMemoryAttitudeAcceptedJoinWarRaw": 100,
			"iPositiveMemoryDecayAcceptedJoinWarRaw": 100,
			"iPositiveMemoryAttitudeAcceptedStopTradingRaw": 50,
			"iPositiveMemoryDecayAcceptedStopTradingRaw": 50,
			"iPositiveMemoryAttitudeVotedForUsRaw": 200,
			"iPositiveMemoryDecayVotedForUsRaw": 10,
			"iPositiveMemoryAttitudeEventGoodToUsRaw": 100,
			"iPositiveMemoryDecayEventGoodToUsRaw": 50,
			"iPositiveMemoryAttitudeLiberatedCitiesRaw": 150,
			"iPositiveMemoryDecayLiberatedCitiesRaw": 150,
			"iPositiveMemoryAttitudeIndependenceRaw": 100,
			"iPositiveMemoryDecayIndependenceRaw": 30,
			"iPositiveMemoryAttitudeTradedTechToUsRaw": -1,
			"iPositiveMemoryDecayTradedTechToUsRaw": 25,
			"iAggregatedPositiveMemoryGiveHelpAffection": -999,
			"iAggregatedPositiveMemoryAcceptDemandAffection": -999,
			"iAggregatedPositiveMemoryAcceptedReligionAffection": -999,
			"iAggregatedPositiveMemoryAcceptedCivicAffection": -999,
			"iAggregatedPositiveMemoryAcceptedJoinWarAffection": -999,
			"iAggregatedPositiveMemoryAcceptedStopTradingAffection": -999,
			"iAggregatedPositiveMemoryVotedForUsAffection": -999,
			"iAggregatedPositiveMemoryEventGoodToUsAffection": -999,
			"iAggregatedPositiveMemoryLiberatedCitiesAffection": -999,
			"iAggregatedPositiveMemoryIndependenceAffection": -999,
			"iAggregatedPositiveMemoryTradedTechToUsAffection": -999,
			"iAggregatedPositiveMemoryGiveHelpResentment": -999,
			"iAggregatedPositiveMemoryAcceptDemandResentment": -999,
			"iAggregatedPositiveMemoryAcceptedReligionResentment": -999,
			"iAggregatedPositiveMemoryAcceptedCivicResentment": -999,
			"iAggregatedPositiveMemoryAcceptedJoinWarResentment": -999,
			"iAggregatedPositiveMemoryAcceptedStopTradingResentment": -999,
			"iAggregatedPositiveMemoryVotedForUsResentment": -999,
			"iAggregatedPositiveMemoryEventGoodToUsResentment": -999,
			"iAggregatedPositiveMemoryLiberatedCitiesResentment": -999,
			"iAggregatedPositiveMemoryIndependenceResentment": -999,
			"iAggregatedPositiveMemoryTradedTechToUsResentment": -999,
			"iNegativeMemoryAttitudeDeclaredWarRaw": -300,
			"iNegativeMemoryDecayDeclaredWarRaw": 150,
			"iNegativeMemoryAttitudeDeclaredWarOnFriendRaw": -100,
			"iNegativeMemoryDecayDeclaredWarOnFriendRaw": 120,
			"iNegativeMemoryAttitudeHiredWarAllyRaw": -200,
			"iNegativeMemoryDecayHiredWarAllyRaw": 75,
			"iNegativeMemoryAttitudeNukedUsRaw": -200,
			"iNegativeMemoryDecayNukedUsRaw": 120,
			"iNegativeMemoryAttitudeNukedFriendRaw": -100,
			"iNegativeMemoryDecayNukedFriendRaw": 80,
			"iNegativeMemoryAttitudeRazedCityRaw": -250,
			"iNegativeMemoryDecayRazedCityRaw": 75,
			"iNegativeMemoryAttitudeRazedHolyCityRaw": -200,
			"iNegativeMemoryDecayRazedHolyCityRaw": 150,
			"iNegativeMemoryAttitudeSpyCaughtRaw": -100,
			"iNegativeMemoryDecaySpyCaughtRaw": 40,
			"iNegativeMemoryAttitudeRefusedHelpRaw": -100,
			"iNegativeMemoryDecayRefusedHelpRaw": 100,
			"iNegativeMemoryAttitudeRejectedDemandRaw": -100,
			"iNegativeMemoryDecayRejectedDemandRaw": 90,
			"iNegativeMemoryAttitudeDeniedReligionRaw": -100,
			"iNegativeMemoryDecayDeniedReligionRaw": 50,
			"iNegativeMemoryAttitudeDeniedCivicRaw": -100,
			"iNegativeMemoryDecayDeniedCivicRaw": 50,
			"iNegativeMemoryAttitudeDeniedJoinWarRaw": -100,
			"iNegativeMemoryDecayDeniedJoinWarRaw": 100,
			"iNegativeMemoryAttitudeDeniedStopTradingRaw": -100,
			"iNegativeMemoryDecayDeniedStopTradingRaw": 50,
			"iNegativeMemoryAttitudeStoppedTradingRecentRaw": 0,
			"iNegativeMemoryDecayStoppedTradingRecentRaw": 18,
			"iNegativeMemoryAttitudeStoppedTradingRaw": -100,
			"iNegativeMemoryDecayStoppedTradingRaw": 60,
			"iNegativeMemoryAttitudeHiredTradeEmbargoRaw": -100,
			"iNegativeMemoryDecayHiredTradeEmbargoRaw": 60,
			"iNegativeMemoryAttitudeMadeDemandRaw": -100,
			"iNegativeMemoryDecayMadeDemandRaw": 30,
			"iNegativeMemoryAttitudeMadeDemandRecentRaw": 0,
			"iNegativeMemoryDecayMadeDemandRecentRaw": 20,
			"iNegativeMemoryAttitudeVotedAgainstUsRaw": -200,
			"iNegativeMemoryDecayVotedAgainstUsRaw": 10,
			"iNegativeMemoryAttitudeEventBadToUsRaw": -100,
			"iNegativeMemoryDecayEventBadToUsRaw": 50,
			"iNegativeMemoryAttitudeCancelledOpenBordersRaw": 0,
			"iNegativeMemoryDecayCancelledOpenBordersRaw": 10,
			"iNegativeMemoryAttitudeCancelledVassalAgreementRaw": 0,
			"iNegativeMemoryDecayCancelledVassalAgreementRaw": 10,
			"iNegativeMemoryAttitudeCancelledDefensivePactRaw": 0,
			"iNegativeMemoryDecayCancelledDefensivePactRaw": 10,
			"iNegativeMemoryAttitudeDeclaredWarRecentRaw": 0,
			"iNegativeMemoryDecayDeclaredWarRecentRaw": 11,
			"iNegativeMemoryAttitudeReceivedTechFromAnyRaw": 0,
			"iNegativeMemoryDecayReceivedTechFromAnyRaw": 20,
			"iAggregatedNegativeMemoryDeclaredWarAffection": -999,
			"iAggregatedNegativeMemoryDeclaredWarOnFriendAffection": -999,
			"iAggregatedNegativeMemoryHiredWarAllyAffection": -999,
			"iAggregatedNegativeMemoryNukedUsAffection": -999,
			"iAggregatedNegativeMemoryNukedFriendAffection": -999,
			"iAggregatedNegativeMemoryRazedCityAffection": -999,
			"iAggregatedNegativeMemoryRazedHolyCityAffection": -999,
			"iAggregatedNegativeMemorySpyCaughtAffection": -999,
			"iAggregatedNegativeMemoryRefusedHelpAffection": -999,
			"iAggregatedNegativeMemoryRejectedDemandAffection": -999,
			"iAggregatedNegativeMemoryDeniedReligionAffection": -999,
			"iAggregatedNegativeMemoryDeniedCivicAffection": -999,
			"iAggregatedNegativeMemoryDeniedJoinWarAffection": -999,
			"iAggregatedNegativeMemoryDeniedStopTradingAffection": -999,
			"iAggregatedNegativeMemoryStoppedTradingRecentAffection": -999,
			"iAggregatedNegativeMemoryStoppedTradingAffection": -999,
			"iAggregatedNegativeMemoryHiredTradeEmbargoAffection": -999,
			"iAggregatedNegativeMemoryMadeDemandAffection": -999,
			"iAggregatedNegativeMemoryMadeDemandRecentAffection": -999,
			"iAggregatedNegativeMemoryVotedAgainstUsAffection": -999,
			"iAggregatedNegativeMemoryEventBadToUsAffection": -999,
			"iAggregatedNegativeMemoryCancelledOpenBordersAffection": -999,
			"iAggregatedNegativeMemoryCancelledVassalAgreementAffection": -999,
			"iAggregatedNegativeMemoryCancelledDefensivePactAffection": -999,
			"iAggregatedNegativeMemoryDeclaredWarRecentAffection": -999,
			"iAggregatedNegativeMemoryReceivedTechFromAnyAffection": -999,
			"iAggregatedNegativeMemoryDeclaredWarResentment": -999,
			"iAggregatedNegativeMemoryDeclaredWarOnFriendResentment": -999,
			"iAggregatedNegativeMemoryHiredWarAllyResentment": -999,
			"iAggregatedNegativeMemoryNukedUsResentment": -999,
			"iAggregatedNegativeMemoryNukedFriendResentment": -999,
			"iAggregatedNegativeMemoryRazedCityResentment": -999,
			"iAggregatedNegativeMemoryRazedHolyCityResentment": -999,
			"iAggregatedNegativeMemorySpyCaughtResentment": -999,
			"iAggregatedNegativeMemoryRefusedHelpResentment": -999,
			"iAggregatedNegativeMemoryRejectedDemandResentment": -999,
			"iAggregatedNegativeMemoryDeniedReligionResentment": -999,
			"iAggregatedNegativeMemoryDeniedCivicResentment": -999,
			"iAggregatedNegativeMemoryDeniedJoinWarResentment": -999,
			"iAggregatedNegativeMemoryDeniedStopTradingResentment": -999,
			"iAggregatedNegativeMemoryStoppedTradingRecentResentment": -999,
			"iAggregatedNegativeMemoryStoppedTradingResentment": -999,
			"iAggregatedNegativeMemoryHiredTradeEmbargoResentment": -999,
			"iAggregatedNegativeMemoryMadeDemandResentment": -999,
			"iAggregatedNegativeMemoryMadeDemandRecentResentment": -999,
			"iAggregatedNegativeMemoryVotedAgainstUsResentment": -999,
			"iAggregatedNegativeMemoryEventBadToUsResentment": -999,
			"iAggregatedNegativeMemoryCancelledOpenBordersResentment": -999,
			"iAggregatedNegativeMemoryCancelledVassalAgreementResentment": -999,
			"iAggregatedNegativeMemoryCancelledDefensivePactResentment": -999,
			"iAggregatedNegativeMemoryDeclaredWarRecentResentment": -999,
			"iAggregatedNegativeMemoryReceivedTechFromAnyResentment": -999
		},
		"LEADER_DEFAULTS": {
			"Type": "LEADER_DEFAULTS",
			"Description": "",
			"Civilopedia": "",
			"ArtDefineTag": "",
			"iWonderConstructRand": 0,
			"iBaseAttitude": 0,
			"iBasePeaceWeight": 0,
			"iPeaceWeightRand": 3,
			"iWarmongerRespect": 0,
			"iEspionageWeight": 0,
			"iRefuseToTalkWarThreshold": 0,
			"iNoTechTradeThreshold": 0,
			"iTechTradeKnownPercent": 0,
			"iMaxGoldTradePercent": 0,
			"iMaxGoldPerTurnTradePercent": 10,
			"iCultureVictoryWeight": 30,
			"iSpaceVictoryWeight": 30,
			"iConquestVictoryWeight": 30,
			"iDominationVictoryWeight": 30,
			"iDiplomacyVictoryWeight": 30,
			"iMaxWarRand": 0,
			"iMaxWarNearbyPowerRatio": 0,
			"iMaxWarDistantPowerRatio": 0,
			"iMaxWarMinAdjacentLandPercent": 0,
			"iLimitedWarRand": 0,
			"iLimitedWarPowerRatio": 0,
			"iDogpileWarRand": 0,
			"iMakePeaceRand": 0,
			"iDeclareWarTradeRand": 40,
			"iDemandRebukedSneakProb": 0,
			"iDemandRebukedWarProb": 0,
			"iRazeCityProb": 0,
			"iBuildUnitProb": 0,
			"iBaseAttackOddsChange": 0,
			"iAttackOddsChangeRand": 8,
			"iWorseRankDifferenceAttitudeChange": 0,
			"iBetterRankDifferenceAttitudeChange": 0,
			"iCloseBordersAttitudeChange": 0,
			"iLostWarAttitudeChange": -1,
			"iAtWarAttitudeDivisor": -5,
			"iAtWarAttitudeChangeLimit": 5,
			"iAtPeaceAttitudeDivisor": 60,
			"iAtPeaceAttitudeChangeLimit": 1,
			"iSameReligionAttitudeChange": 1,
			"iSameReligionAttitudeDivisor": 10,
			"iSameReligionAttitudeChangeLimit": 0,
			"iDifferentReligionAttitudeChange": -1,
			"iDifferentReligionAttitudeDivisor": -15,
			"iDifferentReligionAttitudeChangeLimit": 0,
			"iBonusTradeAttitudeDivisor": 50,
			"iBonusTradeAttitudeChangeLimit": 2,
			"iOpenBordersAttitudeDivisor": 25,
			"iOpenBordersAttitudeChangeLimit": 2,
			"iDefensivePactAttitudeDivisor": 12,
			"iDefensivePactAttitudeChangeLimit": 2,
			"iShareWarAttitudeChange": 1,
			"iShareWarAttitudeDivisor": 8,
			"iShareWarAttitudeChangeLimit": 0,
			"iFavoriteCivicAttitudeChange": 1,
			"iFavoriteCivicAttitudeDivisor": 10,
			"iFavoriteCivicAttitudeChangeLimit": 0,
			"iDemandTributeAttitudeThreshold": 0,
			"iNoGiveHelpAttitudeThreshold": 0,
			"iTechRefuseAttitudeThreshold": -3,
			"iCityRefuseAttitudeThreshold": 0,
			"iNativeCityRefuseAttitudeThreshold": 1,
			"iStrategicBonusRefuseAttitudeThreshold": -3,
			"iHappinessBonusRefuseAttitudeThreshold": -3,
			"iHealthBonusRefuseAttitudeThreshold": -3,
			"iMapRefuseAttitudeThreshold": -3,
			"iDeclareWarRefuseAttitudeThreshold": -3,
			"iDeclareWarThemRefuseAttitudeThreshold": -3,
			"iStopTradingRefuseAttitudeThreshold": -3,
			"iStopTradingThemRefuseAttitudeThreshold": -3,
			"iAdoptCivicRefuseAttitudeThreshold": -3,
			"iConvertReligionRefuseAttitudeThreshold": -3,
			"iOpenBordersRefuseAttitudeThreshold": -3,
			"iDefensivePactRefuseAttitudeThreshold": 1,
			"iPermanentAllianceRefuseAttitudeThreshold": 1,
			"iVassalRefuseAttitudeThreshold": -3,
			"iVassalPowerModifier": 0,
			"iFreedomAppreciation": 10,
			"FavoriteCivic": "NONE",
			"FavoriteReligion": "NONE",
			"Traits": "",
			"iFlavorMilitary": 0,
			"iFlavorReligion": 0,
			"iFlavorProduction": 0,
			"iFlavorGold": 0,
			"iFlavorScience": 0,
			"iFlavorCulture": 0,
			"iFlavorGrowth": 0,
			"iFlavorEspionage": 0,
			"iNoWarAttitudeProbFurious": 0,
			"iNoWarAttitudeProbAnnoyed": 0,
			"iNoWarAttitudeProbCautious": 0,
			"iNoWarAttitudeProbPleased": 0,
			"iNoWarAttitudeProbFriendly": 100,
			"iLoveOfPeace": 0,
			"UnitAIWeightModifiers": "",
			"ImprovementWeightModifiers": "",
			"DiplomacyIntroMusicPeace": [
				{
					"EraType": "ERA_ANCIENT"
				},
				{
					"EraType": "ERA_CLASSICAL"
				},
				{
					"EraType": "ERA_MEDIEVAL"
				},
				{
					"EraType": "ERA_RENAISSANCE"
				},
				{
					"EraType": "ERA_INDUSTRIAL"
				},
				{
					"EraType": "ERA_MODERN"
				},
				{
					"EraType": "ERA_FUTURE"
				}
			],
			"DiplomacyMusicPeace": [
				{
					"EraType": "ERA_ANCIENT"
				},
				{
					"EraType": "ERA_CLASSICAL"
				},
				{
					"EraType": "ERA_MEDIEVAL"
				},
				{
					"EraType": "ERA_RENAISSANCE"
				},
				{
					"EraType": "ERA_INDUSTRIAL"
				},
				{
					"EraType": "ERA_MODERN"
				},
				{
					"EraType": "ERA_FUTURE"
				}
			],
			"DiplomacyIntroMusicWar": [
				{
					"EraType": "ERA_ANCIENT"
				},
				{
					"EraType": "ERA_CLASSICAL"
				},
				{
					"EraType": "ERA_MEDIEVAL"
				},
				{
					"EraType": "ERA_RENAISSANCE"
				},
				{
					"EraType": "ERA_INDUSTRIAL"
				},
				{
					"EraType": "ERA_MODERN"
				},
				{
					"EraType": "ERA_FUTURE"
				}
			],
			"DiplomacyMusicWar": [
				{
					"EraType": "ERA_ANCIENT",
					"DiploScriptId": "AS2D_DIPLO_WARDRUMS_EARLY"
				},
				{
					"EraType": "ERA_CLASSICAL",
					"DiploScriptId": "AS2D_DIPLO_WARDRUMS_EARLY"
				},
				{
					"EraType": "ERA_MEDIEVAL",
					"DiploScriptId": "AS2D_DIPLO_WARDRUMS_MIDDLE"
				},
				{
					"EraType": "ERA_RENAISSANCE",
					"DiploScriptId": "AS2D_DIPLO_WARDRUMS_MIDDLE"
				},
				{
					"EraType": "ERA_INDUSTRIAL",
					"DiploScriptId": "AS2D_DIPLO_WARDRUMS_LATE"
				},
				{
					"EraType": "ERA_MODERN",
					"DiploScriptId": "AS2D_DIPLO_WARDRUMS_LATE"
				},
				{
					"EraType": "ERA_FUTURE",
					"DiploScriptId": "AS2D_DIPLO_WARDRUMS_LATE"
				}
			],
			"iContactReligionPressureDelayRaw": 50,
			"iContactReligionPressureRandRaw": -1,
			"iContactCivicPressureDelayRaw": 50,
			"iContactCivicPressureRandRaw": -1,
			"iContactJoinWarDelayRaw": 20,
			"iContactJoinWarRandRaw": -1,
			"iContactStopTradingDelayRaw": 20,
			"iContactStopTradingRandRaw": -1,
			"iContactGiveHelpDelayRaw": 50,
			"iContactGiveHelpRandRaw": -1,
			"iContactAskForHelpDelayRaw": 50,
			"iContactAskForHelpRandRaw": -1,
			"iContactDemandTributeDelayRaw": 50,
			"iContactDemandTributeRandRaw": -1,
			"iContactTradeTechDelayRaw": 30,
			"iContactTradeTechRandRaw": -1,
			"iContactTradeBonusDelayRaw": 20,
			"iContactTradeBonusRandRaw": -1,
			"iContactPeaceTreatyDelayRaw": -1,
			"iContactPeaceTreatyRandRaw": -1,
			"iContactOpenBordersDelayRaw": 40,
			"iContactOpenBordersRandRaw": 10,
			"iContactDefensivePactDelayRaw": 20,
			"iContactDefensivePactRandRaw": 80,
			"iContactPermanentAllianceDelayRaw": 20,
			"iContactPermanentAllianceRandRaw": 80,
			"iContactTradeMapDelayRaw": 50,
			"iContactTradeMapRandRaw": 20,
			"iAggregatedContactReligionPressureProb": -999,
			"iAggregatedContactCivicPressureProb": -999,
			"iAggregatedContactJoinWarProb": -999,
			"iAggregatedContactStopTradingProb": -999,
			"iAggregatedContactGiveHelpProb": -999,
			"iAggregatedContactAskForHelpProb": -999,
			"iAggregatedContactDemandTributeProb": -999,
			"iAggregatedContactTradeTechProb": -999,
			"iAggregatedContactTradeBonusProb": -999,
			"iAggregatedContactPeaceTreatyProb": -999,
			"iAggregatedContactOpenBordersProb": -999,
			"iAggregatedContactDefensivePactProb": -999,
			"iAggregatedContactPermanentAllianceProb": -999,
			"iAggregatedContactTradeMapProb": -999,
			"iPositiveMemoryAttitudeGiveHelpRaw": 100,
			"iPositiveMemoryDecayGiveHelpRaw": 150,
			"iPositiveMemoryAttitudeAcceptDemandRaw": 100,
			"iPositiveMemoryDecayAcceptDemandRaw": 30,
			"iPositiveMemoryAttitudeAcceptedReligionRaw": 100,
			"iPositiveMemoryDecayAcceptedReligionRaw": 100,
			"iPositiveMemoryAttitudeAcceptedCivicRaw": 100,
			"iPositiveMemoryDecayAcceptedCivicRaw": 100,
			"iPositiveMemoryAttitudeAcceptedJoinWarRaw": 100,
			"iPositiveMemoryDecayAcceptedJoinWarRaw": 100,
			"iPositiveMemoryAttitudeAcceptedStopTradingRaw": 50,
			"iPositiveMemoryDecayAcceptedStopTradingRaw": 50,
			"iPositiveMemoryAttitudeVotedForUsRaw": 200,
			"iPositiveMemoryDecayVotedForUsRaw": 10,
			"iPositiveMemoryAttitudeEventGoodToUsRaw": 100,
			"iPositiveMemoryDecayEventGoodToUsRaw": 50,
			"iPositiveMemoryAttitudeLiberatedCitiesRaw": 150,
			"iPositiveMemoryDecayLiberatedCitiesRaw": 150,
			"iPositiveMemoryAttitudeIndependenceRaw": 100,
			"iPositiveMemoryDecayIndependenceRaw": 30,
			"iPositiveMemoryAttitudeTradedTechToUsRaw": -1,
			"iPositiveMemoryDecayTradedTechToUsRaw": 25,
			"iAggregatedPositiveMemoryGiveHelpAffection": -999,
			"iAggregatedPositiveMemoryAcceptDemandAffection": -999,
			"iAggregatedPositiveMemoryAcceptedReligionAffection": -999,
			"iAggregatedPositiveMemoryAcceptedCivicAffection": -999,
			"iAggregatedPositiveMemoryAcceptedJoinWarAffection": -999,
			"iAggregatedPositiveMemoryAcceptedStopTradingAffection": -999,
			"iAggregatedPositiveMemoryVotedForUsAffection": -999,
			"iAggregatedPositiveMemoryEventGoodToUsAffection": -999,
			"iAggregatedPositiveMemoryLiberatedCitiesAffection": -999,
			"iAggregatedPositiveMemoryIndependenceAffection": -999,
			"iAggregatedPositiveMemoryTradedTechToUsAffection": -999,
			"iAggregatedPositiveMemoryGiveHelpResentment": -999,
			"iAggregatedPositiveMemoryAcceptDemandResentment": -999,
			"iAggregatedPositiveMemoryAcceptedReligionResentment": -999,
			"iAggregatedPositiveMemoryAcceptedCivicResentment": -999,
			"iAggregatedPositiveMemoryAcceptedJoinWarResentment": -999,
			"iAggregatedPositiveMemoryAcceptedStopTradingResentment": -999,
			"iAggregatedPositiveMemoryVotedForUsResentment": -999,
			"iAggregatedPositiveMemoryEventGoodToUsResentment": -999,
			"iAggregatedPositiveMemoryLiberatedCitiesResentment": -999,
			"iAggregatedPositiveMemoryIndependenceResentment": -999,
			"iAggregatedPositiveMemoryTradedTechToUsResentment": -999,
			"iNegativeMemoryAttitudeDeclaredWarRaw": -300,
			"iNegativeMemoryDecayDeclaredWarRaw": 150,
			"iNegativeMemoryAttitudeDeclaredWarOnFriendRaw": -100,
			"iNegativeMemoryDecayDeclaredWarOnFriendRaw": 120,
			"iNegativeMemoryAttitudeHiredWarAllyRaw": -200,
			"iNegativeMemoryDecayHiredWarAllyRaw": 75,
			"iNegativeMemoryAttitudeNukedUsRaw": -200,
			"iNegativeMemoryDecayNukedUsRaw": 120,
			"iNegativeMemoryAttitudeNukedFriendRaw": -100,
			"iNegativeMemoryDecayNukedFriendRaw": 80,
			"iNegativeMemoryAttitudeRazedCityRaw": -250,
			"iNegativeMemoryDecayRazedCityRaw": 75,
			"iNegativeMemoryAttitudeRazedHolyCityRaw": -200,
			"iNegativeMemoryDecayRazedHolyCityRaw": 150,
			"iNegativeMemoryAttitudeSpyCaughtRaw": -100,
			"iNegativeMemoryDecaySpyCaughtRaw": 40,
			"iNegativeMemoryAttitudeRefusedHelpRaw": -100,
			"iNegativeMemoryDecayRefusedHelpRaw": 100,
			"iNegativeMemoryAttitudeRejectedDemandRaw": -100,
			"iNegativeMemoryDecayRejectedDemandRaw": 90,
			"iNegativeMemoryAttitudeDeniedReligionRaw": -100,
			"iNegativeMemoryDecayDeniedReligionRaw": 50,
			"iNegativeMemoryAttitudeDeniedCivicRaw": -100,
			"iNegativeMemoryDecayDeniedCivicRaw": 50,
			"iNegativeMemoryAttitudeDeniedJoinWarRaw": -100,
			"iNegativeMemoryDecayDeniedJoinWarRaw": 100,
			"iNegativeMemoryAttitudeDeniedStopTradingRaw": -100,
			"iNegativeMemoryDecayDeniedStopTradingRaw": 50,
			"iNegativeMemoryAttitudeStoppedTradingRecentRaw": 0,
			"iNegativeMemoryDecayStoppedTradingRecentRaw": 18,
			"iNegativeMemoryAttitudeStoppedTradingRaw": -100,
			"iNegativeMemoryDecayStoppedTradingRaw": 60,
			"iNegativeMemoryAttitudeHiredTradeEmbargoRaw": -100,
			"iNegativeMemoryDecayHiredTradeEmbargoRaw": 60,
			"iNegativeMemoryAttitudeMadeDemandRaw": -100,
			"iNegativeMemoryDecayMadeDemandRaw": 30,
			"iNegativeMemoryAttitudeMadeDemandRecentRaw": 0,
			"iNegativeMemoryDecayMadeDemandRecentRaw": 20,
			"iNegativeMemoryAttitudeVotedAgainstUsRaw": -200,
			"iNegativeMemoryDecayVotedAgainstUsRaw": 10,
			"iNegativeMemoryAttitudeEventBadToUsRaw": -100,
			"iNegativeMemoryDecayEventBadToUsRaw": 50,
			"iNegativeMemoryAttitudeCancelledOpenBordersRaw": 0,
			"iNegativeMemoryDecayCancelledOpenBordersRaw": 10,
			"iNegativeMemoryAttitudeCancelledVassalAgreementRaw": 0,
			"iNegativeMemoryDecayCancelledVassalAgreementRaw": 10,
			"iNegativeMemoryAttitudeCancelledDefensivePactRaw": 0,
			"iNegativeMemoryDecayCancelledDefensivePactRaw": 10,
			"iNegativeMemoryAttitudeDeclaredWarRecentRaw": 0,
			"iNegativeMemoryDecayDeclaredWarRecentRaw": 11,
			"iNegativeMemoryAttitudeReceivedTechFromAnyRaw": 0,
			"iNegativeMemoryDecayReceivedTechFromAnyRaw": 20,
			"iAggregatedNegativeMemoryDeclaredWarAffection": -999,
			"iAggregatedNegativeMemoryDeclaredWarOnFriendAffection": -999,
			"iAggregatedNegativeMemoryHiredWarAllyAffection": -999,
			"iAggregatedNegativeMemoryNukedUsAffection": -999,
			"iAggregatedNegativeMemoryNukedFriendAffection": -999,
			"iAggregatedNegativeMemoryRazedCityAffection": -999,
			"iAggregatedNegativeMemoryRazedHolyCityAffection": -999,
			"iAggregatedNegativeMemorySpyCaughtAffection": -999,
			"iAggregatedNegativeMemoryRefusedHelpAffection": -999,
			"iAggregatedNegativeMemoryRejectedDemandAffection": -999,
			"iAggregatedNegativeMemoryDeniedReligionAffection": -999,
			"iAggregatedNegativeMemoryDeniedCivicAffection": -999,
			"iAggregatedNegativeMemoryDeniedJoinWarAffection": -999,
			"iAggregatedNegativeMemoryDeniedStopTradingAffection": -999,
			"iAggregatedNegativeMemoryStoppedTradingRecentAffection": -999,
			"iAggregatedNegativeMemoryStoppedTradingAffection": -999,
			"iAggregatedNegativeMemoryHiredTradeEmbargoAffection": -999,
			"iAggregatedNegativeMemoryMadeDemandAffection": -999,
			"iAggregatedNegativeMemoryMadeDemandRecentAffection": -999,
			"iAggregatedNegativeMemoryVotedAgainstUsAffection": -999,
			"iAggregatedNegativeMemoryEventBadToUsAffection": -999,
			"iAggregatedNegativeMemoryCancelledOpenBordersAffection": -999,
			"iAggregatedNegativeMemoryCancelledVassalAgreementAffection": -999,
			"iAggregatedNegativeMemoryCancelledDefensivePactAffection": -999,
			"iAggregatedNegativeMemoryDeclaredWarRecentAffection": -999,
			"iAggregatedNegativeMemoryReceivedTechFromAnyAffection": -999,
			"iAggregatedNegativeMemoryDeclaredWarResentment": -999,
			"iAggregatedNegativeMemoryDeclaredWarOnFriendResentment": -999,
			"iAggregatedNegativeMemoryHiredWarAllyResentment": -999,
			"iAggregatedNegativeMemoryNukedUsResentment": -999,
			"iAggregatedNegativeMemoryNukedFriendResentment": -999,
			"iAggregatedNegativeMemoryRazedCityResentment": -999,
			"iAggregatedNegativeMemoryRazedHolyCityResentment": -999,
			"iAggregatedNegativeMemorySpyCaughtResentment": -999,
			"iAggregatedNegativeMemoryRefusedHelpResentment": -999,
			"iAggregatedNegativeMemoryRejectedDemandResentment": -999,
			"iAggregatedNegativeMemoryDeniedReligionResentment": -999,
			"iAggregatedNegativeMemoryDeniedCivicResentment": -999,
			"iAggregatedNegativeMemoryDeniedJoinWarResentment": -999,
			"iAggregatedNegativeMemoryDeniedStopTradingResentment": -999,
			"iAggregatedNegativeMemoryStoppedTradingRecentResentment": -999,
			"iAggregatedNegativeMemoryStoppedTradingResentment": -999,
			"iAggregatedNegativeMemoryHiredTradeEmbargoResentment": -999,
			"iAggregatedNegativeMemoryMadeDemandResentment": -999,
			"iAggregatedNegativeMemoryMadeDemandRecentResentment": -999,
			"iAggregatedNegativeMemoryVotedAgainstUsResentment": -999,
			"iAggregatedNegativeMemoryEventBadToUsResentment": -999,
			"iAggregatedNegativeMemoryCancelledOpenBordersResentment": -999,
			"iAggregatedNegativeMemoryCancelledVassalAgreementResentment": -999,
			"iAggregatedNegativeMemoryCancelledDefensivePactResentment": -999,
			"iAggregatedNegativeMemoryDeclaredWarRecentResentment": -999,
			"iAggregatedNegativeMemoryReceivedTechFromAnyResentment": -999
		},
		"LEADER_ALEXANDER": {
			"Type": "LEADER_ALEXANDER",
			"Description": "TXT_KEY_LEADER_ALEXANDER",
			"Civilopedia": "TXT_KEY_LEADER_ALEXANDER_PEDIA",
			"ArtDefineTag": "ART_DEF_LEADER_ALEXANDER",
			"iWonderConstructRand": 20,
			"iBaseAttitude": 0,
			"iBasePeaceWeight": 0,
			"iWarmongerRespect": 2,
			"iEspionageWeight": 100,
			"iRefuseToTalkWarThreshold": 8,
			"iNoTechTradeThreshold": 5,
			"iTechTradeKnownPercent": 30,
			"iMaxGoldTradePercent": 5,
			"iCultureVictoryWeight": 25,
			"iSpaceVictoryWeight": 25,
			"iConquestVictoryWeight": 35,
			"iDominationVictoryWeight": 65,
			"iDiplomacyVictoryWeight": 0,
			"iMaxWarRand": 50,
			"iMaxWarNearbyPowerRatio": 90,
			"iMaxWarDistantPowerRatio": 70,
			"iMaxWarMinAdjacentLandPercent": 0,
			"iLimitedWarRand": 40,
			"iLimitedWarPowerRatio": 130,
			"iDogpileWarRand": 50,
			"iMakePeaceRand": 40,
			"iDemandRebukedSneakProb": 40,
			"iDemandRebukedWarProb": 25,
			"iRazeCityProb": 0,
			"iBuildUnitProb": 35,
			"iBaseAttackOddsChange": 4,
			"iWorseRankDifferenceAttitudeChange": -2,
			"iBetterRankDifferenceAttitudeChange": 0,
			"iCloseBordersAttitudeChange": -4,
			"iSameReligionAttitudeChangeLimit": 4,
			"iDifferentReligionAttitudeChangeLimit": -1,
			"iShareWarAttitudeChangeLimit": 4,
			"iFavoriteCivicAttitudeChangeLimit": 2,
			"iTechRefuseAttitudeThreshold": -1,
			"iCityRefuseAttitudeThreshold": 0,
			"iNativeCityRefuseAttitudeThreshold": 1,
			"iStrategicBonusRefuseAttitudeThreshold": 0,
			"iHappinessBonusRefuseAttitudeThreshold": -1,
			"iHealthBonusRefuseAttitudeThreshold": -1,
			"iMapRefuseAttitudeThreshold": 1,
			"iDeclareWarRefuseAttitudeThreshold": -1,
			"iDeclareWarThemRefuseAttitudeThreshold": 1,
			"iStopTradingRefuseAttitudeThreshold": 0,
			"iStopTradingThemRefuseAttitudeThreshold": 0,
			"iAdoptCivicRefuseAttitudeThreshold": 1,
			"iConvertReligionRefuseAttitudeThreshold": 0,
			"iOpenBordersRefuseAttitudeThreshold": -1,
			"iVassalRefuseAttitudeThreshold": 1,
			"iVassalPowerModifier": 20,
			"FavoriteCivic": "CIVIC_VASSALAGE",
			"FavoriteReligion": "RELIGION_PAGANISM",
			"Traits": [
				{
					"TraitType": "TRAIT_PHILOSOPHICAL",
					"bTrait": "1"
				},
				{
					"TraitType": "TRAIT_AGGRESSIVE",
					"bTrait": "1"
				}
			],
			"iFlavorMilitary": 5,
			"iFlavorReligion": 0,
			"iFlavorProduction": 0,
			"iFlavorGold": 0,
			"iFlavorScience": 0,
			"iFlavorCulture": 0,
			"iFlavorGrowth": 2,
			"iFlavorEspionage": 0,
			"iNoWarAttitudeProbFurious": 0,
			"iNoWarAttitudeProbAnnoyed": 0,
			"iNoWarAttitudeProbCautious": 20,
			"iNoWarAttitudeProbPleased": 80,
			"iNoWarAttitudeProbFriendly": 80,
			"UnitAIWeightModifiers": [
				{
					"UnitAIType": "UNITAI_SETTLE",
					"iWeightModifier": "25"
				},
				{
					"UnitAIType": "UNITAI_COLLATERAL",
					"iWeightModifier": "25"
				}
			],
			"ImprovementWeightModifiers": [
				{
					"ImprovementType": "IMPROVEMENT_MINE",
					"iWeightModifier": "30"
				}
			],
			"DiplomacyIntroMusicPeace": "",
			"DiplomacyMusicPeace": [
				{
					"EraType": "ERA_ANCIENT",
					"DiploScriptId": "AS2D_DIPLO_ALEXANDER_EARLY"
				},
				{
					"EraType": "ERA_CLASSICAL",
					"DiploScriptId": "AS2D_DIPLO_ALEXANDER_EARLY"
				},
				{
					"EraType": "ERA_MEDIEVAL",
					"DiploScriptId": "AS2D_DIPLO_ALEXANDER_MIDDLE"
				},
				{
					"EraType": "ERA_RENAISSANCE",
					"DiploScriptId": "AS2D_DIPLO_ALEXANDER_MIDDLE"
				},
				{
					"EraType": "ERA_INDUSTRIAL",
					"DiploScriptId": "AS2D_DIPLO_ALEXANDER_LATE"
				},
				{
					"EraType": "ERA_MODERN",
					"DiploScriptId": "AS2D_DIPLO_ALEXANDER_LATE"
				},
				{
					"EraType": "ERA_FUTURE",
					"DiploScriptId": "AS2D_DIPLO_ALEXANDER_LATE"
				}
			],
			"DiplomacyIntroMusicWar": "",
			"DiplomacyMusicWar": "",
			"iPeaceWeightRand": 3,
			"iMaxGoldPerTurnTradePercent": 10,
			"iDeclareWarTradeRand": 40,
			"iAttackOddsChangeRand": 8,
			"iLostWarAttitudeChange": -1,
			"iAtWarAttitudeDivisor": -5,
			"iAtWarAttitudeChangeLimit": 5,
			"iAtPeaceAttitudeDivisor": 60,
			"iAtPeaceAttitudeChangeLimit": 1,
			"iSameReligionAttitudeChange": 1,
			"iSameReligionAttitudeDivisor": 10,
			"iDifferentReligionAttitudeChange": -1,
			"iDifferentReligionAttitudeDivisor": -15,
			"iBonusTradeAttitudeDivisor": 50,
			"iBonusTradeAttitudeChangeLimit": 2,
			"iOpenBordersAttitudeDivisor": 25,
			"iOpenBordersAttitudeChangeLimit": 2,
			"iDefensivePactAttitudeDivisor": 12,
			"iDefensivePactAttitudeChangeLimit": 2,
			"iShareWarAttitudeChange": 1,
			"iShareWarAttitudeDivisor": 8,
			"iFavoriteCivicAttitudeChange": 1,
			"iFavoriteCivicAttitudeDivisor": 10,
			"iDemandTributeAttitudeThreshold": 0,
			"iNoGiveHelpAttitudeThreshold": 0,
			"iDefensivePactRefuseAttitudeThreshold": 1,
			"iPermanentAllianceRefuseAttitudeThreshold": 1,
			"iFreedomAppreciation": 10,
			"iLoveOfPeace": 0,
			"iContactReligionPressureDelayRaw": 50,
			"iContactReligionPressureRandRaw": 250,
			"iContactCivicPressureDelayRaw": 50,
			"iContactCivicPressureRandRaw": 1000,
			"iContactJoinWarDelayRaw": 20,
			"iContactJoinWarRandRaw": 20,
			"iContactStopTradingDelayRaw": 20,
			"iContactStopTradingRandRaw": 50,
			"iContactGiveHelpDelayRaw": 50,
			"iContactGiveHelpRandRaw": 500,
			"iContactAskForHelpDelayRaw": 50,
			"iContactAskForHelpRandRaw": 250,
			"iContactDemandTributeDelayRaw": 50,
			"iContactDemandTributeRandRaw": 250,
			"iContactTradeTechDelayRaw": 30,
			"iContactTradeTechRandRaw": 5,
			"iContactTradeBonusDelayRaw": 20,
			"iContactTradeBonusRandRaw": 5,
			"iContactPeaceTreatyDelayRaw": 15,
			"iContactPeaceTreatyRandRaw": 20,
			"iContactOpenBordersDelayRaw": 40,
			"iContactOpenBordersRandRaw": 10,
			"iContactDefensivePactDelayRaw": 20,
			"iContactDefensivePactRandRaw": 80,
			"iContactPermanentAllianceDelayRaw": 20,
			"iContactPermanentAllianceRandRaw": 80,
			"iContactTradeMapDelayRaw": 50,
			"iContactTradeMapRandRaw": 20,
			"iAggregatedContactReligionPressureProb": 79,
			"iAggregatedContactCivicPressureProb": 55,
			"iAggregatedContactJoinWarProb": 0,
			"iAggregatedContactStopTradingProb": 50,
			"iAggregatedContactGiveHelpProb": 78,
			"iAggregatedContactAskForHelpProb": 77,
			"iAggregatedContactDemandTributeProb": 89,
			"iAggregatedContactTradeTechProb": 79,
			"iAggregatedContactTradeBonusProb": 73,
			"iAggregatedContactPeaceTreatyProb": 39,
			"iAggregatedContactOpenBordersProb": 50,
			"iAggregatedContactDefensivePactProb": 50,
			"iAggregatedContactPermanentAllianceProb": 50,
			"iAggregatedContactTradeMapProb": 50,
			"iPositiveMemoryAttitudeGiveHelpRaw": 100,
			"iPositiveMemoryDecayGiveHelpRaw": 150,
			"iPositiveMemoryAttitudeAcceptDemandRaw": 100,
			"iPositiveMemoryDecayAcceptDemandRaw": 30,
			"iPositiveMemoryAttitudeAcceptedReligionRaw": 100,
			"iPositiveMemoryDecayAcceptedReligionRaw": 100,
			"iPositiveMemoryAttitudeAcceptedCivicRaw": 100,
			"iPositiveMemoryDecayAcceptedCivicRaw": 100,
			"iPositiveMemoryAttitudeAcceptedJoinWarRaw": 100,
			"iPositiveMemoryDecayAcceptedJoinWarRaw": 100,
			"iPositiveMemoryAttitudeAcceptedStopTradingRaw": 50,
			"iPositiveMemoryDecayAcceptedStopTradingRaw": 50,
			"iPositiveMemoryAttitudeVotedForUsRaw": 200,
			"iPositiveMemoryDecayVotedForUsRaw": 10,
			"iPositiveMemoryAttitudeEventGoodToUsRaw": 100,
			"iPositiveMemoryDecayEventGoodToUsRaw": 50,
			"iPositiveMemoryAttitudeLiberatedCitiesRaw": 150,
			"iPositiveMemoryDecayLiberatedCitiesRaw": 150,
			"iPositiveMemoryAttitudeIndependenceRaw": 100,
			"iPositiveMemoryDecayIndependenceRaw": 30,
			"iPositiveMemoryAttitudeTradedTechToUsRaw": 10,
			"iPositiveMemoryDecayTradedTechToUsRaw": 25,
			"iAggregatedPositiveMemoryGiveHelpAffection": 50,
			"iAggregatedPositiveMemoryAcceptDemandAffection": 50,
			"iAggregatedPositiveMemoryAcceptedReligionAffection": 50,
			"iAggregatedPositiveMemoryAcceptedCivicAffection": 50,
			"iAggregatedPositiveMemoryAcceptedJoinWarAffection": 50,
			"iAggregatedPositiveMemoryAcceptedStopTradingAffection": 50,
			"iAggregatedPositiveMemoryVotedForUsAffection": 50,
			"iAggregatedPositiveMemoryEventGoodToUsAffection": 50,
			"iAggregatedPositiveMemoryLiberatedCitiesAffection": 50,
			"iAggregatedPositiveMemoryIndependenceAffection": 50,
			"iAggregatedPositiveMemoryTradedTechToUsAffection": 33,
			"iAggregatedPositiveMemoryGiveHelpResentment": 50,
			"iAggregatedPositiveMemoryAcceptDemandResentment": 50,
			"iAggregatedPositiveMemoryAcceptedReligionResentment": 50,
			"iAggregatedPositiveMemoryAcceptedCivicResentment": 50,
			"iAggregatedPositiveMemoryAcceptedJoinWarResentment": 50,
			"iAggregatedPositiveMemoryAcceptedStopTradingResentment": 50,
			"iAggregatedPositiveMemoryVotedForUsResentment": 50,
			"iAggregatedPositiveMemoryEventGoodToUsResentment": 50,
			"iAggregatedPositiveMemoryLiberatedCitiesResentment": 50,
			"iAggregatedPositiveMemoryIndependenceResentment": 50,
			"iAggregatedPositiveMemoryTradedTechToUsResentment": 50,
			"iNegativeMemoryAttitudeDeclaredWarRaw": -300,
			"iNegativeMemoryDecayDeclaredWarRaw": 150,
			"iNegativeMemoryAttitudeDeclaredWarOnFriendRaw": -100,
			"iNegativeMemoryDecayDeclaredWarOnFriendRaw": 120,
			"iNegativeMemoryAttitudeHiredWarAllyRaw": -200,
			"iNegativeMemoryDecayHiredWarAllyRaw": 75,
			"iNegativeMemoryAttitudeNukedUsRaw": -200,
			"iNegativeMemoryDecayNukedUsRaw": 120,
			"iNegativeMemoryAttitudeNukedFriendRaw": -100,
			"iNegativeMemoryDecayNukedFriendRaw": 80,
			"iNegativeMemoryAttitudeRazedCityRaw": -250,
			"iNegativeMemoryDecayRazedCityRaw": 75,
			"iNegativeMemoryAttitudeRazedHolyCityRaw": -200,
			"iNegativeMemoryDecayRazedHolyCityRaw": 150,
			"iNegativeMemoryAttitudeSpyCaughtRaw": -100,
			"iNegativeMemoryDecaySpyCaughtRaw": 40,
			"iNegativeMemoryAttitudeRefusedHelpRaw": -100,
			"iNegativeMemoryDecayRefusedHelpRaw": 100,
			"iNegativeMemoryAttitudeRejectedDemandRaw": -100,
			"iNegativeMemoryDecayRejectedDemandRaw": 90,
			"iNegativeMemoryAttitudeDeniedReligionRaw": -100,
			"iNegativeMemoryDecayDeniedReligionRaw": 50,
			"iNegativeMemoryAttitudeDeniedCivicRaw": -100,
			"iNegativeMemoryDecayDeniedCivicRaw": 50,
			"iNegativeMemoryAttitudeDeniedJoinWarRaw": -100,
			"iNegativeMemoryDecayDeniedJoinWarRaw": 100,
			"iNegativeMemoryAttitudeDeniedStopTradingRaw": -100,
			"iNegativeMemoryDecayDeniedStopTradingRaw": 50,
			"iNegativeMemoryAttitudeStoppedTradingRecentRaw": 0,
			"iNegativeMemoryDecayStoppedTradingRecentRaw": 18,
			"iNegativeMemoryAttitudeStoppedTradingRaw": -100,
			"iNegativeMemoryDecayStoppedTradingRaw": 60,
			"iNegativeMemoryAttitudeHiredTradeEmbargoRaw": -100,
			"iNegativeMemoryDecayHiredTradeEmbargoRaw": 60,
			"iNegativeMemoryAttitudeMadeDemandRaw": -100,
			"iNegativeMemoryDecayMadeDemandRaw": 30,
			"iNegativeMemoryAttitudeMadeDemandRecentRaw": 0,
			"iNegativeMemoryDecayMadeDemandRecentRaw": 20,
			"iNegativeMemoryAttitudeVotedAgainstUsRaw": -200,
			"iNegativeMemoryDecayVotedAgainstUsRaw": 10,
			"iNegativeMemoryAttitudeEventBadToUsRaw": -100,
			"iNegativeMemoryDecayEventBadToUsRaw": 50,
			"iNegativeMemoryAttitudeCancelledOpenBordersRaw": 0,
			"iNegativeMemoryDecayCancelledOpenBordersRaw": 10,
			"iNegativeMemoryAttitudeCancelledVassalAgreementRaw": 0,
			"iNegativeMemoryDecayCancelledVassalAgreementRaw": 10,
			"iNegativeMemoryAttitudeCancelledDefensivePactRaw": 0,
			"iNegativeMemoryDecayCancelledDefensivePactRaw": 10,
			"iNegativeMemoryAttitudeDeclaredWarRecentRaw": 0,
			"iNegativeMemoryDecayDeclaredWarRecentRaw": 11,
			"iNegativeMemoryAttitudeReceivedTechFromAnyRaw": 0,
			"iNegativeMemoryDecayReceivedTechFromAnyRaw": 20,
			"iAggregatedNegativeMemoryDeclaredWarAffection": 50,
			"iAggregatedNegativeMemoryDeclaredWarOnFriendAffection": 50,
			"iAggregatedNegativeMemoryHiredWarAllyAffection": 50,
			"iAggregatedNegativeMemoryNukedUsAffection": 50,
			"iAggregatedNegativeMemoryNukedFriendAffection": 50,
			"iAggregatedNegativeMemoryRazedCityAffection": 50,
			"iAggregatedNegativeMemoryRazedHolyCityAffection": 50,
			"iAggregatedNegativeMemorySpyCaughtAffection": 50,
			"iAggregatedNegativeMemoryRefusedHelpAffection": 50,
			"iAggregatedNegativeMemoryRejectedDemandAffection": 50,
			"iAggregatedNegativeMemoryDeniedReligionAffection": 50,
			"iAggregatedNegativeMemoryDeniedCivicAffection": 50,
			"iAggregatedNegativeMemoryDeniedJoinWarAffection": 50,
			"iAggregatedNegativeMemoryDeniedStopTradingAffection": 50,
			"iAggregatedNegativeMemoryStoppedTradingRecentAffection": 50,
			"iAggregatedNegativeMemoryStoppedTradingAffection": 50,
			"iAggregatedNegativeMemoryHiredTradeEmbargoAffection": 50,
			"iAggregatedNegativeMemoryMadeDemandAffection": 50,
			"iAggregatedNegativeMemoryMadeDemandRecentAffection": 50,
			"iAggregatedNegativeMemoryVotedAgainstUsAffection": 50,
			"iAggregatedNegativeMemoryEventBadToUsAffection": 50,
			"iAggregatedNegativeMemoryCancelledOpenBordersAffection": 50,
			"iAggregatedNegativeMemoryCancelledVassalAgreementAffection": 50,
			"iAggregatedNegativeMemoryCancelledDefensivePactAffection": 50,
			"iAggregatedNegativeMemoryDeclaredWarRecentAffection": 50,
			"iAggregatedNegativeMemoryReceivedTechFromAnyAffection": 50,
			"iAggregatedNegativeMemoryDeclaredWarResentment": 50,
			"iAggregatedNegativeMemoryDeclaredWarOnFriendResentment": 0,
			"iAggregatedNegativeMemoryHiredWarAllyResentment": 50,
			"iAggregatedNegativeMemoryNukedUsResentment": 50,
			"iAggregatedNegativeMemoryNukedFriendResentment": 0,
			"iAggregatedNegativeMemoryRazedCityResentment": 50,
			"iAggregatedNegativeMemoryRazedHolyCityResentment": 50,
			"iAggregatedNegativeMemorySpyCaughtResentment": 0,
			"iAggregatedNegativeMemoryRefusedHelpResentment": 50,
			"iAggregatedNegativeMemoryRejectedDemandResentment": 50,
			"iAggregatedNegativeMemoryDeniedReligionResentment": 50,
			"iAggregatedNegativeMemoryDeniedCivicResentment": 50,
			"iAggregatedNegativeMemoryDeniedJoinWarResentment": 50,
			"iAggregatedNegativeMemoryDeniedStopTradingResentment": 50,
			"iAggregatedNegativeMemoryStoppedTradingRecentResentment": 50,
			"iAggregatedNegativeMemoryStoppedTradingResentment": 100,
			"iAggregatedNegativeMemoryHiredTradeEmbargoResentment": 50,
			"iAggregatedNegativeMemoryMadeDemandResentment": 0,
			"iAggregatedNegativeMemoryMadeDemandRecentResentment": 50,
			"iAggregatedNegativeMemoryVotedAgainstUsResentment": 100,
			"iAggregatedNegativeMemoryEventBadToUsResentment": 50,
			"iAggregatedNegativeMemoryCancelledOpenBordersResentment": 50,
			"iAggregatedNegativeMemoryCancelledVassalAgreementResentment": 50,
			"iAggregatedNegativeMemoryCancelledDefensivePactResentment": 50,
			"iAggregatedNegativeMemoryDeclaredWarRecentResentment": 50,
			"iAggregatedNegativeMemoryReceivedTechFromAnyResentment": 50
		},
		"LEADER_CATHERINE": {
			"Type": "LEADER_CATHERINE",
			"Description": "TXT_KEY_LEADER_CATHERINE",
			"Civilopedia": "TXT_KEY_LEADER_CATHERINE_PEDIA",
			"ArtDefineTag": "ART_DEF_LEADER_CATHERINE",
			"iWonderConstructRand": 30,
			"iBaseAttitude": 1,
			"iBasePeaceWeight": 2,
			"iWarmongerRespect": 2,
			"iEspionageWeight": 130,
			"iRefuseToTalkWarThreshold": 6,
			"iNoTechTradeThreshold": 15,
			"iTechTradeKnownPercent": 20,
			"iMaxGoldTradePercent": 5,
			"iCultureVictoryWeight": 30,
			"iSpaceVictoryWeight": 45,
			"iConquestVictoryWeight": 25,
			"iDominationVictoryWeight": 40,
			"iDiplomacyVictoryWeight": 10,
			"iMaxWarRand": 100,
			"iMaxWarNearbyPowerRatio": 90,
			"iMaxWarDistantPowerRatio": 40,
			"iMaxWarMinAdjacentLandPercent": 1,
			"iLimitedWarRand": 80,
			"iLimitedWarPowerRatio": 110,
			"iDogpileWarRand": 25,
			"iMakePeaceRand": 10,
			"iDemandRebukedSneakProb": 80,
			"iDemandRebukedWarProb": 0,
			"iRazeCityProb": 0,
			"iBuildUnitProb": 25,
			"iBaseAttackOddsChange": 2,
			"iWorseRankDifferenceAttitudeChange": -2,
			"iBetterRankDifferenceAttitudeChange": 0,
			"iCloseBordersAttitudeChange": -4,
			"iSameReligionAttitudeChangeLimit": 4,
			"iDifferentReligionAttitudeChangeLimit": -2,
			"iShareWarAttitudeChangeLimit": 2,
			"iFavoriteCivicAttitudeChangeLimit": 3,
			"iTechRefuseAttitudeThreshold": -3,
			"iCityRefuseAttitudeThreshold": 1,
			"iNativeCityRefuseAttitudeThreshold": 2,
			"iStrategicBonusRefuseAttitudeThreshold": 0,
			"iHappinessBonusRefuseAttitudeThreshold": -1,
			"iHealthBonusRefuseAttitudeThreshold": -2,
			"iMapRefuseAttitudeThreshold": 1,
			"iDeclareWarRefuseAttitudeThreshold": 1,
			"iDeclareWarThemRefuseAttitudeThreshold": 2,
			"iStopTradingRefuseAttitudeThreshold": -1,
			"iStopTradingThemRefuseAttitudeThreshold": -1,
			"iAdoptCivicRefuseAttitudeThreshold": -1,
			"iConvertReligionRefuseAttitudeThreshold": 0,
			"iOpenBordersRefuseAttitudeThreshold": -2,
			"iDefensivePactRefuseAttitudeThreshold": 0,
			"iVassalRefuseAttitudeThreshold": -1,
			"iVassalPowerModifier": -20,
			"FavoriteCivic": "CIVIC_HEREDITARY_RULE",
			"FavoriteReligion": "RELIGION_CHRISTIANITY",
			"Traits": [
				{
					"TraitType": "TRAIT_CREATIVE",
					"bTrait": "1"
				},
				{
					"TraitType": "TRAIT_IMPERIALIST",
					"bTrait": "1"
				}
			],
			"iFlavorMilitary": 2,
			"iFlavorReligion": 0,
			"iFlavorProduction": 0,
			"iFlavorGold": 0,
			"iFlavorScience": 0,
			"iFlavorCulture": 5,
			"iFlavorGrowth": 0,
			"iFlavorEspionage": 0,
			"iNoWarAttitudeProbFurious": 0,
			"iNoWarAttitudeProbAnnoyed": 0,
			"iNoWarAttitudeProbCautious": 20,
			"iNoWarAttitudeProbPleased": 80,
			"iNoWarAttitudeProbFriendly": 80,
			"UnitAIWeightModifiers": [
				{
					"UnitAIType": "UNITAI_RESERVE",
					"iWeightModifier": "25"
				}
			],
			"ImprovementWeightModifiers": [
				{
					"ImprovementType": "IMPROVEMENT_FARM",
					"iWeightModifier": "20"
				},
				{
					"ImprovementType": "IMPROVEMENT_LUMBERMILL",
					"iWeightModifier": "20"
				}
			],
			"DiplomacyIntroMusicPeace": "",
			"DiplomacyMusicPeace": [
				{
					"EraType": "ERA_ANCIENT",
					"DiploScriptId": "AS2D_DIPLO_CATHERINE_EARLY"
				},
				{
					"EraType": "ERA_CLASSICAL",
					"DiploScriptId": "AS2D_DIPLO_CATHERINE_EARLY"
				},
				{
					"EraType": "ERA_MEDIEVAL",
					"DiploScriptId": "AS2D_DIPLO_CATHERINE_MIDDLE"
				},
				{
					"EraType": "ERA_RENAISSANCE",
					"DiploScriptId": "AS2D_DIPLO_CATHERINE_MIDDLE"
				},
				{
					"EraType": "ERA_INDUSTRIAL",
					"DiploScriptId": "AS2D_DIPLO_CATHERINE_LATE"
				},
				{
					"EraType": "ERA_MODERN",
					"DiploScriptId": "AS2D_DIPLO_CATHERINE_LATE"
				},
				{
					"EraType": "ERA_FUTURE",
					"DiploScriptId": "AS2D_DIPLO_CATHERINE_LATE"
				}
			],
			"DiplomacyIntroMusicWar": "",
			"DiplomacyMusicWar": "",
			"iPeaceWeightRand": 3,
			"iMaxGoldPerTurnTradePercent": 10,
			"iDeclareWarTradeRand": 40,
			"iAttackOddsChangeRand": 8,
			"iLostWarAttitudeChange": -1,
			"iAtWarAttitudeDivisor": -5,
			"iAtWarAttitudeChangeLimit": 5,
			"iAtPeaceAttitudeDivisor": 60,
			"iAtPeaceAttitudeChangeLimit": 1,
			"iSameReligionAttitudeChange": 1,
			"iSameReligionAttitudeDivisor": 10,
			"iDifferentReligionAttitudeChange": -1,
			"iDifferentReligionAttitudeDivisor": -15,
			"iBonusTradeAttitudeDivisor": 50,
			"iBonusTradeAttitudeChangeLimit": 2,
			"iOpenBordersAttitudeDivisor": 25,
			"iOpenBordersAttitudeChangeLimit": 2,
			"iDefensivePactAttitudeDivisor": 12,
			"iDefensivePactAttitudeChangeLimit": 2,
			"iShareWarAttitudeChange": 1,
			"iShareWarAttitudeDivisor": 8,
			"iFavoriteCivicAttitudeChange": 1,
			"iFavoriteCivicAttitudeDivisor": 10,
			"iDemandTributeAttitudeThreshold": 0,
			"iNoGiveHelpAttitudeThreshold": 0,
			"iPermanentAllianceRefuseAttitudeThreshold": 1,
			"iFreedomAppreciation": 10,
			"iLoveOfPeace": 0,
			"iContactReligionPressureDelayRaw": 50,
			"iContactReligionPressureRandRaw": 250,
			"iContactCivicPressureDelayRaw": 50,
			"iContactCivicPressureRandRaw": 500,
			"iContactJoinWarDelayRaw": 20,
			"iContactJoinWarRandRaw": 10,
			"iContactStopTradingDelayRaw": 20,
			"iContactStopTradingRandRaw": 50,
			"iContactGiveHelpDelayRaw": 50,
			"iContactGiveHelpRandRaw": 500,
			"iContactAskForHelpDelayRaw": 50,
			"iContactAskForHelpRandRaw": 25,
			"iContactDemandTributeDelayRaw": 50,
			"iContactDemandTributeRandRaw": 750,
			"iContactTradeTechDelayRaw": 30,
			"iContactTradeTechRandRaw": 2,
			"iContactTradeBonusDelayRaw": 20,
			"iContactTradeBonusRandRaw": 2,
			"iContactPeaceTreatyDelayRaw": 10,
			"iContactPeaceTreatyRandRaw": 15,
			"iContactOpenBordersDelayRaw": 40,
			"iContactOpenBordersRandRaw": 10,
			"iContactDefensivePactDelayRaw": 20,
			"iContactDefensivePactRandRaw": 80,
			"iContactPermanentAllianceDelayRaw": 20,
			"iContactPermanentAllianceRandRaw": 80,
			"iContactTradeMapDelayRaw": 50,
			"iContactTradeMapRandRaw": 20,
			"iAggregatedContactReligionPressureProb": 79,
			"iAggregatedContactCivicPressureProb": 79,
			"iAggregatedContactJoinWarProb": 100,
			"iAggregatedContactStopTradingProb": 50,
			"iAggregatedContactGiveHelpProb": 78,
			"iAggregatedContactAskForHelpProb": 100,
			"iAggregatedContactDemandTributeProb": 66,
			"iAggregatedContactTradeTechProb": 95,
			"iAggregatedContactTradeBonusProb": 93,
			"iAggregatedContactPeaceTreatyProb": 78,
			"iAggregatedContactOpenBordersProb": 50,
			"iAggregatedContactDefensivePactProb": 50,
			"iAggregatedContactPermanentAllianceProb": 50,
			"iAggregatedContactTradeMapProb": 50,
			"iPositiveMemoryAttitudeGiveHelpRaw": 100,
			"iPositiveMemoryDecayGiveHelpRaw": 150,
			"iPositiveMemoryAttitudeAcceptDemandRaw": 100,
			"iPositiveMemoryDecayAcceptDemandRaw": 30,
			"iPositiveMemoryAttitudeAcceptedReligionRaw": 100,
			"iPositiveMemoryDecayAcceptedReligionRaw": 100,
			"iPositiveMemoryAttitudeAcceptedCivicRaw": 100,
			"iPositiveMemoryDecayAcceptedCivicRaw": 100,
			"iPositiveMemoryAttitudeAcceptedJoinWarRaw": 100,
			"iPositiveMemoryDecayAcceptedJoinWarRaw": 100,
			"iPositiveMemoryAttitudeAcceptedStopTradingRaw": 50,
			"iPositiveMemoryDecayAcceptedStopTradingRaw": 50,
			"iPositiveMemoryAttitudeVotedForUsRaw": 200,
			"iPositiveMemoryDecayVotedForUsRaw": 10,
			"iPositiveMemoryAttitudeEventGoodToUsRaw": 100,
			"iPositiveMemoryDecayEventGoodToUsRaw": 50,
			"iPositiveMemoryAttitudeLiberatedCitiesRaw": 150,
			"iPositiveMemoryDecayLiberatedCitiesRaw": 150,
			"iPositiveMemoryAttitudeIndependenceRaw": 100,
			"iPositiveMemoryDecayIndependenceRaw": 30,
			"iPositiveMemoryAttitudeTradedTechToUsRaw": 15,
			"iPositiveMemoryDecayTradedTechToUsRaw": 25,
			"iAggregatedPositiveMemoryGiveHelpAffection": 50,
			"iAggregatedPositiveMemoryAcceptDemandAffection": 50,
			"iAggregatedPositiveMemoryAcceptedReligionAffection": 50,
			"iAggregatedPositiveMemoryAcceptedCivicAffection": 50,
			"iAggregatedPositiveMemoryAcceptedJoinWarAffection": 50,
			"iAggregatedPositiveMemoryAcceptedStopTradingAffection": 50,
			"iAggregatedPositiveMemoryVotedForUsAffection": 50,
			"iAggregatedPositiveMemoryEventGoodToUsAffection": 50,
			"iAggregatedPositiveMemoryLiberatedCitiesAffection": 50,
			"iAggregatedPositiveMemoryIndependenceAffection": 50,
			"iAggregatedPositiveMemoryTradedTechToUsAffection": 67,
			"iAggregatedPositiveMemoryGiveHelpResentment": 50,
			"iAggregatedPositiveMemoryAcceptDemandResentment": 50,
			"iAggregatedPositiveMemoryAcceptedReligionResentment": 50,
			"iAggregatedPositiveMemoryAcceptedCivicResentment": 50,
			"iAggregatedPositiveMemoryAcceptedJoinWarResentment": 50,
			"iAggregatedPositiveMemoryAcceptedStopTradingResentment": 50,
			"iAggregatedPositiveMemoryVotedForUsResentment": 50,
			"iAggregatedPositiveMemoryEventGoodToUsResentment": 50,
			"iAggregatedPositiveMemoryLiberatedCitiesResentment": 50,
			"iAggregatedPositiveMemoryIndependenceResentment": 50,
			"iAggregatedPositiveMemoryTradedTechToUsResentment": 50,
			"iNegativeMemoryAttitudeDeclaredWarRaw": -300,
			"iNegativeMemoryDecayDeclaredWarRaw": 150,
			"iNegativeMemoryAttitudeDeclaredWarOnFriendRaw": -100,
			"iNegativeMemoryDecayDeclaredWarOnFriendRaw": 120,
			"iNegativeMemoryAttitudeHiredWarAllyRaw": -200,
			"iNegativeMemoryDecayHiredWarAllyRaw": 75,
			"iNegativeMemoryAttitudeNukedUsRaw": -200,
			"iNegativeMemoryDecayNukedUsRaw": 120,
			"iNegativeMemoryAttitudeNukedFriendRaw": -100,
			"iNegativeMemoryDecayNukedFriendRaw": 80,
			"iNegativeMemoryAttitudeRazedCityRaw": -250,
			"iNegativeMemoryDecayRazedCityRaw": 75,
			"iNegativeMemoryAttitudeRazedHolyCityRaw": -200,
			"iNegativeMemoryDecayRazedHolyCityRaw": 150,
			"iNegativeMemoryAttitudeSpyCaughtRaw": -200,
			"iNegativeMemoryDecaySpyCaughtRaw": 40,
			"iNegativeMemoryAttitudeRefusedHelpRaw": -200,
			"iNegativeMemoryDecayRefusedHelpRaw": 100,
			"iNegativeMemoryAttitudeRejectedDemandRaw": -200,
			"iNegativeMemoryDecayRejectedDemandRaw": 90,
			"iNegativeMemoryAttitudeDeniedReligionRaw": -200,
			"iNegativeMemoryDecayDeniedReligionRaw": 50,
			"iNegativeMemoryAttitudeDeniedCivicRaw": -200,
			"iNegativeMemoryDecayDeniedCivicRaw": 50,
			"iNegativeMemoryAttitudeDeniedJoinWarRaw": -200,
			"iNegativeMemoryDecayDeniedJoinWarRaw": 100,
			"iNegativeMemoryAttitudeDeniedStopTradingRaw": -200,
			"iNegativeMemoryDecayDeniedStopTradingRaw": 50,
			"iNegativeMemoryAttitudeStoppedTradingRecentRaw": 0,
			"iNegativeMemoryDecayStoppedTradingRecentRaw": 18,
			"iNegativeMemoryAttitudeStoppedTradingRaw": -100,
			"iNegativeMemoryDecayStoppedTradingRaw": 60,
			"iNegativeMemoryAttitudeHiredTradeEmbargoRaw": -100,
			"iNegativeMemoryDecayHiredTradeEmbargoRaw": 60,
			"iNegativeMemoryAttitudeMadeDemandRaw": -200,
			"iNegativeMemoryDecayMadeDemandRaw": 30,
			"iNegativeMemoryAttitudeMadeDemandRecentRaw": 0,
			"iNegativeMemoryDecayMadeDemandRecentRaw": 20,
			"iNegativeMemoryAttitudeVotedAgainstUsRaw": -200,
			"iNegativeMemoryDecayVotedAgainstUsRaw": 10,
			"iNegativeMemoryAttitudeEventBadToUsRaw": -100,
			"iNegativeMemoryDecayEventBadToUsRaw": 50,
			"iNegativeMemoryAttitudeCancelledOpenBordersRaw": 0,
			"iNegativeMemoryDecayCancelledOpenBordersRaw": 10,
			"iNegativeMemoryAttitudeCancelledVassalAgreementRaw": 0,
			"iNegativeMemoryDecayCancelledVassalAgreementRaw": 10,
			"iNegativeMemoryAttitudeCancelledDefensivePactRaw": 0,
			"iNegativeMemoryDecayCancelledDefensivePactRaw": 10,
			"iNegativeMemoryAttitudeDeclaredWarRecentRaw": 0,
			"iNegativeMemoryDecayDeclaredWarRecentRaw": 11,
			"iNegativeMemoryAttitudeReceivedTechFromAnyRaw": 0,
			"iNegativeMemoryDecayReceivedTechFromAnyRaw": 20,
			"iAggregatedNegativeMemoryDeclaredWarAffection": 50,
			"iAggregatedNegativeMemoryDeclaredWarOnFriendAffection": 50,
			"iAggregatedNegativeMemoryHiredWarAllyAffection": 50,
			"iAggregatedNegativeMemoryNukedUsAffection": 50,
			"iAggregatedNegativeMemoryNukedFriendAffection": 50,
			"iAggregatedNegativeMemoryRazedCityAffection": 50,
			"iAggregatedNegativeMemoryRazedHolyCityAffection": 50,
			"iAggregatedNegativeMemorySpyCaughtAffection": 50,
			"iAggregatedNegativeMemoryRefusedHelpAffection": 50,
			"iAggregatedNegativeMemoryRejectedDemandAffection": 50,
			"iAggregatedNegativeMemoryDeniedReligionAffection": 50,
			"iAggregatedNegativeMemoryDeniedCivicAffection": 50,
			"iAggregatedNegativeMemoryDeniedJoinWarAffection": 50,
			"iAggregatedNegativeMemoryDeniedStopTradingAffection": 50,
			"iAggregatedNegativeMemoryStoppedTradingRecentAffection": 50,
			"iAggregatedNegativeMemoryStoppedTradingAffection": 50,
			"iAggregatedNegativeMemoryHiredTradeEmbargoAffection": 50,
			"iAggregatedNegativeMemoryMadeDemandAffection": 50,
			"iAggregatedNegativeMemoryMadeDemandRecentAffection": 50,
			"iAggregatedNegativeMemoryVotedAgainstUsAffection": 50,
			"iAggregatedNegativeMemoryEventBadToUsAffection": 50,
			"iAggregatedNegativeMemoryCancelledOpenBordersAffection": 50,
			"iAggregatedNegativeMemoryCancelledVassalAgreementAffection": 50,
			"iAggregatedNegativeMemoryCancelledDefensivePactAffection": 50,
			"iAggregatedNegativeMemoryDeclaredWarRecentAffection": 50,
			"iAggregatedNegativeMemoryReceivedTechFromAnyAffection": 50,
			"iAggregatedNegativeMemoryDeclaredWarResentment": 50,
			"iAggregatedNegativeMemoryDeclaredWarOnFriendResentment": 0,
			"iAggregatedNegativeMemoryHiredWarAllyResentment": 50,
			"iAggregatedNegativeMemoryNukedUsResentment": 50,
			"iAggregatedNegativeMemoryNukedFriendResentment": 0,
			"iAggregatedNegativeMemoryRazedCityResentment": 50,
			"iAggregatedNegativeMemoryRazedHolyCityResentment": 50,
			"iAggregatedNegativeMemorySpyCaughtResentment": 100,
			"iAggregatedNegativeMemoryRefusedHelpResentment": 100,
			"iAggregatedNegativeMemoryRejectedDemandResentment": 100,
			"iAggregatedNegativeMemoryDeniedReligionResentment": 100,
			"iAggregatedNegativeMemoryDeniedCivicResentment": 100,
			"iAggregatedNegativeMemoryDeniedJoinWarResentment": 100,
			"iAggregatedNegativeMemoryDeniedStopTradingResentment": 100,
			"iAggregatedNegativeMemoryStoppedTradingRecentResentment": 50,
			"iAggregatedNegativeMemoryStoppedTradingResentment": 100,
			"iAggregatedNegativeMemoryHiredTradeEmbargoResentment": 50,
			"iAggregatedNegativeMemoryMadeDemandResentment": 100,
			"iAggregatedNegativeMemoryMadeDemandRecentResentment": 50,
			"iAggregatedNegativeMemoryVotedAgainstUsResentment": 100,
			"iAggregatedNegativeMemoryEventBadToUsResentment": 50,
			"iAggregatedNegativeMemoryCancelledOpenBordersResentment": 50,
			"iAggregatedNegativeMemoryCancelledVassalAgreementResentment": 50,
			"iAggregatedNegativeMemoryCancelledDefensivePactResentment": 50,
			"iAggregatedNegativeMemoryDeclaredWarRecentResentment": 50,
			"iAggregatedNegativeMemoryReceivedTechFromAnyResentment": 50
		},
		"LEADER_GANDHI": {
			"Type": "LEADER_GANDHI",
			"Description": "TXT_KEY_LEADER_GANDHI",
			"Civilopedia": "TXT_KEY_LEADER_GANDHI_PEDIA",
			"ArtDefineTag": "ART_DEF_LEADER_GANDHI",
			"iWonderConstructRand": 10,
			"iBaseAttitude": 2,
			"iBasePeaceWeight": 10,
			"iWarmongerRespect": 0,
			"iEspionageWeight": 50,
			"iRefuseToTalkWarThreshold": 6,
			"iNoTechTradeThreshold": 15,
			"iTechTradeKnownPercent": 20,
			"iMaxGoldTradePercent": 10,
			"iCultureVictoryWeight": 45,
			"iSpaceVictoryWeight": 30,
			"iConquestVictoryWeight": 0,
			"iDominationVictoryWeight": 5,
			"iDiplomacyVictoryWeight": 70,
			"iMaxWarRand": 400,
			"iMaxWarNearbyPowerRatio": 100,
			"iMaxWarDistantPowerRatio": 60,
			"iMaxWarMinAdjacentLandPercent": 3,
			"iLimitedWarRand": 200,
			"iLimitedWarPowerRatio": 80,
			"iDogpileWarRand": 100,
			"iMakePeaceRand": 10,
			"iDemandRebukedSneakProb": 0,
			"iDemandRebukedWarProb": 0,
			"iRazeCityProb": 0,
			"iBuildUnitProb": 15,
			"iBaseAttackOddsChange": 0,
			"iWorseRankDifferenceAttitudeChange": 0,
			"iBetterRankDifferenceAttitudeChange": 1,
			"iCloseBordersAttitudeChange": -2,
			"iSameReligionAttitudeChangeLimit": 4,
			"iDifferentReligionAttitudeChangeLimit": -1,
			"iShareWarAttitudeChangeLimit": 2,
			"iFavoriteCivicAttitudeChangeLimit": 5,
			"iTechRefuseAttitudeThreshold": -3,
			"iCityRefuseAttitudeThreshold": 1,
			"iNativeCityRefuseAttitudeThreshold": 2,
			"iStrategicBonusRefuseAttitudeThreshold": -1,
			"iHappinessBonusRefuseAttitudeThreshold": -3,
			"iHealthBonusRefuseAttitudeThreshold": -3,
			"iMapRefuseAttitudeThreshold": -3,
			"iDeclareWarRefuseAttitudeThreshold": 1,
			"iDeclareWarThemRefuseAttitudeThreshold": -1,
			"iStopTradingRefuseAttitudeThreshold": 1,
			"iStopTradingThemRefuseAttitudeThreshold": 0,
			"iAdoptCivicRefuseAttitudeThreshold": 0,
			"iConvertReligionRefuseAttitudeThreshold": -1,
			"iOpenBordersRefuseAttitudeThreshold": -3,
			"iVassalRefuseAttitudeThreshold": -1,
			"iVassalPowerModifier": -20,
			"FavoriteCivic": "CIVIC_UNIVERSAL_SUFFRAGE",
			"FavoriteReligion": "RELIGION_HINDUISM",
			"Traits": [
				{
					"TraitType": "TRAIT_SPIRITUAL",
					"bTrait": "1"
				},
				{
					"TraitType": "TRAIT_PHILOSOPHICAL",
					"bTrait": "1"
				}
			],
			"iFlavorMilitary": 0,
			"iFlavorReligion": 0,
			"iFlavorProduction": 0,
			"iFlavorGold": 0,
			"iFlavorScience": 0,
			"iFlavorCulture": 10,
			"iFlavorGrowth": 0,
			"iFlavorEspionage": 0,
			"iNoWarAttitudeProbFurious": 20,
			"iNoWarAttitudeProbAnnoyed": 50,
			"iNoWarAttitudeProbCautious": 85,
			"iNoWarAttitudeProbPleased": 110,
			"iNoWarAttitudeProbFriendly": 115,
			"UnitAIWeightModifiers": "",
			"ImprovementWeightModifiers": [
				{
					"ImprovementType": "IMPROVEMENT_FARM",
					"iWeightModifier": "30"
				}
			],
			"DiplomacyIntroMusicPeace": [
				{
					"EraType": "ERA_ANCIENT",
					"DiploScriptId": "AS2D_DIPLO_GANDHI_EARLY_INTRO"
				},
				{
					"EraType": "ERA_CLASSICAL",
					"DiploScriptId": "AS2D_DIPLO_GANDHI_EARLY_INTRO"
				}
			],
			"DiplomacyMusicPeace": [
				{
					"EraType": "ERA_ANCIENT",
					"DiploScriptId": "AS2D_DIPLO_GANDHI_EARLY_LP"
				},
				{
					"EraType": "ERA_CLASSICAL",
					"DiploScriptId": "AS2D_DIPLO_GANDHI_EARLY_LP"
				},
				{
					"EraType": "ERA_MEDIEVAL",
					"DiploScriptId": "AS2D_DIPLO_GANDHI_MIDDLE"
				},
				{
					"EraType": "ERA_RENAISSANCE",
					"DiploScriptId": "AS2D_DIPLO_GANDHI_MIDDLE"
				},
				{
					"EraType": "ERA_INDUSTRIAL",
					"DiploScriptId": "AS2D_DIPLO_GANDHI_LATE"
				},
				{
					"EraType": "ERA_MODERN",
					"DiploScriptId": "AS2D_DIPLO_GANDHI_LATE"
				},
				{
					"EraType": "ERA_FUTURE",
					"DiploScriptId": "AS2D_DIPLO_GANDHI_LATE"
				}
			],
			"DiplomacyIntroMusicWar": "",
			"DiplomacyMusicWar": "",
			"iPeaceWeightRand": 3,
			"iMaxGoldPerTurnTradePercent": 10,
			"iDeclareWarTradeRand": 40,
			"iAttackOddsChangeRand": 8,
			"iLostWarAttitudeChange": -1,
			"iAtWarAttitudeDivisor": -5,
			"iAtWarAttitudeChangeLimit": 5,
			"iAtPeaceAttitudeDivisor": 60,
			"iAtPeaceAttitudeChangeLimit": 1,
			"iSameReligionAttitudeChange": 1,
			"iSameReligionAttitudeDivisor": 10,
			"iDifferentReligionAttitudeChange": -1,
			"iDifferentReligionAttitudeDivisor": -15,
			"iBonusTradeAttitudeDivisor": 50,
			"iBonusTradeAttitudeChangeLimit": 2,
			"iOpenBordersAttitudeDivisor": 25,
			"iOpenBordersAttitudeChangeLimit": 2,
			"iDefensivePactAttitudeDivisor": 12,
			"iDefensivePactAttitudeChangeLimit": 2,
			"iShareWarAttitudeChange": 1,
			"iShareWarAttitudeDivisor": 8,
			"iFavoriteCivicAttitudeChange": 1,
			"iFavoriteCivicAttitudeDivisor": 10,
			"iDemandTributeAttitudeThreshold": 0,
			"iNoGiveHelpAttitudeThreshold": 0,
			"iDefensivePactRefuseAttitudeThreshold": 1,
			"iPermanentAllianceRefuseAttitudeThreshold": 1,
			"iFreedomAppreciation": 10,
			"iLoveOfPeace": 0,
			"iContactReligionPressureDelayRaw": 50,
			"iContactReligionPressureRandRaw": 500,
			"iContactCivicPressureDelayRaw": 50,
			"iContactCivicPressureRandRaw": 50,
			"iContactJoinWarDelayRaw": 20,
			"iContactJoinWarRandRaw": 20,
			"iContactStopTradingDelayRaw": 20,
			"iContactStopTradingRandRaw": 50,
			"iContactGiveHelpDelayRaw": 50,
			"iContactGiveHelpRandRaw": 25,
			"iContactAskForHelpDelayRaw": 50,
			"iContactAskForHelpRandRaw": 50,
			"iContactDemandTributeDelayRaw": 50,
			"iContactDemandTributeRandRaw": 0,
			"iContactTradeTechDelayRaw": 30,
			"iContactTradeTechRandRaw": 2,
			"iContactTradeBonusDelayRaw": 20,
			"iContactTradeBonusRandRaw": 2,
			"iContactPeaceTreatyDelayRaw": 8,
			"iContactPeaceTreatyRandRaw": 10,
			"iContactOpenBordersDelayRaw": 40,
			"iContactOpenBordersRandRaw": 10,
			"iContactDefensivePactDelayRaw": 20,
			"iContactDefensivePactRandRaw": 80,
			"iContactPermanentAllianceDelayRaw": 20,
			"iContactPermanentAllianceRandRaw": 80,
			"iContactTradeMapDelayRaw": 50,
			"iContactTradeMapRandRaw": 20,
			"iAggregatedContactReligionPressureProb": 53,
			"iAggregatedContactCivicPressureProb": 100,
			"iAggregatedContactJoinWarProb": 0,
			"iAggregatedContactStopTradingProb": 50,
			"iAggregatedContactGiveHelpProb": 100,
			"iAggregatedContactAskForHelpProb": 97,
			"iAggregatedContactDemandTributeProb": 0,
			"iAggregatedContactTradeTechProb": 95,
			"iAggregatedContactTradeBonusProb": 93,
			"iAggregatedContactPeaceTreatyProb": 100,
			"iAggregatedContactOpenBordersProb": 50,
			"iAggregatedContactDefensivePactProb": 50,
			"iAggregatedContactPermanentAllianceProb": 50,
			"iAggregatedContactTradeMapProb": 50,
			"iPositiveMemoryAttitudeGiveHelpRaw": 100,
			"iPositiveMemoryDecayGiveHelpRaw": 150,
			"iPositiveMemoryAttitudeAcceptDemandRaw": 100,
			"iPositiveMemoryDecayAcceptDemandRaw": 30,
			"iPositiveMemoryAttitudeAcceptedReligionRaw": 100,
			"iPositiveMemoryDecayAcceptedReligionRaw": 100,
			"iPositiveMemoryAttitudeAcceptedCivicRaw": 100,
			"iPositiveMemoryDecayAcceptedCivicRaw": 100,
			"iPositiveMemoryAttitudeAcceptedJoinWarRaw": 100,
			"iPositiveMemoryDecayAcceptedJoinWarRaw": 100,
			"iPositiveMemoryAttitudeAcceptedStopTradingRaw": 50,
			"iPositiveMemoryDecayAcceptedStopTradingRaw": 50,
			"iPositiveMemoryAttitudeVotedForUsRaw": 200,
			"iPositiveMemoryDecayVotedForUsRaw": 10,
			"iPositiveMemoryAttitudeEventGoodToUsRaw": 100,
			"iPositiveMemoryDecayEventGoodToUsRaw": 50,
			"iPositiveMemoryAttitudeLiberatedCitiesRaw": 150,
			"iPositiveMemoryDecayLiberatedCitiesRaw": 150,
			"iPositiveMemoryAttitudeIndependenceRaw": 100,
			"iPositiveMemoryDecayIndependenceRaw": 30,
			"iPositiveMemoryAttitudeTradedTechToUsRaw": 5,
			"iPositiveMemoryDecayTradedTechToUsRaw": 25,
			"iAggregatedPositiveMemoryGiveHelpAffection": 50,
			"iAggregatedPositiveMemoryAcceptDemandAffection": 50,
			"iAggregatedPositiveMemoryAcceptedReligionAffection": 50,
			"iAggregatedPositiveMemoryAcceptedCivicAffection": 50,
			"iAggregatedPositiveMemoryAcceptedJoinWarAffection": 50,
			"iAggregatedPositiveMemoryAcceptedStopTradingAffection": 50,
			"iAggregatedPositiveMemoryVotedForUsAffection": 50,
			"iAggregatedPositiveMemoryEventGoodToUsAffection": 50,
			"iAggregatedPositiveMemoryLiberatedCitiesAffection": 50,
			"iAggregatedPositiveMemoryIndependenceAffection": 50,
			"iAggregatedPositiveMemoryTradedTechToUsAffection": 0,
			"iAggregatedPositiveMemoryGiveHelpResentment": 50,
			"iAggregatedPositiveMemoryAcceptDemandResentment": 50,
			"iAggregatedPositiveMemoryAcceptedReligionResentment": 50,
			"iAggregatedPositiveMemoryAcceptedCivicResentment": 50,
			"iAggregatedPositiveMemoryAcceptedJoinWarResentment": 50,
			"iAggregatedPositiveMemoryAcceptedStopTradingResentment": 50,
			"iAggregatedPositiveMemoryVotedForUsResentment": 50,
			"iAggregatedPositiveMemoryEventGoodToUsResentment": 50,
			"iAggregatedPositiveMemoryLiberatedCitiesResentment": 50,
			"iAggregatedPositiveMemoryIndependenceResentment": 50,
			"iAggregatedPositiveMemoryTradedTechToUsResentment": 50,
			"iNegativeMemoryAttitudeDeclaredWarRaw": -300,
			"iNegativeMemoryDecayDeclaredWarRaw": 150,
			"iNegativeMemoryAttitudeDeclaredWarOnFriendRaw": -200,
			"iNegativeMemoryDecayDeclaredWarOnFriendRaw": 120,
			"iNegativeMemoryAttitudeHiredWarAllyRaw": -200,
			"iNegativeMemoryDecayHiredWarAllyRaw": 75,
			"iNegativeMemoryAttitudeNukedUsRaw": -200,
			"iNegativeMemoryDecayNukedUsRaw": 120,
			"iNegativeMemoryAttitudeNukedFriendRaw": -200,
			"iNegativeMemoryDecayNukedFriendRaw": 80,
			"iNegativeMemoryAttitudeRazedCityRaw": -250,
			"iNegativeMemoryDecayRazedCityRaw": 75,
			"iNegativeMemoryAttitudeRazedHolyCityRaw": -200,
			"iNegativeMemoryDecayRazedHolyCityRaw": 150,
			"iNegativeMemoryAttitudeSpyCaughtRaw": -100,
			"iNegativeMemoryDecaySpyCaughtRaw": 40,
			"iNegativeMemoryAttitudeRefusedHelpRaw": 0,
			"iNegativeMemoryDecayRefusedHelpRaw": 100,
			"iNegativeMemoryAttitudeRejectedDemandRaw": 0,
			"iNegativeMemoryDecayRejectedDemandRaw": 90,
			"iNegativeMemoryAttitudeDeniedReligionRaw": 0,
			"iNegativeMemoryDecayDeniedReligionRaw": 50,
			"iNegativeMemoryAttitudeDeniedCivicRaw": 0,
			"iNegativeMemoryDecayDeniedCivicRaw": 50,
			"iNegativeMemoryAttitudeDeniedJoinWarRaw": 0,
			"iNegativeMemoryDecayDeniedJoinWarRaw": 100,
			"iNegativeMemoryAttitudeDeniedStopTradingRaw": 0,
			"iNegativeMemoryDecayDeniedStopTradingRaw": 50,
			"iNegativeMemoryAttitudeStoppedTradingRecentRaw": 0,
			"iNegativeMemoryDecayStoppedTradingRecentRaw": 18,
			"iNegativeMemoryAttitudeStoppedTradingRaw": 0,
			"iNegativeMemoryDecayStoppedTradingRaw": 60,
			"iNegativeMemoryAttitudeHiredTradeEmbargoRaw": -100,
			"iNegativeMemoryDecayHiredTradeEmbargoRaw": 60,
			"iNegativeMemoryAttitudeMadeDemandRaw": -100,
			"iNegativeMemoryDecayMadeDemandRaw": 30,
			"iNegativeMemoryAttitudeMadeDemandRecentRaw": 0,
			"iNegativeMemoryDecayMadeDemandRecentRaw": 20,
			"iNegativeMemoryAttitudeVotedAgainstUsRaw": 0,
			"iNegativeMemoryDecayVotedAgainstUsRaw": 10,
			"iNegativeMemoryAttitudeEventBadToUsRaw": -100,
			"iNegativeMemoryDecayEventBadToUsRaw": 50,
			"iNegativeMemoryAttitudeCancelledOpenBordersRaw": 0,
			"iNegativeMemoryDecayCancelledOpenBordersRaw": 10,
			"iNegativeMemoryAttitudeCancelledVassalAgreementRaw": 0,
			"iNegativeMemoryDecayCancelledVassalAgreementRaw": 10,
			"iNegativeMemoryAttitudeCancelledDefensivePactRaw": 0,
			"iNegativeMemoryDecayCancelledDefensivePactRaw": 10,
			"iNegativeMemoryAttitudeDeclaredWarRecentRaw": 0,
			"iNegativeMemoryDecayDeclaredWarRecentRaw": 11,
			"iNegativeMemoryAttitudeReceivedTechFromAnyRaw": 0,
			"iNegativeMemoryDecayReceivedTechFromAnyRaw": 20,
			"iAggregatedNegativeMemoryDeclaredWarAffection": 50,
			"iAggregatedNegativeMemoryDeclaredWarOnFriendAffection": 50,
			"iAggregatedNegativeMemoryHiredWarAllyAffection": 50,
			"iAggregatedNegativeMemoryNukedUsAffection": 50,
			"iAggregatedNegativeMemoryNukedFriendAffection": 50,
			"iAggregatedNegativeMemoryRazedCityAffection": 50,
			"iAggregatedNegativeMemoryRazedHolyCityAffection": 50,
			"iAggregatedNegativeMemorySpyCaughtAffection": 50,
			"iAggregatedNegativeMemoryRefusedHelpAffection": 50,
			"iAggregatedNegativeMemoryRejectedDemandAffection": 50,
			"iAggregatedNegativeMemoryDeniedReligionAffection": 50,
			"iAggregatedNegativeMemoryDeniedCivicAffection": 50,
			"iAggregatedNegativeMemoryDeniedJoinWarAffection": 50,
			"iAggregatedNegativeMemoryDeniedStopTradingAffection": 50,
			"iAggregatedNegativeMemoryStoppedTradingRecentAffection": 50,
			"iAggregatedNegativeMemoryStoppedTradingAffection": 50,
			"iAggregatedNegativeMemoryHiredTradeEmbargoAffection": 50,
			"iAggregatedNegativeMemoryMadeDemandAffection": 50,
			"iAggregatedNegativeMemoryMadeDemandRecentAffection": 50,
			"iAggregatedNegativeMemoryVotedAgainstUsAffection": 50,
			"iAggregatedNegativeMemoryEventBadToUsAffection": 50,
			"iAggregatedNegativeMemoryCancelledOpenBordersAffection": 50,
			"iAggregatedNegativeMemoryCancelledVassalAgreementAffection": 50,
			"iAggregatedNegativeMemoryCancelledDefensivePactAffection": 50,
			"iAggregatedNegativeMemoryDeclaredWarRecentAffection": 50,
			"iAggregatedNegativeMemoryReceivedTechFromAnyAffection": 50,
			"iAggregatedNegativeMemoryDeclaredWarResentment": 50,
			"iAggregatedNegativeMemoryDeclaredWarOnFriendResentment": 100,
			"iAggregatedNegativeMemoryHiredWarAllyResentment": 50,
			"iAggregatedNegativeMemoryNukedUsResentment": 50,
			"iAggregatedNegativeMemoryNukedFriendResentment": 100,
			"iAggregatedNegativeMemoryRazedCityResentment": 50,
			"iAggregatedNegativeMemoryRazedHolyCityResentment": 50,
			"iAggregatedNegativeMemorySpyCaughtResentment": 0,
			"iAggregatedNegativeMemoryRefusedHelpResentment": 0,
			"iAggregatedNegativeMemoryRejectedDemandResentment": 0,
			"iAggregatedNegativeMemoryDeniedReligionResentment": 0,
			"iAggregatedNegativeMemoryDeniedCivicResentment": 0,
			"iAggregatedNegativeMemoryDeniedJoinWarResentment": 0,
			"iAggregatedNegativeMemoryDeniedStopTradingResentment": 0,
			"iAggregatedNegativeMemoryStoppedTradingRecentResentment": 50,
			"iAggregatedNegativeMemoryStoppedTradingResentment": 0,
			"iAggregatedNegativeMemoryHiredTradeEmbargoResentment": 50,
			"iAggregatedNegativeMemoryMadeDemandResentment": 0,
			"iAggregatedNegativeMemoryMadeDemandRecentResentment": 50,
			"iAggregatedNegativeMemoryVotedAgainstUsResentment": 0,
			"iAggregatedNegativeMemoryEventBadToUsResentment": 50,
			"iAggregatedNegativeMemoryCancelledOpenBordersResentment": 50,
			"iAggregatedNegativeMemoryCancelledVassalAgreementResentment": 50,
			"iAggregatedNegativeMemoryCancelledDefensivePactResentment": 50,
			"iAggregatedNegativeMemoryDeclaredWarRecentResentment": 50,
			"iAggregatedNegativeMemoryReceivedTechFromAnyResentment": 50
		},
    }
