[file]
savefile=PublicMaps\WB_Maps\Vadus_World.CivBeyondSwordWBSave

[map]
sizeX=84
sizeY=52

[civs]
CIVILIZATION_AMERICA=23,36
CIVILIZATION_ARABIA=53,30
CIVILIZATION_AZTEC=17,32
CIVILIZATION_BABYLON=52,33
CIVILIZATION_BYZANTIUM=48,35
CIVILIZATION_CARTHAGE=43,32
CIVILIZATION_CELT=41,37
CIVILIZATION_CHINA=68,37
CIVILIZATION_EGYPT=49,31
CIVILIZATION_ENGLAND=39,41
CIVILIZATION_ETHIOPIA=51,26
CIVILIZATION_FRANCE=41,39
CIVILIZATION_GERMANY=45,40
CIVILIZATION_GREECE=46,34
CIVILIZATION_HOLY_ROMAN=43,39
CIVILIZATION_INCA=25,21
CIVILIZATION_INDIA=61,31
CIVILIZATION_JAPAN=73,35
CIVILIZATION_KHMER=66,29
CIVILIZATION_KOREA=71,36
CIVILIZATION_MALI=43,27
CIVILIZATION_MAYA=21,31
CIVILIZATION_MONGOL=62,39
CIVILIZATION_NATIVE_AMERICA=17,39
CIVILIZATION_NETHERLANDS=42,40
CIVILIZATION_OTTOMAN=48,35
CIVILIZATION_PERSIA=55,33
CIVILIZATION_PORTUGAL=38,35
CIVILIZATION_ROME=43,35
CIVILIZATION_RUSSIA=50,40
CIVILIZATION_SPAIN=39,35
CIVILIZATION_SUMERIA=52,33
CIVILIZATION_VIKING=43,45
CIVILIZATION_ZULU=49,19