[file]
savefile=PublicMaps\WB_Maps\Earth.CivBeyondSwordWBSave

[map]
sizeX=124
sizeY=68

[civs]
CIVILIZATION_AMERICA=29,46
CIVILIZATION_ARABIA=75,35
CIVILIZATION_AZTEC=18,38
CIVILIZATION_BABYLON=78,41
CIVILIZATION_BYZANTIUM=68,46
CIVILIZATION_CARTHAGE=59,42
CIVILIZATION_CELT=58,49
CIVILIZATION_CHINA=102,47
CIVILIZATION_EGYPT=69,37
CIVILIZATION_ENGLAND=56,53
CIVILIZATION_ETHIOPIA=69,31
CIVILIZATION_FRANCE=58,51
CIVILIZATION_GERMANY=61,52
CIVILIZATION_GREECE=67,43
CIVILIZATION_HOLY_ROMAN=60,52
CIVILIZATION_INCA=30,23
CIVILIZATION_INDIA=93,39
CIVILIZATION_JAPAN=115,46
CIVILIZATION_KHMER=102,34
CIVILIZATION_KOREA=109,46
CIVILIZATION_MALI=58,32
CIVILIZATION_MAYA=23,36
CIVILIZATION_MONGOL=99,52
CIVILIZATION_NATIVE_AMERICA=23,49
CIVILIZATION_NETHERLANDS=59,52
CIVILIZATION_OTTOMAN=69,45
CIVILIZATION_PERSIA=82,40
CIVILIZATION_PORTUGAL=53,45
CIVILIZATION_ROME=61,46
CIVILIZATION_RUSSIA=72,55
CIVILIZATION_SPAIN=55,46
CIVILIZATION_SUMERIA=78,40
CIVILIZATION_VIKING=61,61
CIVILIZATION_ZULU=68,18