[file]
savefile=PublicMaps\WB_Maps\EarthEvolution.CivBeyondSwordWBSave

[map]
sizeX=124
sizeY=68

[civs]
CIVILIZATION_AMERICA=26,45
CIVILIZATION_ARABIA=75,33
CIVILIZATION_AZTEC=18,37
CIVILIZATION_BABYLON=76,42
CIVILIZATION_BYZANTIUM=68,45
CIVILIZATION_CARTHAGE=57,39
CIVILIZATION_CELT=51,59
CIVILIZATION_CHINA=103,45
CIVILIZATION_EGYPT=69,34
CIVILIZATION_ENGLAND=53,54
CIVILIZATION_ETHIOPIA=72,20
CIVILIZATION_FRANCE=55,50
CIVILIZATION_GERMANY=63,52
CIVILIZATION_GREECE=67,41
CIVILIZATION_HOLY_ROMAN=62,48
CIVILIZATION_INCA=26,22
CIVILIZATION_INDIA=90,40
CIVILIZATION_JAPAN=113,45
CIVILIZATION_KHMER=102,33
CIVILIZATION_KOREA=109,46
CIVILIZATION_MALI=54,30
CIVILIZATION_MAYA=22,36
CIVILIZATION_MONGOL=97,56
CIVILIZATION_NATIVE_AMERICA=11,52
CIVILIZATION_NETHERLANDS=57,53
CIVILIZATION_OTTOMAN=85,49
CIVILIZATION_PERSIA=82,38
CIVILIZATION_PORTUGAL=49,43
CIVILIZATION_ROME=60,44
CIVILIZATION_RUSSIA=73,54
CIVILIZATION_SPAIN=54,44
CIVILIZATION_SUMERIA=77,39
CIVILIZATION_VIKING=63,61
CIVILIZATION_ZULU=68,12