TOOLKIT=$(PROGRAMFILES)/Civ4SDK/Microsoft Visual C++ Toolkit 2003
PSDK=$(PROGRAMFILES)/Civ4SDK\WindowsSDK
CIV4_PATH=$(PROGRAMFILES)/Steam/steamapps/common/Sid Meier's Civilization IV Beyond the Sword
